### ISSUE TITLE
Initiate a Forkless Runtime Upgrade error impl pallet_scheduler::Config for Runtime  missing `PreimageProvider`, `NoPreimagePostponement` in implementation

### ISSUE THREAD

**Issue by techyangj** [substrate-developer-hub/substrate-docs#1003]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Bug report for compiling, code snippets, templates, etc.

When bulid the upgraded runtime, occur error
cargo build --release -p node-template-runtime
error:
impl pallet_scheduler::Config for Runtime { missing `PreimageProvider`, `NoPreimagePostponement` in implementation
help: implement the missing item: `type PreimageProvider = Type;`
      = help: implement the missing item: `type NoPreimagePostponement = Type;`

### Steps to reproduce the problem

Learn the official tutorial：Initiate a Forkless Runtime Upgrade

bulid the upgraded runtime
cargo build --release -p node-template-runtime  

error

**Comment by NukeManDan** [comment]
https://substrate.stackexchange.com/questions/2663/substrate-forkless-upgrade-tutorial-pallet-scheduler-has-breaking-changes
