### ISSUE TITLE
Kitties Tutorials Images

### ISSUE THREAD

**Issue by imadarai** [substrate-developer-hub/substrate-docs#101]
Can we move Kitties Tutorials Images under `src/images/tutorials` folder. 
Or is there a reason to place them under static folder - as they might need to be linked externally? 

<img width="138" alt="Screenshot 2021-09-23 at 11 55 55" src="https://user-images.githubusercontent.com/57454832/134488281-41c90efb-d7a8-404d-bd7b-35af060a52b5.png">
<img width="146" alt="Screenshot 2021-09-23 at 11 55 47" src="https://user-images.githubusercontent.com/57454832/134488284-1972a93d-e17f-4a61-9158-62b7d6e36e52.png">

**Comment by sacha-l** [comment]
We decided to stick to what we currently have for now, and revise this in the next batch of updates. So long as this scheme doesn't introduce any broken links, I'm fine with it (and it doesn't AFAIK).
