### ISSUE TITLE
error: failed to run custom build command for `tikv-jemalloc-sys v0.4.3+5.2.1-patched.2`

### ISSUE THREAD

**Issue by neykrom** [substrate-developer-hub/substrate-docs#1035]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Bug report for compiling, code snippets, templates, etc.

Hi. need help. I am on :
Intel core i5 CPU M430 2.27GHz x4
Memory: 3.6 GiB
graphic card NVA5 intel HD Graphics (ILK)
Ubutu 20.04.4 LTS --- 64 bit --- gnome 3.36.8

Tutoriel
Prepare a Substrate node using the node template
cargo build --release

I have the following error:
Compiling rand_distr v0.4.3
error: failed to run custom build command for `tikv-jemalloc-sys v0.4.3+5.2.1-patched.2`

Caused by:
  process didn't exit successfully: `/home/nonqme/substrate-node-template/target/release/build/tikv-jemalloc-sys-b789a6952291f23f/build-script-build` (exit status: 101)
  --- stdout
  TARGET=x86_64-unknown-linux-gnu
  HOST=x86_64-unknown-linux-gnu
  NUM_JOBS=4
  OUT_DIR="/home/nonqme/substrate-node-template/target/release/build/tikv-jemalloc-sys-68994192a6deaa0f/out"
  BUILD_DIR="/home/nonqme/substrate-node-template/target/release/build/tikv-jemalloc-sys-68994192a6deaa0f/out/build"
  SRC_DIR="/home/nonqme/.cargo/registry/src/github.com-1ecc6299db9ec823/tikv-jemalloc-sys-0.4.3+5.2.1-patched.2"
  OPT_LEVEL = Some("3")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu=None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  CC="cc"
  CFLAGS="-O3 -ffunction-sections -fdata-sections -fPIC -m64 -Wall"
  JEMALLOC_REPO_DIR="jemalloc"
  running: "sh" "/home/nonqme/substrate-node-template/target/release/build/tikv-jemalloc-sys-68994192a6deaa0f/out/build/configure" "--disable-cxx" "--with-private -namespace=_rjem_" "--host=x86_64-unknown-linux-gnu" "--build=x86_64-unknown-linux-gnu" "--prefix=/home/nonqme/substrate-node-template/target/release /build/tikv-jemalloc-sys-68994192a6deaa0f/out"
  checking for xsltproc... false

### Steps to reproduce the problem

Tutoriel
Prepare a Substrate node using the node template
cargo build --release

**Comment by NukeManDan** [comment]
I think #1081 and #1026 should solve this

**Comment by anrichp** [comment]
Hi all I have followed the instructions within the tutorial and ensured that make is installed; however I continue receiving the error as above: 

error: failed to run custom build command for `tikv-jemalloc-sys v0.4.3+5.2.1-patched.2`

Windows 11 running WSL:
Distributor ID: Ubuntu
Description: Ubuntu 20.04.4 LTS
Release: 20.04
Codename: focal

--- stdout
  TARGET=x86_64-unknown-linux-gnu
  HOST=x86_64-unknown-linux-gnu
  NUM_JOBS=16
  OUT_DIR="/mnt/c/Users/anric/substrate-node-template/target/release/build/tikv-jemalloc-sys-589f2417f775c6fa/out"
  BUILD_DIR="/mnt/c/Users/anric/substrate-node-template/target/release/build/tikv-jemalloc-sys-589f2417f775c6fa/out/build"
  SRC_DIR="/home/anrichp/.cargo/registry/src/github.com-1ecc6299db9ec823/tikv-jemalloc-sys-0.4.3+5.2.1-patched.2"
  OPT_LEVEL = Some("3")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  CC="cc"
  CFLAGS="-O3 -ffunction-sections -fdata-sections -fPIC -m64 -Wall"
  JEMALLOC_REPO_DIR="jemalloc"

**Comment by Tidus91** [comment]
i have the exact same problem, tried to fix it with those propositions but it's not working
