### ISSUE TITLE
Depricate ExternalLink component

### ISSUE THREAD

**Issue by sacha-l** [substrate-developer-hub/substrate-docs#104]
The `ExternalLink` component is nice but a little annoying to use. Docs currently have so many links and it would be nice remove the potential overhead for contributors referring to outside links by automating this on the Gatsby side. 

The idea would be that any page with links that aren't internal to Substrate.io automatically render as `ExternalLink` components. 

I'm not sure how exactly this could be done but Ethereum.org does this somehow. For example, here's what their page with external and internal links looks like:

![Screen Shot 2021-09-23 at 3 01 55 PM](https://user-images.githubusercontent.com/23283108/134511497-a90d85f1-47fe-41f8-a9d1-342806836a7f.png)

And [here's](https://github.com/ethereum/ethereum-org-website/edit/dev/src/content/developers/docs/programming-languages/rust/index.md) the source code for that page. Putting this a `phase-2` because it's not a blocker on launching but thought may as well start the discussion here.

**Comment by NukeManDan** [comment]
This was fixed in #223 for reference :tada:
