### ISSUE TITLE
Migrate Substrate github Wiki

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-docs#105]
https://github.com/paritytech/substrate/wiki/ has a few pages that should be ported into the devhub (that are still relevant) and the wiki pages removed:

![image](https://user-images.githubusercontent.com/35669742/134574313-1ac99ad8-3fc1-4e9c-b0ab-468a30619250.png)

Options as I see them (open for comment):
- [ ] ~~Leave the top level page as is pointing to the correct devhub URL or~~ remove the wiki completely. #
- [ ] Migrate historical pages accessible is some new section on the devhub for reference **or** delete completely **or** migrate to another location outside devhub

**Comment by sacha-l** [comment]
Added in #117.

**Comment by NukeManDan** [comment]
So are we agreed that an issue to remove the wiki from substrate is good to go on launch of the site? If so, we should create a tracking/reminder issue for it.

Perhaps an overall launch checklist issue tracker?

**Comment by sacha-l** [comment]
@NukeManDan added here: https://github.com/substrate-developer-hub/substrate-docs/issues/107
