### ISSUE TITLE
scale codec: Note about boolean option is confusing

### ISSUE THREAD

**Issue by eldargab** [substrate-developer-hub/substrate-docs#1061]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Bug report for compiling, code snippets, templates, etc.

[Article](https://github.com/substrate-developer-hub/substrate-docs/blob/50ae063248fe27ae589d1bbdc368968433363345/v3/docs/07-advanced/b-scale-codec/index.mdx#options) about scale encoding of `Option<T>` mentions special handling of `Option<bool>` case.  However, in actual scale encoded data from substrate nodes `Option<bool>` is treated as regular option type and takes 2 bytes instead of 1.

**Comment by NukeManDan** [comment]
#1094  shoulds fix @eldargab please re-open if you disagree
