### ISSUE TITLE
Broken Link: Society pallet

### ISSUE THREAD

**Issue by laurogripa** [substrate-developer-hub/substrate-docs#1088]
The society pallet is mentioned on Polkadot Wiki but the link is broken.

Wiki article: https://wiki.polkadot.network/docs/maintain-guides-society-kusama

This link can be found in the first sentence: https://docs.substrate.io/rustdocs/latest/pallet_society/index.html

I couldn't find the documentation about this pallet

**Comment by sacha-l** [comment]
Thanks for flagging this @laurogripa ! 

This should fix it : https://github.com/w3f/polkadot-wiki/pull/3425
