### ISSUE TITLE
Broken Links for `/rustdocs`

### ISSUE THREAD

**Issue by Wiezzel** [substrate-developer-hub/substrate-docs#1096]
https://docs.substrate.io/rustdocs/latest/pallet_randomness_collective_flip/index.html gives 404
This site popped up as the second result when googling "RandomnessCollectiveFlip".

**Comment by NukeManDan** [comment]
latest isn't maintained, possibly some build issues blocking https://github.com/substrate-developer-hub/substrate-docs/issues/428
It will soon be deprecated.

## please use https://paritytech.github.io/substrate/master/sc_service/index.html
For the time being.

**Comment by lisa-parity** [comment]
All of the rustdocs links have changed and this one is no longer in the doc.
