### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by shiyivei** [substrate-developer-hub/substrate-docs#1100]
the [Substrate RPC API](https://docs.substrate.io/rustdocs/latest/sc_rpc_api/index.html) landing page is 404

**Comment by lisa-parity** [comment]
@jonnysmillie, do you know where this reference is? Maybe the issue is fixed already?I'm not finding this link in the current doc:
https://docs.substrate.io/rustdocs/latest/sc_rpc_api/index.html

**Comment by lisa-parity** [comment]
This link isn't in the documentation anymore and we aren't using the rustdocs path, so this is a no op. Closing.
