### ISSUE TITLE
Main-md Latest Polkadot Version should be used in upcoming version of document

### ISSUE THREAD

**Issue by ayushmishra2005** [substrate-developer-hub/substrate-docs#1101]
I was reviewing this https://substrate-docs-md.netlify.app/tutorials/connect-other-chains/relay-chain/#hardware-and-software-requirements and found that this document is using `Polkadot-v0.9.18` for cumulus workshop. 

It should be similar to https://docs.substrate.io/tutorials/v3/cumulus/start-relay/#software-versioning

**Comment by NukeManDan** [comment]
Agreed! Cc @lisa-parity  we must ensure the versions are updated to the latest release of Polkadot before launch.

**Comment by lsgunnlsgunn** [comment]
Goes this mean changing the version in the content or changing the 'latest' tag to point to a different version, or both?

**Comment by lisa-parity** [comment]
Closing as an outdated issue. Main-md is no more.
