### ISSUE TITLE
Broken Link rustdocs

### ISSUE THREAD

**Issue by blockedby** [substrate-developer-hub/substrate-docs#1103]
Link from https://wiki.polkadot.network/docs/build-protocol-info#existential-deposit at paragraph "Free vs. Reserved vs. Locked vs. Vesting Balance" is broken.

Link is https://docs.substrate.io/rustdocs/latest/frame_support/traits/trait.LockableCurrency.html

**Comment by NukeManDan** [comment]
Will be sortof fixed with a redirected in #1054
