### ISSUE TITLE
Size of boarders in not uniform, too large

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-docs#1110]
All on on my 1920x1080 monitor. Yellow indicates the spaces. Based on the present https://substrate-docs-md.netlify.app/main-docs/ deployment (main-md)

---

The right side has to much space and is asymmetric:

![s1](https://user-images.githubusercontent.com/35669742/173197538-0e8b69e8-8a0f-4b23-974a-5f9999c78c8b.png)

---

Especially when there is no "on this page" section (should this ever happen?) there is IMHO too much room on the side:

![s2](https://user-images.githubusercontent.com/35669742/173197539-845242a0-dc0c-4dd8-8d4b-bd8b53301039.png)

---

Zoomed in to 175% this is symetric it seems, before it goes to mobile view with no side nav:

![z1](https://user-images.githubusercontent.com/35669742/173197543-2a6bea28-75da-4e84-a4db-19da5bb60002.png)

**Comment by jonnysmillie** [comment]
Hi @NukeManDan you are indeed correct that the layout is not symmetrical. I deviated from the design and previous implementation slightly in an attempt to make better use of the available space but I agree that it would more visually consistent if the distance between the sections within the main body of content are the same.

This is the change I would propose:
![Screenshot 2022-06-23 at 10 35 12](https://user-images.githubusercontent.com/7614348/175269383-68c33a13-30fe-44ec-82d7-a98451be31e7.png)
![Screenshot 2022-06-23 at 10 37 11](https://user-images.githubusercontent.com/7614348/175269440-3410d5a4-298f-4de7-b9bf-3a6c735d383a.png)
