### ISSUE TITLE
Broken Links in tutorial

### ISSUE THREAD

**Issue by thadouk** [substrate-developer-hub/substrate-docs#1162]
In the "Start a local relay chain" tutorial
https://docs.substrate.io/tutorials/connect-other-chains/relay-chain/
Under the[ Pre-configured chain spec files](https://docs.substrate.io/tutorials/connect-other-chains/relay-chain/#pre-configured-chain-spec-files) section:

The links for the chainspecs are broken:
- https://docs.substrate.io/assets/tutorials/cumulus/chain-spec/rococo-custom-2-plain.json/
- https://docs.substrate.io/assets/tutorials/cumulus/chain-spec/rococo-custom-2-raw.json/

There are also several image links missing. For example in https://docs.substrate.io/tutorials/connect-other-chains/parachain/#block-finalization :
```
<Image is missing>
```

**Comment by NukeManDan** [comment]
included in #1140
