### ISSUE TITLE
Edit Button

### ISSUE THREAD

**Issue by dejanzivanov** [substrate-developer-hub/substrate-docs#1170]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Content request

Already existing button on the doc page is barely visible, i didn't see it until one of the developers pointed out, that there is edit button at the top of the page.

So my proposal is, can design be a little bit more "eye catching". So future developers know where to look out if they encounter a certain problem.

![image](https://user-images.githubusercontent.com/77687815/175398279-fe2f014c-9eba-4a4d-a0d1-57ab3b995d07.png)

As you can see Edit button perfectly blended with background as an arctic fox in arctic :D

### Are you willing to help with this request?

No.

**Comment by NukeManDan** [comment]
The top now reads `Edit this page` - and there is also a link to the page on github in the footer that links to the page too, above the _large_ call to action to post an issue.

@dejanzivanov wdyt? Is this obvious enough? 

![image](https://user-images.githubusercontent.com/35669742/175756608-1ae7cd05-4c03-4042-a4c3-ed0d43fd9365.png)

**Comment by dejanzivanov** [comment]
Yep! It looks much better! and pretty obvious! Easy eyecatch
