### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by andresvsm-old** [substrate-developer-hub/substrate-docs#1176]
Broken links from [cumulus tutorial](https://docs.substrate.io/tutorials/connect-other-chains/relay-chain/) (custom specs)

https://docs.substrate.io/assets/tutorials/cumulus/chain-spec/rococo-custom-2-plain.json/

https://docs.substrate.io/assets/tutorials/cumulus/chain-spec/rococo-custom-2-raw.json/

**Comment by NukeManDan** [comment]
duplicate #1162
