### ISSUE TITLE
Private network

### ISSUE THREAD

**Issue by mjachi** [substrate-developer-hub/substrate-docs#1196]
### Broken Link

https://docs.substrate.io/tutorials/v3/private-network

### Expected Location

Looking for documentation/ tutorial on building a small private network with substrate.

### Context and Origin

I know I've come across this link in a few places, clicking around like a madman searching for about anything on the subject. The two I could find from recent memory (will add as I find any others)...

- [The Node template README](https://github.com/substrate-developer-hub/substrate-node-template/tree/latest). 
- Google/ Brave Search for a query in the neighborhood of "build a private chain substrate"... so, out of your control

I want to say that I remember finding the same link at some point in the actual documentation itself... maybe that's been caught already, or I'm just misremembering things.

**Comment by NukeManDan** [comment]
https://docs.substrate.io/tutorials/get-started/trusted-network/
