### ISSUE TITLE
Lock `main` branch

### ISSUE THREAD

**Issue by imadarai** [substrate-developer-hub/substrate-docs#120]
<img width="1032" alt="Screenshot 2021-09-27 at 17 43 36" src="https://user-images.githubusercontent.com/57454832/134941245-01bbbb31-7395-4c52-b9dd-d14d54998d98.png">

@jimmychu0807 I don't think I've the proper access, but can we please lock the `main` branch - similar to how we have it with the current website?

**Comment by jimmychu0807** [comment]
Main branch is now public and locked.
