### ISSUE TITLE
Runtime storage best practices - Verify First Write Last Requires Additional Info Since Polkadot-v0.9.25

### ISSUE THREAD

**Issue by timurguvenkaya** [substrate-developer-hub/substrate-docs#1215]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Content request

Section: https://docs.substrate.io/main-docs/build/runtime-storage/ (Verify First, Update Last)

In substrate polkadot-v0.9.25 branch (https://github.com/paritytech/substrate/tree/polkadot-v0.9.25) #[transactional] macro got deprecated since it is now default behavior (https://github.com/paritytech/substrate/pull/11546 & https://github.com/paritytech/substrate/pull/11431). So now, even if verification happens **after** storage update, the state won't persist. It will get reverted on Err. Hence, it makes sense to update that section according to new updates. It is still best practice to follow, but it needs updated information.

### Are you willing to help with this request?

Yes!

**Comment by lisa-parity** [comment]
@timurguvenkaya, information about transactional storage added to the documentation:
https://docs.substrate.io/build/runtime-storage/
