### ISSUE TITLE
Link to Plain Rococo relay chain spec file is broken

### ISSUE THREAD

**Issue by notstano** [substrate-developer-hub/substrate-docs#1216]
### Broken Link

https://github.com/substrate-developer-hub/substrate-docs/blob/main/static/assets/tutorials/cumulus/chain-specs/rococo-custom-2-plain.json

### Expected Location

https://github.com/substrate-developer-hub/substrate-docs/blob/main/static/assets/tutorials/cumulus%20(copy)/chain-specs/rococo-custom-2-plain.json

### Context and Origin

The _Pre-configured chain spec files_ section of the _Start a local relay chain_ tutorial https://docs.substrate.io/tutorials/connect-other-chains/local-relay/#relay-chain-specification

**Comment by NukeManDan** [comment]
#1218
