### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by nikania** [substrate-developer-hub/substrate-docs#1228]
In the [Cumulus section of Parachain Development on Polkadot wiki](https://wiki.polkadot.network/docs/build-pdk#cumulus)
exists broken link to the [parachain tutorials](https://docs.substrate.io/tutorials/connect-other-chains/relay-chain/)

**Comment by Imod7** [comment]
Maybe I can add here another link that appears to be broken. I found it in a [Substrate SE question](https://substrate.stackexchange.com/questions/1854/hardware-benchmark-standard-vs-ecosystem-nodes) and submitted a revision.
The link has the url : https://docs.substrate.io/v3/runtime/benchmarking/
and it looks like the correct one should be : https://docs.substrate.io/main-docs/test/benchmark/

**Comment by lisa-parity** [comment]
https://github.com/w3f/polkadot-wiki/pull/3520

**Comment by lisa-parity** [comment]
The link in the Polkadot wkik has been removed because the tutorials are still under construction. We'll put it back when then are updated.
