### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by muharem** [substrate-developer-hub/substrate-docs#1239]
Broken link - https://docs.substrate.io/rustdocs/v3.0.0/sp_api/trait.Core.html
From page - [Runtime Apis](https://substrate.recipes/runtime-api.html?highlight=rpc#runtime-apis)

**Comment by lisa-parity** [comment]
Hi @muharem ,
The recipes site is no longer being maintained. I wasn't able to spot the broken link. You can use this link thogh:
https://paritytech.github.io/substrate/master/sp_api/trait.Core.html
