### ISSUE TITLE
Code panel in docs have inconsistent width proportion at different screen width

### ISSUE THREAD

**Issue by jimmychu0807** [substrate-developer-hub/substrate-docs#124]
To reproduce them, have your screen on a page showing code panel and open to the widest, then slowly drag inward.

- Widest: ![03](https://user-images.githubusercontent.com/898091/135027963-af9d996a-dbc9-40af-a7f8-37f11615732d.png)

- Drag inward:
![02](https://user-images.githubusercontent.com/898091/135027989-ffea5a72-545d-4906-848a-6ef7f8bd6f46.png)

- Drag further inward: ![01](https://user-images.githubusercontent.com/898091/135027994-d47fe545-4340-4284-8e1e-9cb4dbda96cc.png)

**Comment by imadarai** [comment]
@jimmychu0807 Pushed a new version of the layout and addressed this.  
[Preview here](https://deploy-preview-148--substrate-docs-staging.netlify.app/v3/runtime/events-and-errors) 

Let me know if you have any thoughts, and I can merge it once done.

**Comment by jimmychu0807** [comment]
Nice fix.
