### ISSUE TITLE
Navigation bar doesn't have "Specify the origin for a call" guide

### ISSUE THREAD

**Issue by Berzhenium** [substrate-developer-hub/substrate-docs#1245]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### What browsers are you seeing the problem on?

Other (please write below)

### Bug report for the website

Guide called ["Specify the origin for a call"](https://docs.substrate.io/tutorials/work-with-pallets/specify-origin/)  is a part of ["Work With Pallets"](https://docs.substrate.io/tutorials/work-with-pallets/) chapter, but left navigation bar doesn't have that guide. Also none of  the previous/next button directs to that guide. Literally only one link to that important guide is placed in ["Next Steps" section in "Add a pallet to the runtime" guide](https://docs.substrate.io/tutorials/work-with-pallets/add-a-pallet/#next-steps) and it's easy to miss.

**Comment by lisa-parity** [comment]
with the merged PR a version of this content is available.
