### ISSUE TITLE
Cannot open the top menu in Safari (is it just me?)

### ISSUE THREAD

**Issue by jimmychu0807** [substrate-developer-hub/substrate-docs#126]
@imadarai 

When accessing https://substrate-docs-staging.netlify.app from my Safari, I cannot open the top menu bar. Not sure if it is just me.... If it is not, this is quite MAJOR.

Also attaching the console error when opening the page in Safari

![Screenshot 2021-09-28 at 15 23 06](https://user-images.githubusercontent.com/898091/135041919-29f4ee91-c998-4cca-b4ac-b6d27c0c2554.png)

**Comment by imadarai** [comment]
This gave me a heart-attack.  

It seems to be a [caching issue](https://answers.netlify.com/t/gatsbys-js-files-not-loading-because-of-content-type-mismatch-on-ios/29804/2) - but i'm going to investigate this further tomorrow.

**Comment by imadarai** [comment]
Clearing Cache and redeploying resolved this for me.  
@jimmychu0807 can you check on your end as well please 🙏 ? 
There is an issue with manifest json uploading - that delays any javascript to load, but that will be something to tackle at the very end.

**Comment by jimmychu0807** [comment]
Still doesn't work for me. I use a private window in Safari to test it.

**Comment by imadarai** [comment]
@jimmychu0807 Can you clear your cache and check again? 

I added two flags on `gatsby-netlify-plugin` that should resolve this for staging. 

```
{
      resolve: `gatsby-plugin-netlify`,
      options: {
        mergeLinkHeaders: false,
        mergeCachingHeaders: false,
      },
    },
```

**Comment by jimmychu0807** [comment]
@imadarai This is fixed. Very cool!
