### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by olliecorbisiero** [substrate-developer-hub/substrate-docs#1288]
2x 404 links here: 

https://core.tetcoin.org/docs/en/knowledgebase/runtime/upgrades#accessing-the-runtime-version

**Comment by lisa-parity** [comment]
Hi @olliecorbisiero, I think you'll need to contact the owner of the website you mention for a fix.
But the relevant content is here:
https://docs.substrate.io/main-docs/build/upgrade/#accessing-the-runtime-version
