### ISSUE TITLE
Broken Link_(srml_executive)

### ISSUE THREAD

**Issue by WB-Expert5007** [substrate-developer-hub/substrate-docs#1291]
I can't join this link, ```https://substrate.dev/rustdocs/v1.0/srml_executive/index.html```.
Where can I find this link?

**Comment by lisa-parity** [comment]
@WB-Expert5007 I'm not sure if this is still in use. Last mention of it seems to be 2019. In what context did you find the link? If you give me some hints about what are you trying to do, I'll see if I can find an answer or appropriate redirect.

**Comment by WB-Expert5007** [comment]
For example, please check below.

https://github.com/paritytech/substrate-open-working-groups/blob/main/SOWG/1-polkadot-token-standard.md
![image](https://user-images.githubusercontent.com/96474901/181526854-d1ad1340-c676-4771-afc0-1c2b54f04ddc.png)

This doesn't show any repo like this.
![image](https://user-images.githubusercontent.com/96474901/181527297-149385a0-1eb8-4b96-9971-419accecb8a6.png)

Thanks.

**Comment by lisa-parity** [comment]
Ah, so these appear to be links to external specs—in this case to Cosmos.
You might trying poking around here:
https://github.com/cosmos/ibc/tree/main/spec
And I'll add an issue in that repo that there are dead links, but that's not part of Substrate doc, so I'm closing the issue here.
