### ISSUE TITLE
Broken "Visualizing the Substrate code base" link

### ISSUE THREAD

**Issue by jsidorenko** [substrate-developer-hub/substrate-docs#1295]
### Broken Link

https://octo-repo-visualization.vercel.app/?repo=paritytech%2Fsubstrate

### Context and Origin

On the [Libraries page](https://docs.substrate.io/main-docs/build/libraries/) the link [Visualizing the Substrate code base](https://octo-repo-visualization.vercel.app/?repo=paritytech%2Fsubstrate) is broken (returns 404)

**Comment by lisa-parity** [comment]
Thanks for catching this!
Because this was a link to an external tool, there's no "fix" except to remove it.
