### ISSUE TITLE
M1. error: failed to run custom build command for 'prost-build v0.10.1'

### ISSUE THREAD

**Issue by bgodlin** [substrate-developer-hub/substrate-docs#1298]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Content request

Hello,
trying to go through the [installation steps](https://docs.substrate.io/main-docs/install/macos/) on M1 leading to `error: failed to run custom build command for 'prost-build v0.10.1'`. Issue could be solved by executing the commands from [this question](https://stackoverflow.com/questions/72061535/getting-this-error-message-while-installing-solana-error-failed-to-run-custom). Maybe it make sense to add the corresponding materials in the docs.

### Are you willing to help with this request?

Maybe (please elaborate above)

**Comment by lisa-parity** [comment]
@sacha-l , @NukeManDan Do you have an M1 machine to test this? The answer referenced is for Solana, but I don't have an M1 computer, so I can't check if this is a general fix.
Also, I think there was some issue uncovered in the academy around compiling on an M1 mac, but I never saw the error in question of the details of how it got fixed. 
I can certainly add something to doc is we know both the symptom and the fix.

**Comment by sacha-l** [comment]
I run an M1 but never have run into these problems. Perhaps let's leave this open in case other new users run into this issue and add this to our docs if needed.

**Comment by sacha-l** [comment]
Update: another user reported this bug here: #1324 and a fix here: #1327. :)
