### ISSUE TITLE
Multiple Main Tags 

### ISSUE THREAD

**Issue by carinaluise** [substrate-developer-hub/substrate-docs#1303]
## Accessibility Report
There are duplicate `<main>` tags within pages.

Landmarks can be used by assistive technology such as screen readers to quickly identify and navigate to large sections of the document. 

The `<main>` element has a role of `main`. There should only be one main landmark role per document, so that it is clear to the user where and how they can navigate to the main section of the page.

Example
<img width="720" alt="176189951-9fe2909b-0707-4ed7-8e14-1436e5b299ff" src="https://user-images.githubusercontent.com/60577717/180819218-11f17f0d-7b1e-45a3-af1f-c40fc9b03414.png">

**Comment by jonnysmillie** [comment]
I will remove the first main tag and keep the one that has the className `markdown-body`. Thanks.

**Comment by carinaluise** [comment]
Nice one thanks Jonny!! 👍
