### ISSUE TITLE
[recipes] Broken Link

### ISSUE THREAD

**Issue by Leo777** [substrate-developer-hub/substrate-docs#1307]
The link is broken for instant seal on page https://substrate.recipes/kitchen-node.html#kitchen-node-instant-seal

**Comment by lisa-parity** [comment]
Hi @Leo777 , I don't think anyone is maintaining the recipes site anymore, but you can find the information referenced here:
https://paritytech.github.io/substrate/master/sc_consensus_manual_seal/index.html
