### ISSUE TITLE
How can I insert Native token at special times?

### ISSUE THREAD

**Issue by WB-Expert5007** [substrate-developer-hub/substrate-docs#1321]
We are going to mint token every special times.
And Minted tokens should be transferred to Treasury as a Negative Imbalance.
For this, we are going to use ```on_intialize``` hook and ```treasury on_unbalanced method```.
How can I make this?
Please help me.
Thanks.

**Comment by NukeManDan** [comment]
I see you asking on stack exchange and dev chats. Issues here are not for support.
