### ISSUE TITLE
The tutorial "Connect a local parachain" documentation seems to be missing something.

### ISSUE THREAD

**Issue by artlotz** [substrate-developer-hub/substrate-docs#1333]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Bug report for compiling, code snippets, templates, etc.

Link: https://docs.substrate.io/tutorials/connect-other-chains/local-parachain/#custom-parachain-specification

Below the "Custom parachain specification" section is a "Save and distribute your raw spec" section.

The description in this section largely matches the description in the "Reserve a ParaID" section. I can't find any explanation of how to save and deploy the raw spec.

And if you look at the 'Option 2: slots.forceLease' item in the 'Parachain Registration' section, a screenshot of the registered Onboarding parathread appears, but there is no information about the registration method.
![image](https://user-images.githubusercontent.com/9390287/181833181-53e39c44-d253-4453-8334-4569042b7ded.png)

Here's how I found it:
\+ Click ParaThread -> Register Parathread popup -> Upload para-2000-wasm file, Upload para-2000-genesis file -> Click Submit

I completed the tutorial this way, I think the tutorial should explain it for the sake of accuracy.

**Comment by NukeManDan** [comment]
https://github.com/substrate-developer-hub/substrate-docs/blob/archive/main-mdx/v3/tutorials/09-cumulus/b-connecting-to-relay/index.mdx#configure-a-parachain-for-a-specific-relay-chain-and-para-id must have got garbled in the transition, thanks for the spot!
