### ISSUE TITLE
broken link : Access EVM accounts

### ISSUE THREAD

**Issue by artlotz** [substrate-developer-hub/substrate-docs#1334]
### Broken Link

https://docs.substrate.io/tutorials/connect-other-chains/access-evm-accounts/

### Expected Location

404 page

### Context and Origin

1. https://docs.substrate.io/tutorials/integrate-with-tools/access-evm-accounts/#where-to-go-next
2. "Ethereum integration" link click
3. In the "Where to go next" section, click the 3rd item "Access EVM accounts" link

* "Ethereum integration" page is a subcategory of "Integrate With Tools" but not in left side navigation

**Comment by lisa-parity** [comment]
It is sort of a side topic rather than part of the Substrate documentation, so it was intentionally left out of the left navigation. If I find a good place for it, I'll consider including it.
