### ISSUE TITLE
Broken Link in Transaction, weights and fees in mandatory dispatch under Dispatch classes

### ISSUE THREAD

**Issue by gflow33** [substrate-developer-hub/substrate-docs#1336]
### Broken Link

https://docs.substrate.io/main-docs/build/tx-weights-fees/

### Expected Location

https://docs.substrate.io/main-docs/fundamentals/transaction-types/ under transaction types

**Comment by NukeManDan** [comment]
Can you elaborate? What is the issue?

**Comment by gflow33** [comment]
There was a link in the documentation that was broken. The section is Transaction weight and fees specifically under  "mandatory dispatch". It was supposed to link to inherents transactions.
