### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by cxphong** [substrate-developer-hub/substrate-docs#1342]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### What browsers are you seeing the problem on?

Firefox

### Bug report for the website

<img width="1325" alt="Screen Shot 2022-08-01 at 15 08 40" src="https://user-images.githubusercontent.com/10628009/182105067-fb705d8c-4380-4b8b-8068-ecccf67b3ca8.png">

Typos at https://docs.substrate.io/tutorials/get-started/simulate-network/

**Comment by NukeManDan** [comment]
@cxphong why not file a PR to change this file? The linknis at the top right of every page btw
