### ISSUE TITLE
A typo

### ISSUE THREAD

**Issue by cuteOlaf** [substrate-developer-hub/substrate-docs#1353]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### What browsers are you seeing the problem on?

Chrome

### Bug report for the website

https://docs.substrate.io/main-docs/build/libraries/

There is a typo in the **core node libraries** section.

For example, the [sp_std](https://paritytech.github.io/substrate/master/sp_std/index.html) **libraris** takes useful primitives

**Comment by NukeManDan** [comment]
@cuteOlaf - why not make a pr? https://github.com/substrate-developer-hub/substrate-docs/blob/main/content/md/en/docs/main-docs/build/libraries.md

**Comment by cuteOlaf** [comment]
made a PR.
fixed
