### ISSUE TITLE
Benchmarks 'how-to guide' uses outdated syntax

### ISSUE THREAD

**Issue by Wiezzel** [substrate-developer-hub/substrate-docs#1355]
In am referring to [this guide](https://docs.substrate.io/reference/how-to-guides/weights/add-benchmarks/). In section **2. Add benchmarking to your runtime**, point 3. says:
> Then, in addition to your normal runtime configuration, you also need to update the benchmarking section of your runtime. To add our new benchmarks, we simply add a new line with the `add_benchmark!` macro

As far as I know, this syntax (`add_benchmark!`) has been deprecated in favour of a more convenient and easier `define_benchmarks!` in [this PR](https://github.com/paritytech/substrate/pull/10592). I'd like to request updating this section of the guide to use the new syntax.

**Comment by lisa-parity** [comment]
@ggwpez , Can you provide some guidance on what to change?
It seems like the add_benchmark! macro is still valid based on this:
https://paritytech.github.io/substrate/master/frame_benchmarking/index.html
and 
**Adding Benchmarks**
The benchmarks included with each pallet are not automatically added to your node. To actually execute these benchmarks, you need to implement the frame_benchmarking::Benchmark trait. You can see an example of how to do this in the [included Substrate node](https://github.com/paritytech/substrate/blob/master/bin/node/runtime/src/lib.rs).

Assuming there are already some benchmarks set up on your node, you just need to add another instance of the add_benchmark! macro:

///  configuration for running benchmarks
              ///               |    name of your pallet's crate (as imported)
                 ///            v                                  v
add_benchmark!(params, batches, pallet_balances, Balances);
                          ///                       ^                                         ^
                ///    where all benchmark results are saved         |
///            the `struct` created for your pallet by `construct_runtime!`

I wouldn't be at all surprised that this doc is out-of-date, but the How-to guide is pretty thin on details so I'm not sure what needs to change (well, actually, it probably needs to be completely rewritten at some point ;-D).

**Comment by ggwpez** [comment]
Thanks for spotting it!  
The old syntax was in the form of:  
```rust
add_benchmark!(params, batches, frame_benchmarking, BaselineBench::<Runtime>);
add_benchmark!(params, batches, pallet_assets, Assets);
add_benchmark!(params, batches, pallet_babe, Babe);
…
```
and then in another function, one had to write the *same thing again* which is error prone:  
```rust
list_benchmark!(list, extra, frame_benchmarking, BaselineBench::<Runtime>);
list_benchmark!(list, extra, pallet_assets, Assets);
list_benchmark!(list, extra, pallet_babe, Babe);
…
```

these two got unified into `define_benchmarks!` which allows a developer to only write it once.  
```rust
define_benchmarks!(
	[frame_benchmarking, BaselineBench::<Runtime>]
	[pallet_assets, Assets]
	[pallet_babe, Babe]
	…
);
```
This can be seen [here](https://github.com/paritytech/substrate/blob/ef890f5598e0d3fd1b6a5fcc8c3322f7570089d1/bin/node/runtime/src/lib.rs#L1694) (and following lines). The old syntax is still valid and it is possible to mix the old and new syntax, but I would suggest to only mention the new one.  
The developer now only has to add the new benchmark to the `define_benchmarks!` macro invocation.  
In case an alias is needed, they still need to be defined twice eg. [here](https://github.com/paritytech/substrate/blob/ef890f5598e0d3fd1b6a5fcc8c3322f7570089d1/bin/node/runtime/src/lib.rs#L2072) and [here](https://github.com/paritytech/substrate/blob/ef890f5598e0d3fd1b6a5fcc8c3322f7570089d1/bin/node/runtime/src/lib.rs#L2095).  

Looks like [this](https://docs.substrate.io/main-docs/test/benchmark/) article also mentions the old syntax.
