### ISSUE TITLE
Update the HRMP channel guide

### ISSUE THREAD

**Issue by gluneau** [substrate-developer-hub/substrate-docs#1389]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Content request

The existing guide needs an update and a proper place in the nav.

https://docs.substrate.io/reference/how-to-guides/parachains/add-hrmp-channels/

Please inform me when done and I will link to it from Acala's wiki guide to onboard parachains.

### Are you willing to help with this request?

Yes!

**Comment by NukeManDan** [comment]
@gluneau can you link to where you intend to use this content and give some context about what you need it for here?

**Comment by lisa-parity** [comment]
@gluneau, can you take a look at https://docs.substrate.io/tutorials/connect-relay-and-parachains/open-message-passing-channels/ and see if that works for you?
