### ISSUE TITLE
Update to Polkadot v0.9.27

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-docs#1390]
This can be done throughout the docs, as there was issues with the Contracts Node in 26 that should be resolved as per [release notes](https://github.com/paritytech/polkadot/releases/tag/untagged-4e7f91848addc26067ac)

Tracking issues for other materials:
- https://github.com/paritytech/frontier/pull/809 for EVM (tested to work as-is! but fragile, as deps point to `master`, not the correct release branch yet as of 2022-08-12) 
- https://github.com/paritytech/cumulus/issues/1512 for parachains (this is not blocking)

**Comment by lisa-parity** [comment]
Please don't do this as a global operation.
I really would like back my `latest` or a replacement `stable` tag to allow the node template cloned from the developer-hub to lag and allow instructions to always be verified (so a tag can remain at the version that's been tested).

**Comment by NukeManDan** [comment]
This is a know stable working version. Oly outstanding unknows are listed.
