### ISSUE TITLE
[Rust docs/SE] Broken Link

### ISSUE THREAD

**Issue by gautamdhameja** [substrate-developer-hub/substrate-docs#1395]
https://docs.substrate.io/rustdocs/latest/sc_rpc_api/offchain/trait.OffchainApi.html

**Comment by NukeManDan** [comment]
Latest has been deprecated, we use master only , and only the github docs directly throughout now. Anything mussing that is an error in the docs here. Where did you discover thus link?

Should be in here now https://paritytech.github.io/substrate/master/sc_rpc_api/offchain/index.html

**Comment by gautamdhameja** [comment]
I discovered it here - https://substrate.stackexchange.com/questions/1320/how-to-extend-a-custom-rpc-service-to-query-the-off-chain-storage

**Comment by NukeManDan** [comment]
Thanks for the report here, I will update that post. 

Please do us a great favor moving forward & update the SE when you spot things like this, anyone can `edit`  a post and help get links updated. AFAIK there are no plans to try and update all links in our ecosystem with #1132 in place, and many existing links need to be updated by the authors and community of such content.
