### ISSUE TITLE
Old links appear in search results

### ISSUE THREAD

**Issue by cmichi** [substrate-developer-hub/substrate-docs#1426]
If I search the documentation for "smart contract" I have old search results appear:

![screenshot-docs substrate io-2022 08 17-08_59_18](https://user-images.githubusercontent.com/241530/185056208-b7b0561b-c9d0-4eda-8d8d-e74f8ae0fec4.png)

Notice the duplicate search results for "Develop A Smart Contract". One link works, the other is https://docs.substrate.io/tutorials/smart-contracts/develop-contract and leads to a 404.

**Comment by jonnysmillie** [comment]
Thank you for bringing this to my attention @cmichi.

I will look into it and hopefully fix quickly :)

**Comment by jonnysmillie** [comment]
I believe this was related to the search index being cached on our server.

I have cleared the cache and redeployed the site and all seems to work as expected now (at least for the specific case reported!)
