### ISSUE TITLE
Missing Commands (Content)

### ISSUE THREAD

**Issue by carinaluise** [substrate-developer-hub/substrate-docs#1445]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Content request

Missing commands on the following page (Currently empty tables ):
https://docs.substrate.io/reference/command-line-tools/archive/

Example:
<img width="982" alt="Screenshot 2022-08-18 at 11 01 30" src="https://user-images.githubusercontent.com/60577717/185358718-5eb16549-9ff2-4c9c-84ec-e80b3f9deac4.png">

**Comment by lisa-parity** [comment]
@carinaluise, thank for reporting this issue. The placeholder content has been removed but this section needs a lot more work to be functionally helpful. We'll try to get something more useful up soon.
