### ISSUE TITLE
Check if `pallet-contracts` tutorial is still working

### ISSUE THREAD

**Issue by cmichi** [substrate-developer-hub/substrate-docs#1450]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Content request

The user on https://substrate.stackexchange.com/questions/3668/errore0405-cannot-find-trait-trait-in-crate-pallet-contracts writes:

> I am performing the (add the contracts pallet to a runtime) substrate tutorial and I am getting this error
> 
> error[E0405]: cannot find trait Trait in crate pallet_contracts --> runtime/src/lib.rs:279:24 | 279 | impl pallet_contracts::Trait for Runtime { | ^^^^^ not found in pallet_contracts
> 
> can anyone tell me what should I do to solve this error

It could be that the tutorial is outdated, we should check.

### Are you willing to help with this request?

Yes!

**Comment by abdbee** [comment]
The [tutorial](https://docs.substrate.io/reference/how-to-guides/pallet-design/add-contracts-pallet/) in the docs works fine. 

It's possible that the user followed an older tutorial that's not in the docs ( that still uses the `Trait` naming, and still contains some types that are now obsolete).

**Comment by MohammadAbuzar945** [comment]
Dear cmichi , 
Tutorial for me is working fine.Tutorials are updated now please try again .

**Comment by cmichi** [comment]
That's great to hear, thank you both!
