### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by donkey-donkey** [substrate-developer-hub/substrate-docs#1475]
Origin page
https://substrate.recipes/basic-pow.html

link [pre-runtime digests](https://substrate.dev/rustdocs/v3.0.0/sp_runtime/generic/enum.DigestItem.html#variant.PreRuntime)

**Comment by NukeManDan** [comment]
Here is the source of that doc: https://github.com/JoshOrndorff/recipes/blob/master/text/basic-pow.md

I bet Joshy would really appreciate a scan & update of relevant links @donkey-donkey :grinning:  

We can't update the whole universe, it would be epic to get all hand on deck to help update things all over :pray:
