### ISSUE TITLE
Documentation has a Broken Link

### ISSUE THREAD

**Issue by soumil1** [substrate-developer-hub/substrate-docs#1483]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Content request

The link at substrate documentation at line: You have configured your environment for Substrate development by installing "Rust and the Rust toolchain" is broken.
![Screenshot (383)](https://user-images.githubusercontent.com/73458948/186893092-dddfeccb-fa39-473f-9de7-61dd4fe6d37e.png)

### Are you willing to help with this request?

Yes!

**Comment by lisa-parity** [comment]
@soumil1 good catch, thanks!
