### ISSUE TITLE
contracts-pallet: pallet-contracts-rpc error

### ISSUE THREAD

**Issue by MehranMazhar** [substrate-developer-hub/substrate-docs#1499]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [x] This is not a support question.

### Bug report for compiling, code snippets, templates, etc.

In this [contracts-pallet](https://docs.substrate.io/tutorials/work-with-pallets/contracts-pallet/) section "Update the outer node" after adding add the Contracts and Contracts RPC crates :
**pallet-contracts-rpc = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.26" }**
runtime compiles  get error :
![image](https://user-images.githubusercontent.com/11898578/188119942-42d81136-2dfc-4b58-83b4-242e6f9c2048.png)

### Steps to reproduce the problem

I act according to the order given in the tutorial.

**Comment by lisa-parity** [comment]
@MehranMazhar Can you try using a more recent branch? I think there was a bug related to contracts in polkadot-v0.9.26 but the tutorial was inadvertently updated to reference that branch.

**Comment by lisa-parity** [comment]
I think this is fixed by using v0.9.28. Updated doc to change the reference.
