### ISSUE TITLE
[docs] Add XCM / XCMP article 

### ISSUE THREAD

**Issue by sacha-l** [substrate-developer-hub/substrate-docs#150]
Add an article for parachain builders. Work in progress.

**Comment by NukeManDan** [comment]
Add info on using public good parachains. 
Tracking:
- [ ] https://github.com/paritytech/cumulus/issues/908

**Comment by bernardoaraujor** [comment]
any estimations on when will this be available?

**Comment by sacha-l** [comment]
I think the best we can do is have a page that explains basic XCM principles and how to use them, and link to all other current resources on XCM. For more advanced things, we could maintain a Q&A list - what do you think @NukeManDan @shawntabrizi ?

**Comment by NukeManDan** [comment]
stub is included in #1140 , still at this time not in a place I would consider user facing

**Comment by bernardoaraujor** [comment]
this [Audit Report on XCMv2](https://blog.quarkslab.com/resources/2022-02-27-xcmv2-audit/21-12-908-REP.pdf) could be a really good reference for XCM documentation.
