### ISSUE TITLE
Session Key Info is Wrong

### ISSUE THREAD

**Issue by joepetrowski** [substrate-developer-hub/substrate-docs#1506]
https://docs.substrate.io/fundamentals/accounts-addresses-keys/#specialized-accounts

Most of this is incorrect. For starters, there are no "session accounts".

> The session account represents the public/private key pair used by validators to sign consensus-related messages. The session account is not intended to control funds. These keys are also defined generically in the [Session pallet](https://paritytech.github.io/substrate/master/pallet_session/index.html) and made concrete in the runtime. To create the session account key pair, you must attest that the account acts on behalf of your stash account and nominators by signing a transaction with your controller key and publishing the session certificate on the chain. You can generate and register new session keys on chain using a [session.setKeys](https://paritytech.github.io/substrate/master/pallet_session/pallet/struct.Pallet.html#method.set_keys) transaction. You can change session keys using the [author_rotateKeys](https://paritytech.github.io/substrate/master/sc_rpc/author/trait.AuthorApiClient.html#tymethod.rotate_keys) RPC call.

**Comment by lisa-parity** [comment]
@joepetrowski, thanks for pointing this out. The information came from an older article about session keys. I think I've heard that controller keys/accounts were being phased out.
Should that whole Specialized accounts section just be deleted as too Polkadot-specific?

**Comment by joepetrowski** [comment]
Which older article? The last article I knew about them was [this one](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/503/files) from 2020.

We have discussed substituting stash/controller for another proxy type, but I'd leave that out; I don't know of any concrete plans. I logged this issue specifically about the session key info.

> The session account

There is no account. The PR above points this out explicitly. The entire purpose of the `set_keys` transaction is to _connect_ the session **keys** with an account.

> represents the public/private key pair

Can just be "Session keys are a set of private keys used by nodes to sign consensus-related messages." (I would even consider removing "consensus-related" since you could argue that not all messages are consensus-related, but generally the messages relate to consensus or consensus-related roles, like collation.)

> The session account is not intended to control funds.

"Session keys are not intended to control funds." (How can an account control funds?)

> To create the session account key pair, you must attest ...

Huh? How does attesting _create_ a key? 

> by signing a transaction with your controller key and publishing the session certificate on the chain.

The transaction is, in effect, the certificate. It's a signed message from one key (representing a controller account) with a payload of other public keys that says, "these keys sign messages from my node."

> You can generate and register new session keys on chain using a `session.setKeys` transaction.

How does making a transaction generate keys? It only registers them, you need to generate them by telling your node to generate new keys (or you can generate them how you like and inject them to the node).

> You can change session keys using the `author_rotateKeys` RPC call.

This just generates new keys in a node. They won't actually be used until you do a `set_keys` transaction to tell the chain that your node is now using these new keys.

**Comment by lsgunnlsgunn** [comment]
There was a somewhat different article from 2021, but I am pretty sure I'm the one who butchered the reference to session accounts instead of session keys in an (probably misguided) attempt to standardize the language around references to accounts and key pairs. I'll take a stab at cleaning this up but always appreciate your help in getting the info right. Hope it's okay for me to tag you to take a look at the revision.

**Comment by joepetrowski** [comment]
>  session accounts instead of session keys in an (probably misguided) attempt to standardize the language around references to accounts and key pairs.

But why? These are completely different concepts. It's like trying to standardize the language around locks and doors. Locks can be used for lots of different things (doors, bikes, safes, luggage, etc.) and doors can have many ways to secure them (locks, security cameras, alarms). Just because people happen to put locks on some doors doesn't mean that doors are locks.

> Hope it's okay for me to tag you to take a look at the revision.

Yes, no problem.
