### ISSUE TITLE
Smoldot crashes with the versions of the api and rpc-provider

### ISSUE THREAD

**Issue by lana-shanghai** [substrate-developer-hub/substrate-docs#1516]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Bug report for compiling, code snippets, templates, etc.

<img width="1307" alt="Screenshot 2022-09-14 at 09 36 39" src="https://user-images.githubusercontent.com/31368580/190094113-2a8e0002-0776-49da-8513-0744c833d4bd.png">

### Steps to reproduce the problem

Followed the light client tutorial: https://docs.substrate.io/tutorials/integrate-with-tools/integrate-a-light-client-node/

**Comment by lisa-parity** [comment]
@wirednkod, the tutorial and instructions worked previously but now appear to be broken. I hit this problem too.
Can you take a look?

**Comment by wirednkod** [comment]
This is probably resolved with the latest version of Substrate connect (v.0.6.32) released yesterday. I will have a look.

**Comment by wirednkod** [comment]
@lisa-parity I just run the documentation as provided from the link given. Steps of installing the `@polkadot/rpc-provider` and `@polkadot/api`,installed versions `9.3.3` for both, and tutorial works fine (smoldot version 0.6.30) with the use or not of the extension. In the image of @lana-shanghai I can see that smodlot 0.6.25 was used. Make sure that latest rpc-provider is used.

See below:
![image](https://user-images.githubusercontent.com/5408605/190575375-9ddf8da0-b639-4671-871f-df3256d74e96.png)
 
 I'll close this bug for now. Please reopen in case this is not resolved
