### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by oct-sheldon** [substrate-developer-hub/substrate-docs#1517]
https://www.google.com/url?sa=t&source=web&rct=j&url=https://docs.substrate.io/rustdocs/latest/sp_consensus_babe/struct.Epoch.html&ved=2ahUKEwjZ78LY1ZX6AhVB04UKHYfaCmkQFnoECAgQAQ&usg=AOvVaw2ElypHDyONFTMKh5_3YoJb

**Comment by lisa-parity** [comment]
Hi @oct-sheldon 
We've removed the intermediary linkk to rustdocs. You can find what you are looking for here:
https://paritytech.github.io/substrate/master/sp_consensus_babe/struct.Epoch.html

Can you let me know what page had the link? Maybe it was a browser cache issue?

**Comment by oct-sheldon** [comment]
It was a Google search for "epoch Substrate" but not with quotes. Apologies
for being vague in the submission field and thanks for maintaining this so
actively 🔥


Sheldon Dearr
Technical Lead
Infrastructure Security Solutions Engineer

***@***.***
t.me/ArtimusLeton
***@***.***/Sheldon#4184/
