### ISSUE TITLE
Why are `SignedExtension` part of the extrinsics doc?

### ISSUE THREAD

**Issue by bkchr** [substrate-developer-hub/substrate-docs#156]
Mainly what the title says. IMO they don't fit there.

https://docs.substrate.io/v3/concepts/extrinsics

**Comment by sacha-l** [comment]
True. Perhaps more fitting [here](https://docs.substrate.io/v3/concepts/tx-pool). WDYT?

**Comment by bkchr** [comment]
I would move it somewhere to FRAME. As it is a FRAME "concept"
