### ISSUE TITLE
There are kitties in my mint function

### ISSUE THREAD

**Issue by Arjentix** [substrate-developer-hub/substrate-docs#1562]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Bug report for compiling, code snippets, templates, etc.

I was reading [this](https://docs.substrate.io/reference/how-to-guides/basics/mint-basic-tokens/#create-the-mint-function) topic and found out that `mint` function contains 

```rust
 ensure!(Self::kitties(&kitty_id) == None, <Error<T>>::KittyExists);
```

without any context.

Looks like it's a copy-paste from another tutorial or reference

### Steps to reproduce the problem

Go to [Create the mint function](https://docs.substrate.io/reference/how-to-guides/basics/mint-basic-tokens/#create-the-mint-function)

**Comment by lisa-parity** [comment]
@sacha-l , do you know if this line can just be removed? I was tempted to just delete it because it seems out of context and I don't think there's a need for this check, but I haven't tested this guide myself so I figured it best to tag you.

**Comment by sacha-l** [comment]
Fixed! Those kitties have no right being in there 👍🏻 - thanks for flagging @Arjentix
