### ISSUE TITLE
Update Needed to Weight / Fee Documentation

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/substrate-docs#1576]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Content request

As noted in this StackExchange question:

https://substrate.stackexchange.com/questions/5223/tx-weights-fees-documentation-clarity

There needs to be some updates to the code which implements the appropriate traits for the transaction fees pallet.

### Are you willing to help with this request?

Maybe (please elaborate above)

**Comment by lisa-parity** [comment]
@shawntabrizi, the stack exchange question seems to have been removed. Is this about storage added as another dimension to weight  or the OnChargeTransaction trait or something else?
https://paritytech.github.io/substrate/master/pallet_transaction_payment/trait.OnChargeTransaction.html

**Comment by shawntabrizi** [comment]
Here is the deleted text:

<img width="746" alt="image" src="https://user-images.githubusercontent.com/1860335/197317868-9ad04901-b34d-4a71-b800-eb8e91264274.png">


basically i think the traits need to be updated
