### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by mohsin16432** [substrate-developer-hub/substrate-docs#1597]
https://docs.substrate.io/tutorials/connect-other-chains/local-relay/

**Comment by lisa-parity** [comment]
@mohsin16432, the paths to these tutorials changed a little. You can find them here:

https://docs.substrate.io/tutorials/connect-relay-and-parachains/prepare-a-local-relay-chain/
https://docs.substrate.io/tutorials/connect-relay-and-parachains/connect-a-local-parachain/
https://docs.substrate.io/tutorials/connect-relay-and-parachains/acquire-a-testnet-slot/
