### ISSUE TITLE
Tutorial for unit testing a pallet

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/substrate-docs#160]
This topic was previously covered well in devhub both in the [cryptokitties tutorial]() and in the [RC5 and earlier recipes](https://github.com/substrate-developer-hub/recipes/blob/v2.0.0-rc5/text/3-entrees/testing/index.md). Now that content should be moved into a tutorial.

**Comment by NukeManDan** [comment]
https://docs.substrate.io/main-docs/test/
