### ISSUE TITLE
Upgrade Chain Tutorial Should Link to Update Polkadot JS Types

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/substrate-docs#161]
This tutorial: https://substrate.dev/docs/en/tutorials/upgrade-a-chain/sudo-upgrade

Uses Node Template + Polkadot JS

But doesnt ask the user to update their types, thus they run into this error: https://polkadot.js.org/docs/api/FAQ/#the-node-returns-a-could-not-convert-error-on-send

**Comment by NukeManDan** [comment]
If I understand correctly, https://github.com/paritytech/substrate/pull/8615 changes the game here, so we can safely use the node template from [this point](https://github.com/paritytech/substrate/commit/ba153b9ae050eda022f002d74d76f98d1e339a81#diff-94f95fa9191f41684544453d491ef66a46e1fe1cf68a2c8893e6b5fd9ef5d3d2) on. It that includes `scale-info` to expose metadata with the apps UI (and soon to be updated FE template too). So we should support this with the next monthly release (`monthly-2021-10`)

**Comment by NukeManDan** [comment]
AFAIK this issue is no longer relevant, Please do reopen if incorrect!
