### ISSUE TITLE
Document RPC Calls

### ISSUE THREAD

**Issue by danforbes** [substrate-developer-hub/substrate-docs#162]
Migrating https://github.com/substrate-developer-hub/knowledgebase/issues/56

Related:
https://github.com/w3f/PSPs/pull/6
https://github.com/w3f/polkadot-spec/issues/306

**Comment by sacha-l** [comment]
@NukeManDan [this article](https://github.com/substrate-developer-hub/substrate-docs/blob/main/v3/docs/03-runtime/o-custom-rpcs/index.mdx) closes this issue I believe. Hi @danforbes btw 😁

**Comment by NukeManDan** [comment]
I think we are missing a HTG that covers https://substrate.dev/recipes/custom-rpc.html that should be linked in that article, unless I am straight missing that :sweat_smile: 

As readers will want to know how to implement RPCs that are exposed and you can talk to like the article already outlines. An example of the E2E development and use would be best IMHO.

**Comment by NukeManDan** [comment]
I this issue still relevant @sacha-l ? if not please close - or open a new one to refresh on what needs to be done in the new docs :pray:
