### ISSUE TITLE
Tutorial of data migration

### ISSUE THREAD

**Issue by h4x3rotab** [substrate-developer-hub/substrate-docs#163]
We found there's a page about Substrate data migration:

- <https://docs.substrate.io/build/upgrade-the-runtime/#storage-migration>
- <https://github.com/apopiak/substrate-migrations>
- <https://hackmd.io/@apopiak/Hyhroh0Xv/edit>

However it's more like an introduction, with a bunch of example PR and some caveats, but not a tutorial. Specifically, it would be helpful for readers if we can have:

- A step-to-step instructions for how to write a migration, and tear down the related code after finished (the later point is especially useful because it's not mentioned in any of the above docs)
- As said in the [migration guide](https://hackmd.io/BQt-gvEdT66Kbw0j5ySlWw#2-Writing-the-Migration), new migration should support pallet semantic versioning. How can we leverage it?
- The lifecycle of a migration (what will happen once we start a runtime upgrade, etc)
- Any performance consideration? (Looks like a migration can be much heavier than a regular block and 6s is not a limitation?)
- Reference of the related traits

Background: We are trying to migrating a StorageMap to a Child Tire

- https://github.com/Phala-Network/phala-blockchain/issues/107

**Comment by kianenigma** [comment]
We should also cover multi-block migrations, such as: https://substrate.stackexchange.com/questions/5852/how-do-i-do-a-mult-block-migration

**Comment by brunopgalvao** [comment]
Adding this here as it seems to no longer be on the docs site:
- https://github.com/substrate-developer-hub/substrate-docs/tree/bg/polkadot-v0.9.24/v3/how-to-guides/06-storage-migrations
