### ISSUE TITLE
Dynamic Weights Docs Use Out-of-Date Syntax

### ISSUE THREAD

**Issue by danforbes** [substrate-developer-hub/substrate-docs#164]
The usage of `FunctionOf` here is out-of-date https://substrate.dev/docs/en/knowledgebase/runtime/fees#dynamic-weights. Although it does not appear anything else on this page is out-of-date, the entire page should be reviewed as a part of addressing this bug.

**Comment by danforbes** [comment]
@doutv where are you seeing docs that reference `FunctionOf`? I don't see it referenced on [the docs for custom weights in Substrate](https://docs.substrate.io/reference/how-to-guides/weights/use-custom-weights/). Have you reviewed those docs?

**Comment by doutv** [comment]
@danforbes  https://docs.substrate.io/build/tx-weights-fees/#default-weight-annotations

![image](https://github.com/substrate-developer-hub/substrate-docs/assets/20609724/35b819c2-094c-4a43-9aba-73e4996751c5)

**Comment by danforbes** [comment]
Yep, I see. I'm not part of this org anymore so I'm not sure what the plans for the documentation are but maybe @NukeManDan can chime in. In any case, @doutv - do you need any help with custom weights in Substrate?

**Comment by doutv** [comment]
Thanks for your reply! I dont need help.
I want to fix the doc so that others will not stuck in the same issue.

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by danforbes** [comment]
If you go to the page, you will notice a link to edit it:
![image](https://github.com/substrate-developer-hub/substrate-docs/assets/2193247/a1993924-0dad-4f4a-8434-ee9755670873)


Clicking that link will take you to the relevant [source document](https://github.com/substrate-developer-hub/substrate-docs/blob/main/content/md/en/docs/build/tx-weights-fees.md) that is used to render that webpage. You can fork that repository, make the changes that you think need to be made to the source document, and open a Pull Request 👍🏻

**Comment by doutv** [comment]
Thanks for your guide. 

However, I don't know the right method to create a dynamic weight pallet call function in current substrate version. 

@Rashmirreddy Could you can update the doc and fix this issue if you can?

**Comment by Rashmirreddy** [comment]
We are currently working on updating our documentation, and this will be addressed as part of the update.
