### ISSUE TITLE
Broken link RPC documentation

### ISSUE THREAD

**Issue by viac92** [substrate-developer-hub/substrate-docs#1645]
### Broken Link

https://paritytech.github.io/substrate/master/sc_service/trait.RpcExtensionBuilder.html

### Context and Origin

The issue is fixable at this line https://github.com/substrate-developer-hub/substrate-docs/blob/6863630dc455db05f741ce9cbb2e7fec3681da6e/content/md/en/docs/build/custom-rpc.md?plain=1#L19

**Comment by lisa-parity** [comment]
Quite possible.
https://docs.substrate.io/build/remote-procedure-calls/
Thanks for checking!
