### ISSUE TITLE
https://substrate.dev/rustdocs/v3.0.0/frame_support/traits/trait.Currency.htmlBroken Link

### ISSUE THREAD

**Issue by Retamogordo** [substrate-developer-hub/substrate-docs#1664]
This link is referred in
https://substrate.recipes/crowdfund.html

**Comment by lisa-parity** [comment]
That site and associated repo aren't being actively maintained.
Closest thing I could find was this:
https://paritytech.github.io/substrate/master/frame_support/traits/tokens/currency/trait.Currency.html

In any case, all Rust docs now use the same location not user the rustdocs intermediary.
