### ISSUE TITLE
Error when including pallet-contracts to the runtime

### ISSUE THREAD

**Issue by jjean92** [substrate-developer-hub/substrate-docs#1667]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Bug report for compiling, code snippets, templates, etc.

cargo check -p node-template-runtime --release
error: failed to load manifest for workspace member `/home/patriste/Documents/Substrate/substrate-node-template/node`

Caused by:
  failed to load manifest for dependency `node-template-runtime`

Caused by:
  failed to parse manifest at `/home/patriste/Documents/Substrate/substrate-node-template/runtime/Cargo.toml`

Caused by:
  feature `std` includes `pallet-contracts`, but `pallet-contracts` is not an optional dependency
  A non-optional dependency of the same name is defined; consider adding `optional = true` to its definition.

When I include "optional = true" in dependencies definition I have the following error message : 
cargo check -p node-template-runtime --release
    Checking sp-sandbox v0.10.0-dev (https://github.com/paritytech/substrate.git?branch=polkadot-v0.9.32#5ea6d953)
   Compiling pallet-contracts-proc-macro v4.0.0-dev (https://github.com/paritytech/substrate.git?branch=polkadot-v0.9.32#5ea6d953)
error[E0425]: cannot find function `memory_teardown` in module `sandbox`
  --> /home/patriste/.cargo/git/checkouts/substrate-7e08433d4c370a21/5ea6d95/primitives/sandbox/src/host_executor.rs:58:12
   |
58 |         sandbox::memory_teardown(self.memory_idx);
   |                  ^^^^^^^^^^^^^^^ not found in `sandbox`

error[E0425]: cannot find function `memory_new` in module `sandbox`
  --> /home/patriste/.cargo/git/checkouts/substrate-7e08433d4c370a21/5ea6d95/primitives/sandbox/src/host_executor.rs:74:18
   |
74 |         match sandbox::memory_new(initial, maximum) {
   |                        ^^^^^^^^^^ not found in `sandbox`

error[E0425]: cannot find function `memory_get` in module `sandbox`
  --> /home/patriste/.cargo/git/checkouts/substrate-7e08433d4c370a21/5ea6d95/primitives/sandbox/src/host_executor.rs:82:13
   |
82 |             sandbox::memory_get(self.handle.memory_idx, offset, buf.as_mut_ptr(), buf.len() as u32);
   |                      ^^^^^^^^^^ not found in `sandbox`

error[E0425]: cannot find function `memory_set` in module `sandbox`
  --> /home/patriste/.cargo/git/checkouts/substrate-7e08433d4c370a21/5ea6d95/primitives/sandbox/src/host_executor.rs:91:25
   |
91 |         let result = sandbox::memory_set(
   |                               ^^^^^^^^^^ not found in `sandbox`

error[E0425]: cannot find function `instantiate` in module `sandbox`
   --> /home/patriste/.cargo/git/checkouts/substrate-7e08433d4c370a21/5ea6d95/primitives/sandbox/src/host_executor.rs:219:25
    |
219 |         let result = sandbox::instantiate(
    |                               ^^^^^^^^^^^ not found in `sandbox`

error[E0425]: cannot find function `invoke` in module `sandbox`
   --> /home/patriste/.cargo/git/checkouts/substrate-7e08433d4c370a21/5ea6d95/primitives/sandbox/src/host_executor.rs:245:25
    |
245 |         let result = sandbox::invoke(
    |                               ^^^^^^ not found in `sandbox`

error[E0425]: cannot find function `get_global_val` in module `sandbox`
   --> /home/patriste/.cargo/git/checkouts/substrate-7e08433d4c370a21/5ea6d95/primitives/sandbox/src/host_executor.rs:266:12
    |
266 |         sandbox::get_global_val(self.instance_idx, name)
    |                  ^^^^^^^^^^^^^^ not found in `sandbox`

error[E0425]: cannot find function `instance_teardown` in module `sandbox`
   --> /home/patriste/.cargo/git/checkouts/substrate-7e08433d4c370a21/5ea6d95/primitives/sandbox/src/host_executor.rs:272:12
    |
272 |         sandbox::instance_teardown(self.instance_idx);
    |                  ^^^^^^^^^^^^^^^^^ not found in `sandbox`

For more information about this error, try `rustc --explain E0425`.

### Steps to reproduce the problem

Follow the tutorial https://docs.substrate.io/tutorials/work-with-pallets/contracts-pallet/ and error happen when checking runtime 

cargo check -p node-template-runtime --release

Environment : 

- Debian OS :
Linux version 5.10.0-19-amd64 ([debian-kernel@lists.debian.org](mailto:debian-kernel@lists.debian.org)) (gcc-10 (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) https://github.com/substrate-developer-hub/substrate-docs/issues/1 SMP Debian 5.10.149-2 (2022-10-21);
- Rust version :
rustc 1.65.0;
- Node template :
4.0.0-dev (information taken from the "runtime/Cargo.toml" file; is there a command line to check the node template version?

**Comment by lisa-parity** [comment]
@jjean92 In the runtime/Cargo.toml, the dependencies identify a version and a branch. For example:

```
pallet-timestamp = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", " branch" = "polkadot-v0.9.35" }
```

A recent branch seems like it might have broken several tutorials. What do the dependencies look like in your project?

(There have also been changes to the contracts pallets, so we are trying to track down the root cause so we can fix/update the tutorials accordingly.)

**Comment by jjean92** [comment]
the branch version I'm using is polkadot-v0.9.32

**Comment by har00ga** [comment]
These crates have been removed (see: https://substrate.stackexchange.com/questions/6375/error-no-matching-package-named-pallet-contracts-rpc-found). Updating the documentation to reflect this.

**Comment by lisa-parity** [comment]
Initially, the error seemed to be caused by a problem in the manifest files.
https://github.com/substrate-developer-hub/substrate-node-template/pull/407
However, after fixing those problems, we discovered major compatibility issues between the pallets required to add the pallets required for smart contracts and the current version of the node template.
 
If you want to experiment with smart contract development for your blockchain, you should use the preconfigured [substrate-contracts-node](https://github.com/paritytech/substrate-contracts-node) instead of the standard node template.

To resolve these compatibility issues would require extensive changes to the configuration of the standard node template, including using older versions of all crates and modifying multiple files. 
To dive directly into smart contract development, see the tutorials in [Develop smart contracts](/tutorials/smart-contracts/).
