### ISSUE TITLE
How to get nodes to find each other on macOS

### ISSUE THREAD

**Issue by mrcnski** [substrate-developer-hub/substrate-docs#1679]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Content request

I'm wondering if we can add a note to this tutorial:

https://docs.substrate.io/tutorials/connect-relay-and-parachains/prepare-a-local-relay-chain/#relay-chain-specification

Saying if the nodes can't find each other on OSX, to try this SO answer:

https://substrate.stackexchange.com/a/2990/3350

This would have saved me a bunch of time. :)

### Are you willing to help with this request?

Yes!

**Comment by lisa-parity** [comment]
@m-cat, if you'd like to submit a PR with your suggestion, we'd love to improve the tutorial based on your feedback!

**Comment by m-cat** [comment]
@lisa-parity Will do!

**Comment by m-cat** [comment]
Hmm I'm having trouble building the docs. I was getting errors about `gatsby-plugin-substrate`, so I did all the steps at https://github.com/paritytech/gatsby-plugin-substrate#troubleshooting and now I see this:

```
 ERROR #98124  WEBPACK

Generating development SSR bundle failed

Can't resolve '../../../public/page-data/sq/d/167280315.json' in
'/Users/parity/Sync/Repos/github.com/substrate-developer-hub/substrate-docs/node_modules/gatsby-plugin-substrate/hooks'

If you're trying to use a package make sure that '../../../public/page-data/sq/d/167280315.json' is installed. If you're
 trying to use a local file make sure that the path is correct.

File: node_modules/gatsby-plugin-substrate/hooks/use-site-metadata.js:1:0

not finished Building development bundle - 3.879s
not finished Caching HTML renderer compilation - 0.017s
```

**Comment by lsgunnlsgunn** [comment]
This isn't a great answer but sometimes reinstalling yarn cleans up the environment. 
yarn clean
yarn install

**Comment by lsgunnlsgunn** [comment]
This isn't a great answer but sometimes reinstalling yarn cleans up the environment. 
yarn clean
yarn install

**Comment by m-cat** [comment]
I tried that, and also tried deleting the repo and starting over.

I will raise a new issue for this specifically.
