### ISSUE TITLE
Issue running `yarn develop`: Generating development SSR bundle failed

### ISSUE THREAD

**Issue by mrcnski** [substrate-developer-hub/substrate-docs#1688]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Bug report for compiling, code snippets, templates, etc.

```
 ERROR #98124  WEBPACK

Generating development SSR bundle failed

Can't resolve '../../../public/page-data/sq/d/167280315.json' in
'/Users/parity/Sync/Repos/github.com/substrate-developer-hub/substrate-docs/node_modules/gatsby-plugin-substrate/hooks'

If you're trying to use a package make sure that '../../../public/page-data/sq/d/167280315.json' is installed. If you're
 trying to use a local file make sure that the path is correct.

File: node_modules/gatsby-plugin-substrate/hooks/use-site-metadata.js:1:0

not finished Building development bundle - 3.879s
not finished Caching HTML renderer compilation - 0.017s
```

### Steps to reproduce the problem

I'm trying to follow these [install instructions](https://github.com/substrate-developer-hub/substrate-docs#install). When I run `yarn develop`, I see the above.

I tried the Troubleshooting steps linked to [here](https://github.com/paritytech/gatsby-plugin-substrate#troubleshooting). I also tried deleting the whole repo and starting over.

I'm running all the commands in the root directory. Maybe I need to run something in the `plugin/gatsby-plugin-substrate` submodule directory?

**Comment by brrr** [comment]
Configure environment variables

Copy example.env.development into a new .env.development file.

Config URL variables based on your preferable local setup. URL will be used for links generation between Substrate websites.

Default localhost port configuration:

GATSBY_WEBSITE_URL=http://localhost:8100
GATSBY_DOCS_URL=http://localhost:8200
GATSBY_MARKETPLACE_URL=http://localhost:8300
GATSBY_CAREERS_URL=https://careers.substrate.io


**reminder: uncomment lines in  .env.development**

**Comment by mrcnski** [comment]
Oh, I missed that! Thanks so much!
