### ISSUE TITLE
Document How to Maintain a Substrate-Based Chain

### ISSUE THREAD

**Issue by danforbes** [substrate-developer-hub/substrate-docs#169]
Provide better documentation regarding how to maintain the operational stability of a Substrate-based chain. Topics may include: launching and maintaining operators, sentries, bootnodes, RPC pools and more.

Ref: https://wiki.polkadot.network/docs/en/maintain-index

**Comment by NukeManDan** [comment]
Some references:
- Builders program devops office hour: 
  - video https://drive.google.com/file/d/1-nQ_SI2XK6vxPQvORWuv68Yj0UDz5FrO/view
  - notes: https://gist.github.com/lovelaced/cddc1c7234b883ee37e71cf4a1d63cac
- surface services to consider:
  - https://monk.io (SBP video... recording where?)
  - https://www.onfinality.io/

**Comment by lisa-parity** [comment]
Closing this original issue as it is buried in the queue and we do want to add this section to the new information architecture.
