### ISSUE TITLE
Configure the contracts pallet

### ISSUE THREAD

**Issue by magalliance** [substrate-developer-hub/substrate-docs#1702]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Content request

Not actual for branch polkadot-v0.9.31 and above. There are no pallet-contracts-runtime-api and pallet-contracts-rpc in dependencies. Need update tutorial https://docs.substrate.io/tutorials/work-with-pallets/contracts-pallet.

### Are you willing to help with this request?

Maybe (please elaborate above)

**Comment by har00ga** [comment]
These crates have been removed (see: https://substrate.stackexchange.com/questions/6375/error-no-matching-package-named-pallet-contracts-rpc-found). Updating the documentation to reflect this.
