### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by mohamedhabas11** [substrate-developer-hub/substrate-docs#1704]
https://docs.substrate.io/build/custom-rpc/

<img width="1662" alt="Screenshot 2023-01-03 at 16 31 32" src="https://user-images.githubusercontent.com/12120722/210377522-29271abe-5f91-4631-8b67-484a63587864.png">

**Comment by lisa-parity** [comment]
@mohamedhabas11, the name of that section changed. You can find the content here:
https://docs.substrate.io/build/remote-procedure-calls/
