### ISSUE TITLE
Add keep-blocks param with cli

### ISSUE THREAD

**Issue by zjb0807** [substrate-developer-hub/substrate-docs#1705]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Content request

Related: https://github.com/paritytech/substrate/pull/13068

The logic of `prune_blocks` has changed, and the `--keep-blocks=archive` needs to be specified.

### Are you willing to help with this request?

No.

**Comment by lisa-parity** [comment]
Seems like there's no updated needed for now.
