### ISSUE TITLE
Document Transaction Pool Logic

### ISSUE THREAD

**Issue by apopiak** [substrate-developer-hub/substrate-docs#171]
It would be useful to have an article e.g. in the knowledge base that explains the fundamental behavior of the transaction pool.
What's the life cycle of a transaction? Which transactions are propagated?

One thing included there would be that transactions that return an error [here in `validate_transaction`](https://github.com/paritytech/substrate/blob/171ad2322d7561934b82f0b7e41c58d1710f8c24/primitives/runtime/src/traits.rs#L777) are dropped and not propagated.

**Comment by sacha-l** [comment]
Updates here: https://github.com/substrate-developer-hub/docs-sandbox/pull/44

**Comment by lisa-parity** [comment]
https://docs.substrate.io/main-docs/fundamentals/transaction-lifecycle/
Closing this for now as we've added some info to the doc.
