### ISSUE TITLE
Improve "Add trusted nodes" tutorial to avoid confusion about identical generated keys for both nodes

### ISSUE THREAD

**Issue by gogosama-dev** [substrate-developer-hub/substrate-docs#1710]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Content request

Hello everyone. 

I was going through this tutorial:
https://docs.substrate.io/tutorials/get-started/add-trusted-nodes/
and had no complaint until the place where you look at generated keys for the nodes:
`ls /tmp/node01/chains/local_testnet/keystore`
Tutorial says it should display similar to the following:
```
617572611441ddcb22724420b87ee295c6d47c5adff0ce598c87d3c749b776ba9a647f04
6772616e1441ddcb22724420b87ee295c6d47c5adff0ce598c87d3c749b776ba9a647f04
```
So you can clearly see two IDENTICAL keys (disregard first 7 digits of both keys, they present Sr25519/EdSr25519 differential part I would imagine).
However if you follow the tutorial precisely (like I did), you will notice that you actually get two different keys generated.
My output:
```
617572617e016f19ab623ba5f487f540017c1edbab06c0b211a16d40531dbd62d94ceb24
6772616e4ac976937e53fd836512cfd288bb438584ba366cbf9be403a0acd82c1c7c0739
```

And similar for the second node.
TUTORIAL says you should get:
```
617572611a4cc824f6585859851f818e71ac63cf6fdc81018189809814677b2a4699cf45
6772616e1a4cc824f6585859851f818e71ac63cf6fdc81018189809814677b2a4699cf45
```
And what I've got is:
```
617572610a6cadb3d6f55a121de4c89754dd835e634ae83249734dfad01c2fae7e9ac102
6772616e5f273f61a4910897cec969b598a70a832fb7894ad7c741e2a559617898426f20
```

Did I do something wrong? Or have I potentially found some misleading information in the tutorial? 
Wouldn't necessarily call it "a bug", as nothing breaks, but seeing identical keys in the tutorial someone might expect the same in their  own set up, and wasting hours figuring out why his generated keys ain't identical.

What needs to be updated:
https://github.com/substrate-developer-hub/substrate-docs/blob/main/content/md/en/docs/tutorials/get-started/add-trusted-nodes.md
Lines 459, 460
Lines 546, 547

Shall we fix it? I can update with my locally generated keys as an example, if approved. 

### Are you willing to help with this request?

Yes!

**Comment by lisa-parity** [comment]
@gogosama-dev, great catch! I didn't notice that they were identical after the first 7 digits. 
Feel free to open a PR and fix the issue. 
Thanks again for helping to improve the tutorials.

**Comment by gogosama-dev** [comment]
> https://github.com/substrate-developer-hub/substrate-docs/blob/main/content/md/en/docs/tutorials/get-started/add-trusted-nodes.md

Thanks, Lisa!
I've submitted my PR:
https://github.com/substrate-developer-hub/substrate-docs/pull/1724
