### ISSUE TITLE
Does this page only provide the official tools?

### ISSUE THREAD

**Issue by AurevoirXavier** [substrate-developer-hub/substrate-docs#1738]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Content request

Does this page only provide the official tools?

### Are you willing to help with this request?

Yes!

**Comment by lisa-parity** [comment]
@AurevoirXavier which page are you referring to?
Do you mean this page:
https://docs.substrate.io/install/developer-tools/
or this page:
https://docs.substrate.io/reference/command-line-tools/

In general, the topics is Developer Hub talk about "official" tools (at least currently). 
However, you can also find additional respirces here:
https://github.com/substrate-developer-hub/awesome-substrate

**Comment by AurevoirXavier** [comment]
> @AurevoirXavier which page are you referring to? Do you mean this page: https://docs.substrate.io/install/developer-tools/ or this page: https://docs.substrate.io/reference/command-line-tools/
> 
> In general, the topics is Developer Hub talk about "official" tools (at least currently). However, you can also find additional respirces here: https://github.com/substrate-developer-hub/awesome-substrate

Shit, I forgot to put the link here.

Sorry, this one. https://docs.substrate.io/reference/command-line-tools/
