### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by kia9372** [substrate-developer-hub/substrate-docs#1744]
this link is broken . please fix it 

https://docs.substrate.io/tutorials/work-with-pallets/contracts-pallet/

**Comment by lsgunnlsgunn** [comment]
@kia9372 This tutorial has been removed from the documentation for the time being because of compatibility issues. Please use the substrate-contracts-node to work with smart contracts for now you can find a link to the repo for it on the https://docs.substrate.ui/tutorials/ page. HTH.
