### ISSUE TITLE
Missing Image in Consensus Page

### ISSUE THREAD

**Issue by Imod7** [substrate-developer-hub/substrate-docs#1756]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### What browsers are you seeing the problem on?

Firefox, Other (please write below)

### Bug report for the website

Image regarding the (GHOST) rule in the [Consensus](https://docs.substrate.io/fundamentals/consensus/) page is missing : 

![consensus-ghost](https://user-images.githubusercontent.com/12569221/214276295-045a812c-5572-4771-8ee5-8802b4ff77f2.png)

It looks like the link [GHOST rule](https://github.com/substrate-developer-hub/substrate-docs/blob/main/media/images/docs/consensus-ghost.png) points to an image named `consensus-ghost.png` but  I could not find it in the corresponding [folder](https://github.com/substrate-developer-hub/substrate-docs/tree/main/content/media/images/docs) (where I could find the other image that is also in the Consensus page, `consensus-longest-chain.png`).

### Some additional notes
- As a general note, I find very helpful the image explaining GHOST in this [article](https://medium.com/coinmonks/an-in-depth-look-at-the-ghost-protocol-part-2-how-ghost-works-50e49edf7a52) in case you would like to use it as an inspiration. 
- I also find helpful mentioning the term
   - “heaviest” chain -> more blocks -> GHOST (_vs longest chain_ term already mentioned)
  when explaining GHOST
     > _by choosing the branch that has the **most blocks** built on it recursively._

Please take into consideration that the above notes are strictly personal and I am just sharing here in case it is helpful. 
Thank you in advance!

**Comment by lisa-parity** [comment]
good catch and a great suggestion!
