### ISSUE TITLE
Add note on Runtime WASM compression

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-docs#176]
> One does not need to "enable compression" for a runtime.
> Wasm compression has been added to the substrate-wasm-builder on April 7th.
> Polkadot and Kusama (presently) use the wasm-builder v3.0.0 which was tagged Feb 10th (so no compression).

Compressed WASM is critical for parachains. We should note this in the KB (#1027) and possibly explain in some new content what all build artifacts substrate produces and why.

**Comment by lisa-parity** [comment]
https://docs.substrate.io/main-docs/build/build-process/
