### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by AlexD10S** [substrate-developer-hub/substrate-docs#1765]
I can not see the tutorial about how to add the contract pallets anymore: https://docs.substrate.io/tutorials/work-with-pallets/contracts-pallet/

**Comment by TorstenStueber** [comment]
I guess that this is related to this PR: https://github.com/substrate-developer-hub/substrate-docs/pull/1743

**Comment by lisa-parity** [comment]
Hi @AlexD10S, @TorstenStueber,
Yes, unfortunately there are compatibility issues between the current "vanilla" node-template and the contract-related pallets. However, there is a customized node template for contracts and there are tutorials here:
https://docs.substrate.io/tutorials/smart-contracts/

If you run into issues with these tutorials, please do file an issue.
Thanks!

> If you want to experiment with smart contract development for your blockchain, you should use the preconfigured [substrate-contracts-node](https://github.com/paritytech/substrate-contracts-node) instead of the standard node template. There are compatibility issues between the pallets that support smart contracts and the current node template. To resolve these compatibility issues would require extensive changes to the configuration of the standard node template, including using older versions of all crates and modifying multiple files. To dive directly into smart contract development, see the tutorials in [Develop smart contracts](https://docs.substrate.io/tutorials/smart-contracts/).
