### ISSUE TITLE
Update and add to Frontier content

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-docs#177]
https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/967 for reference on things required. 

- [ ] Point to published site for more info & rustdocs of `master` on frontier: https://paritytech.github.io/frontier/
- [ ] Explain how to use github deps for substrate correctly
- [ ] Explain "Wrapping Ethereum Transactions" section more formally, include examples/diagram as needed
- [ ] Update RPC&API details
- [ ] Be  completely tutorial style conformant
- [ ] Point to https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/1088 when ready
- [ ] ...

**Comment by lisa-parity** [comment]
Closing in favor of https://github.com/substrate-developer-hub/substrate-docs/pull/1240
