### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by jjmiranda** [substrate-developer-hub/substrate-docs#1777]
[ContractsApi](https://substrate.dev/rustdocs/latest/pallet_contracts_rpc_runtime_api/trait.ContractsApi.html)

**Comment by lisa-parity** [comment]
You can find the latest information here:
https://paritytech.github.io/substrate/master/pallet_contracts/trait.ContractsApi.html

You might also find this helpful:
https://paritytech.github.io/substrate/master/pallet_contracts/api_doc/index.html
