### ISSUE TITLE
New documentation for node template telemerty

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-docs#178]
Per https://github.com/substrate-developer-hub/substrate-node-template/pull/160 - there is a need to explain the new template telemetry additions, knowledge base and/or tutorial and/or recipe would be important. IMHO a tutorial on telemetry in general, coupling with the Node visualizations may be good?

**Comment by lisa-parity** [comment]
I think this is at least partially covered in the existing Monitor node metrics tutorial, command line, and RPC topics. 
I'm going to close this as deep in the queue in favor of more specific requests based on current state of the doc.
