### ISSUE TITLE
Missing image in crowdloan page

### ISSUE THREAD

**Issue by kianenigma** [substrate-developer-hub/substrate-docs#1784]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Bug report for the website

was answering https://substrate.stackexchange.com/questions/7097/how-we-can-apply-for-crowdloan-to-participate-in-the-auction/7104#7104, and realized https://docs.substrate.io/reference/how-to-guides/parachains/auctions-and-crowdloans/ which is a pretty important page has a bunch of images missing.

**Comment by lisa-parity** [comment]
Path needed to be updated.
