### ISSUE TITLE
Link for configuring of the contracts pallet leads to 404

### ISSUE THREAD

**Issue by mshankarrao** [substrate-developer-hub/substrate-docs#1792]
### Broken Link

In the page https://docs.substrate.io/tutorials/smart-contracts/, the link https://docs.substrate.io/tutorials/work-with-pallets/contracts-pallet/ leads to 404

### Expected Location

I am not exactly sure whether its there in the substrate doc, but it should leads the page where we are adding/configuring the contracts pallet to the standard node template 

### Context and Origin

i was going through all the documents in the substrate developer portal and found that there is this link broken

**Comment by wyhaines** [comment]
I actually fixed this yesterday. There are some other broken links in the docs, but they are all being fixed.

**Comment by lisa-parity** [comment]
@mshankarrao unfortunately, I had to retire that tutorial for adding contracts to the standard node template.
