### ISSUE TITLE
Broken link: Upgrade The Runtime

### ISSUE THREAD

**Issue by cmichi** [substrate-developer-hub/substrate-docs#1809]
### Broken Link

https://docs.substrate.io/build/upgrade-the-runtime/

### Context and Origin

We link to it from `ink-docs`, I can fix it there. But the broken link still shows up in the search:

<img width="729" alt="Bildschirm­foto 2023-02-13 um 14 54 06" src="https://user-images.githubusercontent.com/241530/218476468-b66b3585-1f16-49cc-ad9b-e0a2f7f8296e.png">

I guess you have to restart indexing.

**Comment by lisa-parity** [comment]
New location and file name:
https://docs.substrate.io/maintain/runtime-upgrades/
@jonnysmillie, is the indexing for search something you can trigger?

**Comment by lisa-parity** [comment]
Jonny has updated the index.
