### ISSUE TITLE
Revisit cryptography and identify any additional topics or changes

### ISSUE THREAD

**Issue by lisa-parity** [substrate-developer-hub/substrate-docs#1814]
Resource:
https://github.com/paritytech/polkadot-blockchain-academy/tree/main/syllabus/1-Cryptography
There are six separate submodules, so really need to boil it down to what might be helpful without drilling too deep.

**Comment by har00ga** [comment]
Can I get access to this repo @lisa-parity ? My last invite didn't work.

**Comment by har00ga** [comment]
https://github.com/Polkadot-Blockchain-Academy/pba-content/pull/580
