### ISSUE TITLE
Simulate a network tutorial 

### ISSUE THREAD

**Issue by flomang** [substrate-developer-hub/substrate-docs#1818]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Content request

This is slightly confusing near the end of the tutorial it says: 

"Because you started the nodes in development mode—with the --dev command-line option—all state is cleared for both nodes." 

However, there's no mention of a --dev flag in the command line arguments for starting the node. Both nodes for this tutorial are started with "--chain local". I'm guessing chain "local" and chain "dev" do the same thing and clear state after shutdown? If so, can we reword this or clarify? 

### Are you willing to help with this request?

Yes!

**Comment by lisa-parity** [comment]
@flomang great catch! that is a copy-and-paste mistake and shouldn't be there.
