### ISSUE TITLE
Randomness Collective Flip Pallet - Link broken

### ISSUE THREAD

**Issue by gitofdeepanshu** [substrate-developer-hub/substrate-docs#1827]
### Broken Link

In `Getting Randomness` section, there is  a link associated with `Randomness Collective Flip Pallet` which points to "https://paritytech.github.io/substrate/master/pallet_randomness_collective_flip/index.html" and is broken.

### Expected Location

Unsure

### Context and Origin

Here is the link of page where the broken link was found "https://docs.substrate.io/build/randomness/"

**Comment by Rashmirreddy** [comment]
This issue seems to have been fixed, hence closing.
