### ISSUE TITLE
New reference page for `key` sub-command (not subkey)

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-docs#184]
The `insert` sub-command info on the subkey page is commented out in substrate-developer-hub/substrate-developer-hub.github.io#992 , as it is not included anymore. This should be migrated to a new page dedicated to the `key` command, as it is now diverging from `subkey`.

- [ ] Add information about differences, and when to use which 
- [ ] `insert` sub-command migrated
- [ ] Add content that informs _why_ this BEEFY key format exists (see [PR for details](https://github.com/paritytech/substrate/pull/8674))

**Comment by lisa-parity** [comment]
Covered in the node-template CLI info
