### ISSUE TITLE
Migrate Prebuilt Pallets in FRAME -> Pallets?

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-docs#186]
https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/blob/source/docs/knowledgebase/runtime/frame.md

this lists a large selection of pallets substrate comes with. I would think it be better places in 
https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/blob/source/docs/knowledgebase/runtime/pallets.md I would also call it "official pallets" and add a section on known community ones (awesome substrate link?)

I would opt for pointing to the whole selection in source, but having these listed for seach-ability on devhub is great. 

This likely needs to be revisited every release or substrate and/or FRAME.

**Comment by sacha-l** [comment]
This is no longer relevant because of the changes already made. Good to close @NukeManDan ?

**Comment by NukeManDan** [comment]
https://github.com/substrate-developer-hub/substrate-docs/blob/develop/v3/docs/03-runtime/a-FRAME/index.mdx#prebuilt-pallets

so it looks like this page ^ consolidated the two referenced? If so, we are good!

https://github.com/substrate-developer-hub/substrate-docs/blob/c2de4714e67f83a013b1268364bdb752f61e26b4/v3/docs/02-concepts/a-runtime/index.mdx#frame-primitives

broken link left over to the old page ^^
