### ISSUE TITLE
Broken Link on how-to-guides

### ISSUE THREAD

**Issue by UVvirus** [substrate-developer-hub/substrate-docs#1879]
Off-chain transactions link is broken. please update it.
https://docs.substrate.io/reference/how-to-guides/offchain-workers/offchain-transactions/

**Comment by lisa-parity** [comment]
@UVvirus, this topic has been "promoted" to a full-fledged tutorial.

**Comment by UVvirus** [comment]
@lisa-parity Thank you for your quick response
