### ISSUE TITLE
Error in "Update your smart contract" section causes tests failure and misleads 

### ISSUE THREAD

**Issue by enriquenc** [substrate-developer-hub/substrate-docs#1914]
### Is there an existing issue?

- [x] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [x] This is not a support question.

### Bug report for compiling, code snippets, templates, etc.

Error on page Develop a smart contract - https://docs.substrate.io/tutorials/smart-contracts/develop-a-smart-contract/

The "Update your smart contract" section point 6 says:

            Check your work using the test subcommand:
            ```bash
            cargo test
            ```
            The command should display output similar to the following to indicate successful test completion:
            
            ```bash
            running 1 test
            test incrementer::tests::default_works ... ok
            
            test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
            ```

But we don't make appropriate changes to the tests and "get" function on this step, so tests will fail.
These changes are described in the next step "Add a function to get a storage value".

Resolution: remove step 6 from the "Update your smart contract" section, it causes test failure and misleads a little bit.

**Comment by lisa-parity** [comment]
@parityceleste can you check in with DevRel on whether they are picking this up?

**Comment by bencgreenberg** [comment]
In #1926 I update the tutorial to keep the tests failing at that juncture, but explain why they are failing as incremental steps in the learning process.

**Comment by har00ga** [comment]
@bencgreenberg Thanks :)
