### ISSUE TITLE
Broken Link "Why Substrate?"

### ISSUE THREAD

**Issue by tadeohepperle** [substrate-developer-hub/substrate-docs#1931]
Broken link in "Where to go next" section on [Blockchain Basics](https://docs.substrate.io/learn/blockchain-basics/).
Clicking on "Why Substrate?" leads to https://docs.substrate.io/learn/why-substrate/ which does not exist.

**Comment by lisa-parity** [comment]
Thanks, @tadeohepperle, I missed that link. The following topic incorporates the information that used to be in Why Substrate? topic:
https://docs.substrate.io/learn/welcome-to-substrate/
