### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by DeluxeRaph** [substrate-developer-hub/substrate-docs#1955]
### Broken Link

https://cwcmy04.na1.hubspotlinks.com/Ctc/I6+113/cWcMY04/VVS2RG3HZ4jYW8fdrlg3D00DsW2qd3df4ZdDNZMBB8Vw3q90_V1-WJV7CgGbBW8Ycy-43L5--pVqPNv3895RWbW4YY8-c59ytX0W4cWSCs8dXRWPW2ZX9pW4PPLkdW4kYhsz8FW08RW28HJHX6ymtgZW6ZPbNG58K59zW2zplY8578fbRW575dy98symRVW4yvm-g13VXDJN3hpG3ZbnDNxW3wpdNn4zr7V8W2WS35G87tS_YW5RJ0LB428sLwW39gqRj6bS9fjW23Pdm52JwhpYW60-G173Xf51sW7lvG3L7kMc2DW2Chyz_7p5MgXW5mqhbz3pc66wW8nhfMJ7x9fMjW24WqH76JpJ3CVFj5Sh5QHZY7W5x_R5Q2VxRgtW17G1xn2g6VqDW7rWMbq4T0H9jW76F0HS3jYYsKW3Lzvdn4ZxQSMW4ybN6N1PtbWv3nCn1

### Expected Location

Substrate and modular FRAME system

### Context and Origin

Was in the intro email for substrate newsletter

**Comment by wirednkod** [comment]
@DeluxeRaph this link leads to https://docs.substrate.io/learn/runtime-development/?_hsmi=216712267&_hsenc=p2ANqtz-_5vbLEawBmb20RBlc4Da_stD6rkBUINsXU2QW1XpLce5GoT6FfSVd1l8IB4bchWfbLGSdZq6PXq_CA1hTQ592wSl8q1VgnErxcv9n6n6jja9hZYmM#frame

So this is not broken. I will close this here - please reopen if link is not correct
