### ISSUE TITLE
SCALE code page link broken

### ISSUE THREAD

**Issue by Ank4n** [substrate-developer-hub/substrate-docs#1959]
### Broken Link

https://docs.substrate.io/v3/advanced/scale-codec/

### Expected Location

https://docs.substrate.io/reference/scale-codec/

### Context and Origin

Redirected from rust docs at https://docs.rs/parity-scale-codec/latest/parity_scale_codec/

**Comment by wirednkod** [comment]
@Ank4n can you confirm if this is still active? It seems that the  links are correct.

**Comment by Ank4n** [comment]
> @Ank4n can you confirm if this is still active? It seems that the  links are correct.

Seems fixed now.
