### ISSUE TITLE
Update references of Substrate src code to `devhub/latest` tag instead of `master` branch in Substrate repo.

### ISSUE THREAD

**Issue by jimmychu0807** [substrate-developer-hub/substrate-docs#199]
Currently when pointing to a piece of Substrate src code, we will point to the master branch of Substrate source code.

The correct action would actually be pointing to the latest monthly tag of Substrate repo instead of master branch. A [`devhub/latest` tag](https://github.com/paritytech/substrate/tree/devhub/latest) has already been created in Substrate repo. The next step is to update site-wide so all src code references are pointing to this floating tag.

To be done after Sub0 launch.

**Comment by NukeManDan** [comment]
decided to use `master` - only templates use `latest`
