### ISSUE TITLE
Sidebar scrolling

### ISSUE THREAD

**Issue by sacha-l** [substrate-developer-hub/substrate-docs#201]
Especially for tutorials where the right sidebar (ToC) is quite long, it would be nice to be able to scroll through all items of the ToC without needing to get out of hovering over it. Easy fix @imadarai 🙏🏻 😃 ?

**Comment by imadarai** [comment]
@sacha-l 
I've pushed some slight modifications to the following: 
- Table of Content (height adjustment to display everything) 
- Highlighting ToC (a bit tighter implementation). 

Can you please review, let me know of any edge cases OR close this issue?
