### ISSUE TITLE
nicks pallet repo and branch not available in "Add a pallet to the runtime"

### ISSUE THREAD

**Issue by muddlebee** [substrate-developer-hub/substrate-docs#2087]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Bug report for compiling, code snippets, templates, etc.

https://docs.substrate.io/tutorials/build-application-logic/add-a-pallet/

> pallet-nicks = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "polkadot-v1.0.0" }

branch = "polkadot-v1.0.0" is not presented in polkadot.sdk repo

**Comment by muddlebee** [comment]
fix, changed repo to substrate.git


pallet-nicks = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.0.0" }

**Comment by sgerodes** [comment]
Nicks does not exists anymore in the polkadot sdk
https://github.com/paritytech/polkadot-sdk/commit/dc4a4559111988300f1a2493b649956d48728ccc
