### ISSUE TITLE
Broken git repository link to clone polkadot chain template for a local relay chain

### ISSUE THREAD

**Issue by poisonhackerfinger** [substrate-developer-hub/substrate-docs#2091]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Bug report for compiling, code snippets, templates, etc.

the command git clone --branch release-v1.0.0 https://github.com/paritytech/polkadot-sdk.git does not work. 
the link in the docs https://github.com/paritytech/polkadot/releases points to a different repository. 
my logical conclusion is the command should be git clone --branch v1.0.0 https://github.com/paritytech/polkadot.git which works.

### Steps to reproduce the problem

git clone --branch release-v1.0.0 https://github.com/paritytech/polkadot-sdk.git

**Comment by poisonhackerfinger** [comment]
Of course!

I found it in this tutorial https://docs.substrate.io/tutorials/build-a-parachain/prepare-a-local-relay-chain/#build-the-relay-chain-node

**Comment by abujulaibib** [comment]
Thanks for reporting, I will create a PR to correct it.👍🏼😊
