### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by asggWa** [substrate-developer-hub/substrate-docs#2092]
In node telemetry section of wiki polkadot network 
:D

**Comment by abujulaibib** [comment]
Are you referring to this [Telemetry page?](https://wiki.polkadot.network/docs/maintain-networks#telemetry-dashboard). All links there seem to be ok. Please provide the link to that specific section

**Comment by asggWa** [comment]
me error. puts error buts redirectings.
issue start here buts a out link... do not exactly remembers buts manual brokes a link. i think wher its mentioned at wiki
