### ISSUE TITLE
BREAKING CHANGE for `--dev` mode

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-docs#218]
https://github.com/paritytech/substrate/pull/9938
> This changes `--dev` to imply `--tmp` when no explicit `--base-path` is provided.

We need to update the docs throughout to reflect this. AFAIK, we don't rely on `--dev` to persist data anywhere, but it's worth noting in our docs/tutorials/HTGs.

This will (likely) be included in the next release of substrate (post `monthly-2021-10`)

**Comment by shawntabrizi** [comment]
https://github.com/paritytech/substrate/pull/10558
