### ISSUE TITLE
<ExternalLink/> component ends the <p> tag

### ISSUE THREAD

**Issue by jimmychu0807** [substrate-developer-hub/substrate-docs#219]
Using `<ExternalLink/>` components with a line break before, e.g:

```html
If you think your edits are valuable, please consider
<ExternalLink url="https://github.com/paritytech/polkadot-launch">opening a PR</ExternalLink>.
```

will end the current `<p>` tag and start a new `<a>` tag. So the "opening a PR" phrase will be in a new line in the rendered html.

The expected behavior is that the "opening a PR" phrase is still rendered on the same line.

**Comment by imadarai** [comment]
@jimmychu0807 thanks for pointing this out.  Looking into it. 
Would you like me to programmatically apply these throughout the MD files? Or are we using them selectively?

**Comment by imadarai** [comment]
@jimmychu0807 #223 should handle this globally so you don't have to worry about adding the components on each MDX.  Closing this for now, but feel free to re-open after your review if there are any edge cases.
