### ISSUE TITLE
Basic OCW configuration

### ISSUE THREAD

**Issue by sacha-l** [substrate-developer-hub/substrate-docs#260]
A how-to guide stepping through the basic configuration of an off-chain worker. This includes:
- configuring the runtime for an OCW
- basic off-chain worker logic
- sending transactions back on chain (signed and unsigned with or without signed payloads)

**Category:** TBD

**Comment by NukeManDan** [comment]
When completed, replace the recipes reference here
https://github.com/substrate-developer-hub/substrate-docs/pull/468

**Comment by muddlebee** [comment]
https://gnunicorn.github.io/substrate-offchain-cb/
https://github.com/paritytech/substrate/tree/master/frame/examples/offchain-worker

Some examples, can be used as a reference.

**Comment by lisa-parity** [comment]
We have some documentation:
https://docs.substrate.io/reference/how-to-guides/offchain-workers/
Maybe close some of these issues to reduce noise for the new site.
