### ISSUE TITLE
OCW HTTP Fetching and JSON Parsing 

### ISSUE THREAD

**Issue by sacha-l** [substrate-developer-hub/substrate-docs#261]
Based on [this](https://substrate.dev/recipes/off-chain-workers/http-json.html) original OCW recipe, this how-to guide steps developers through the process of constructing HTTP request for OCWs including:
- sending a request to a Github API remote endpoint
- using the `serde` library to parse a JSON string from a HTTP response into a data structure
- manipulating that data structure in the node's runtime

**Comment by NukeManDan** [comment]
When completed, replace the recipes reference here
https://github.com/substrate-developer-hub/substrate-docs/pull/468

**Comment by lisa-parity** [comment]
We have some documentation:
https://docs.substrate.io/reference/how-to-guides/offchain-workers/
Maybe close some of these issues to reduce noise for the new site.
