### ISSUE TITLE
Creating and Using Local Storage in OCWs

### ISSUE THREAD

**Issue by sacha-l** [substrate-developer-hub/substrate-docs#262]
Based on [this](https://substrate.dev/recipes/off-chain-workers/storage.html) OCW recipe, this guide aims to step developers through:
- defining a persistent storage value
- defining a storage lock that sets the locking time limit by amount of time passed in blocks
- use the lock to perform an external process and write data back to storage
- use the [offchain_index API](https://substrate.dev/rustdocs/v3.0.0/sp_io/offchain_index/index.html) to write to the offchain database (_Note: this may be its own How-to guide_)

Other ressources:
- https://substrate.dev/rustdocs/v3.0.0/sp_runtime/offchain/storage/struct.StorageValueRef.html
- https://github.com/paritytech/substrate/tree/master/frame/example-offchain-worker

**Comment by NukeManDan** [comment]
When completed, replace the recipes reference here
https://github.com/substrate-developer-hub/substrate-docs/pull/468

**Comment by lisa-parity** [comment]
We have some documentation:
https://docs.substrate.io/reference/how-to-guides/offchain-workers/
Maybe close some of these issues to reduce noise for the new site.
