### ISSUE TITLE
[docs] Update tx-pool#transaction-priority doc

### ISSUE THREAD

**Issue by sacha-l** [substrate-developer-hub/substrate-docs#284]
Update: WIP for the new devhub [here](https://github.com/substrate-developer-hub/docs-sandbox/pull/44).

[This section](https://docs.substrate.io/v3/concepts/tx-pool#transaction-priority) needs an update based on what was introduced in [this new PR](
https://github.com/paritytech/substrate/pull/9834
) in Substrate master.

**Comment by lisa-parity** [comment]
I think we can close this given the doc in the new site.
