### ISSUE TITLE
Add a social preview banner (with new branding)

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-docs#295]
when linking to the published site on social platforms I would like to see a nice banner pop up. Present behavior on discord as a reference:

![image](https://user-images.githubusercontent.com/35669742/136850772-3878bbc2-7154-4010-81a1-c8e626f86126.png)

What I [uploaded to this repo](https://github.com/substrate-developer-hub/substrate-docs/settings) as the social preview could be used, it is presently displayed in the old devhub too as a social preview and shows up in shared links: 

![banner](https://repository-images.githubusercontent.com/389916574/9aaf306a-2ba6-4f68-bc10-e83a72880d8f)

**Comment by NukeManDan** [comment]
I just noticed we have a Parity brand guide for the Substrate logo and such: [parity internal link](https://drive.google.com/drive/folders/1SheqtdyzqQ41RGfOs-sI44PAAgrJamjm)

I figure we should as the design team to update with the right look here?

**Comment by imadarai** [comment]
> I just noticed we have a Parity brand guide for the Substrate logo and such: [parity internal link](https://drive.google.com/drive/folders/1SheqtdyzqQ41RGfOs-sI44PAAgrJamjm)
> 
> I figure we should as the design team to update with the right look here?

I have done this already.  They are a bit occupied with Sub0 at the moment, so I don't expect this to be a fast turn-around.

**Comment by NukeManDan** [comment]
Perhaps it's better to use the same as used by discord for substrate.io in general: 

![image](https://user-images.githubusercontent.com/35669742/137822041-1b429fc9-17ec-4b68-9c13-48f68200c3f8.png)

**Comment by NukeManDan** [comment]
For now I changed it to:
![https://repository-images.githubusercontent.com/389916574/1e4f23de-078a-418b-b2d2-e760548cff5d](https://repository-images.githubusercontent.com/389916574/1e4f23de-078a-418b-b2d2-e760548cff5d)

**Comment by NukeManDan** [comment]
propagated to all devhub org repos (not archived)
