### ISSUE TITLE
[Broken Link]: No v3.0.0 docs redirect?

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-docs#334]
### Broken URL

https://substrate.dev/rustdocs/v3.0.0/src/sp_runtime/generic/unchecked_extrinsic.rs.html#201-209

### Expected redirect

https://paritytech.github.io/substrate/master/sp_runtime/generic/unchecked_extrinsic.rs.html#201-209 for example, but behavior here is looking for a v3 published docs... where are those? 

### Origin

https://github.com/paritytech/txwrapper-core/pull/141

**Comment by sacha-l** [comment]
What's the solution here @NukeManDan ?

**Comment by NukeManDan** [comment]
@jimmychu0807 getting rust docs generated ongoing.
https://github.com/paritytech/substrate/pull/9856
https://github.com/paritytech/substrate/blob/jc%2Frepublish-all-rustdocs/docs/rustdoc-release.md

We still need to manually generate this for v3. I will do this now and place it here, then we need to get this integrated in the site here.
https://github.com/substrate-developer-hub/rustdocs
