### ISSUE TITLE
Updates to Contracts Tuto

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-docs#343]
#293  had from @sacha-l :
> There was also some other work that I've saved [here](https://hackmd.io/@fscJ0GEvRb2rqALLZB1kfA/Sym4wZfBF) for the Contracts tutorial.

I think this was originally @lsgunnlsgunn 's work? :grin:

**Comment by NukeManDan** [comment]
@lisa-parity @sacha-l still relevant?

**Comment by lisa-parity** [comment]
Closing since this is probably out-dated and new issues should be opened against the current content rather than leaving this issue open.
