### ISSUE TITLE
Broken Link: In Tutorials Forkless Upgrade

### ISSUE THREAD

**Issue by ical10** [substrate-developer-hub/substrate-docs#350]
### Broken URL

https://paritytech.github.io/substrate/latest/pallet_scheduler/enum.Call.html#variant.schedule

### Expected redirect

https://paritytech.github.io/substrate/latest/pallet_scheduler/pallet/enum.Call.html#variant.schedule

### Origin

Google search.
Note: I'm not sure about the expected redirect url version of this scheduler pallet, should be checked if `3.0.0` is `latest` version.

**Comment by NukeManDan** [comment]
`latest` is build off the latest tagged monthly release, see https://docs.substrate.io/rustdocs/ - it is _not_ 3.0.0
