### ISSUE TITLE
Rust docs versions on releases

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-docs#352]
`src/pages/rustdocs.tsx` needs to be manually updated per each release - @jimmychu0807 can you outline how this is done for us? 

It is also presently behind the latest actually used `monthly-2021-10` tag in all templates :grimacing: - how can we be sure about linting this?

Also we have no 3.0.0 docs :grimacing: we should have all _major_ releases always available on the rust docs site IMHO
see #334 

Related to #22 and #323 and https://github.com/paritytech/substrate/issues/9821

Tracked in #353

**Comment by NukeManDan** [comment]
https://docs.substrate.io/rustdocs/

**Comment by lisa-parity** [comment]
This looks obsolete to me as we are doing something different now.
