### ISSUE TITLE
[ink] Add chain extension section

### ISSUE THREAD

**Issue by hammeWang** [substrate-developer-hub/substrate-docs#361]
As the chain extension feature has been implemented and proved to work well, maybe we could add a section on introducing how to use it? 

ref: https://github.com/paritytech/ink/pull/645

**Comment by NukeManDan** [comment]
### https://ink.substrate.io/macros-attributes/chain-extension

https://paritytech.github.io/ink/ink_lang/attr.chain_extension.html#example-definition 

https://decoded.polkadot.network/agenda/?date=2022-06-29&location=online&presentation=enable-http-requests-in-ink&tz=online
