### ISSUE TITLE
[ink] Have user run tests first to see them fail?

### ISSUE THREAD

**Issue by tansaku** [substrate-developer-hub/substrate-docs#362]
Given how mistakes in deployed smart contracts are difficult to correct, would it make sense to encourage those following the tutorial to run the tests first to see them fail before then implementing the code to make them pass?

I was just trying that in https://substrate.dev/substrate-contracts-workshop/#/1/storing-a-mapping and was interested to review the following failures:

```
❯ cargo +nightly test
   Compiling incrementer v0.1.0 (/Users/samueljoseph/Documents/Github/tansaku/incrementer)
    Finished test [unoptimized + debuginfo] target(s) in 1.01s
     Running target/debug/deps/incrementer-d10a7711a3840851

running 2 tests
test incrementer::tests::it_works ... ok
test incrementer::tests::default_works ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

❯ cargo +nightly test
   Compiling incrementer v0.1.0 (/Users/samueljoseph/Documents/Github/tansaku/incrementer)
error[E0433]: failed to resolve: use of undeclared crate or module `ink`
  --> lib.rs:61:11
   |
61 |         #[ink::test]
   |           ^^^ use of undeclared crate or module `ink`

error[E0599]: no method named `get_mins` found for struct `incrementer::Incrementer` in the current scope
  --> lib.rs:65:33
   |
9  |     pub struct Incrementer {
   |     ---------------------- method `get_mins` not found for this
...
65 |             assert_eq!(contract.get_mins(), 0)
   |                                 ^^^^^^^^ method not found in `incrementer::Incrementer`

error: aborting due to 2 previous errors
```
Going forward I'm going to use this approach and see how I can remove errors and fix tests as I implement the code.

BTW I love the approach of showing examples and then challenging the learner to implement their own code - great fun! And great learning!

**Comment by NukeManDan** [comment]
Maybe it's best to ask if this should exist in the ink docs: https://github.com/paritytech/ink-docs
