### ISSUE TITLE
Broken Link on Substrate Storage

### ISSUE THREAD

**Issue by justinfrevert** [substrate-developer-hub/substrate-docs#374]
### Broken URL

https://docs.substrate.io/docs/en/knowledgebase/runtime/storage

### Expected redirect

https://docs.substrate.io/v3/runtime/storage/

### Origin

I came here after searching for substrate storage in Google.

**Comment by imadarai** [comment]
Thanks @justinFrevert for pointing this out.  

I've resolved this particular issue in latest PR.
