### ISSUE TITLE
PoE question

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-docs#390]
tracked in #107 posed by @sacha-l, still needs a decision :pray: 

> This section in the Add A Pallet tutorial is already a how-to guide. I think we should just point to it in the "Next steps -> Learn more" section of that tutorial. For now it's just an optional part of the tutorial. Also a bit awkward and more fitting as a HTG anyway. @lsgunnlsgunn what do you think?

**Comment by lsgunnlsgunn** [comment]
@NukeManDan , what section in the Add the Nicks pallet are you referring to? I couldn't quite figure out the reference. I don't think there should be an optional part included in the tutorial. I think you might be referencing a section that I didn't include in my rewritten version.
