### ISSUE TITLE
Write documentation guidelines

### ISSUE THREAD

**Issue by sacha-l** [substrate-developer-hub/substrate-docs#4]
[WIP]
This is an issue to keep track of the items we want to address in our updated contribution guidelines for the new devhub launch.

Components

List all different components: Tip, Advice, Note, Warning, Important
Convention and examples of which instances to use them in
Docs, Tutorials, How-to guides

Full-stops after bullet-points. Convention tbd
TODO: Add link to the different guidelines (htgs, kb docs) here.

**Comment by sacha-l** [comment]
Add in stuff on Prettier here: https://github.com/substrate-developer-hub/substrate-docs/pull/210

**Comment by sacha-l** [comment]
We should include a link to [Substrate's contributing guidelines](https://github.com/paritytech/substrate/blob/master/docs/CONTRIBUTING.adoc).

**Comment by lsgunnlsgunn** [comment]
I like the idea of customizable titles, but I would like to revisit the use
of these components (when, where, and how to use them). Is this something a
Ui / UC person recommended? If so, I’d like to involve him or her in the
discussion post launch.

**Comment by sacha-l** [comment]
💡 A note to include Substrate's contributing guidelines somehow. Maybe have a separate section referring to [this doc](https://github.com/paritytech/substrate/blob/master/docs/CONTRIBUTING.adoc) for developers wanting to contribute to the codebase.

**Comment by sacha-l** [comment]
From Imad's recent PR: https://github.com/substrate-developer-hub/substrate-docs/pull/449#issuecomment-954503200

## Steps to Contribute
### Docs/HTGs (Adding new .mdx files)

- Create a New .mdx file(s) in the same folder tree
- Update DevNavMenu to reflect the addition of pages.

### Tutorials (Adding new ones)

- Create a folder under /v3/tutorials/
- Create or place index.mdx inside the folder.
- Make sure to have ALL the following frontmatter defined

```mdx
---
title: Create your first Substrate blockchain
slug: /tutorials/v3/create-your-first-substrate-chain
hideNav: true
sideNav: firstChain
version: 3.0 
section: tutorials
category: substrate chain
keywords: node template, basics
difficulty: 1
duration: 1 Hour
relevantSkills: 
  - Rust 
  - Blockchain basics
---
```
- Update DevNavMenu.tsx and add the menu items for tutorial. NOTE the name MUST match sideNav field in frontmatter.
Gatsby will do the rest. No need to go into gatsby-config or gatsby-node file.
🥳

**Comment by NukeManDan** [comment]
With https://github.com/substrate-developer-hub/substrate-docs/pull/482 - we want to run `yarn fmt:docs` locally before making any final PR merge, and #500

**Comment by NukeManDan** [comment]
With Main-md branch launching, we will need to update and add this to the new content

**Comment by lisa-parity** [comment]
Closing this issue as obsolete (MDX-specific) and buried in the queue.
We do have a writing style guide:
https://www.notion.so/paritytechnologies/Using-this-guide-for-writing-and-style-581ffe4e80ea498d9fa0ffe4c00a753d
https://github.com/substrate-developer-hub/substrate-docs/tree/archive/main-mdx/v3/docs/00-style-and-contributor-guidelines/b-main-style-guide

We do have contributor's guidelines:
https://github.com/substrate-developer-hub/substrate-docs/tree/archive/main-mdx/v3/docs/00-style-and-contributor-guidelines/a-contributor-guidelines

They haven't been moved over and updated.
