### ISSUE TITLE
Dark mode header links not viewable on production hosted site

### ISSUE THREAD

**Issue by nuke-web3** [substrate-developer-hub/substrate-docs#402]
Nothing appears on hover over a section heading, but the _link_ object is there. [Example](https://docs.substrate.io/v3/runtime/upgrades/#runtime-versioning) : 

![image](https://user-images.githubusercontent.com/35669742/138145599-94888478-f138-47d2-8ce4-0070eb54c1cc.png)

IMHO we should use a much stronger `#` next to the section so it's hard to miss, I discovered this was a common patter (to click to get the section/head/ID and update the URL) by accident moving my mouse across the screen, I think many do. This helps a LOT with sharing links for users to point them to the _right_ place!

**Comment by NukeManDan** [comment]
Wen `main`, ser? 

IMHO this should only be closed when it's on main (link a PR `main <- develop` to closing this issue?)
