### ISSUE TITLE
Feedback Submission - tutorials - Create your first Substrate blockchain - /tutorials/v3/create-your-first-substrate-chain

### ISSUE THREAD

**Issue by remzrn** [substrate-developer-hub/substrate-docs#429]
### Feedback

According to [this commit](https://github.com/substrate-developer-hub/substrate-front-end-template/pull/203), the yarn version to use is 3.0.2. The 1.x branch of yarn is still under development and still the most popular so would be used by most people. If building requires yarn 3, it would be great to mention it explicitly in the docs.

**Comment by lisa-parity** [comment]
Doc was updated to note this.
