### ISSUE TITLE
[CODE BUG]: Issues following Kitties tutorial Part 1

### ISSUE THREAD

**Issue by cryply** [substrate-developer-hub/substrate-docs#437]
### Bug report for compiling, code snippets, templates, etc.

Hi 

I was trying several times but only way to go to part 2 just git clone complete solution with all changes done,

### Steps to reproduce the problem

In double quotes I show original text from https://docs.substrate.io/tutorials/v3/kitties/pt1/

"Let's lay out the basic structure of our pallet by outlining the parts inside pallets/mykitties/src/lib.rs."
>>> There is no mykitties as we enter kitties in kickstarter

"Now try running the following command to build your pallet. We won't build the entire chain just yet because we haven't yet implemented the Currency type in our runtime. At least we can check that there are no errors in our pallet so far:"

cargo build -p pallet-kitties

>>> This not gonna compile as 

error[E0433]: failed to resolve: use of undeclared crate or module `sp_io`
  --> pallets/kitties/src/lib.rs:12:9
   |
12 |     use sp_io::hashing::blake2_128;
   |         ^^^^^ use of undeclared crate or module `sp_io`

And reason is that kickstarted generated Cargo.toml  mention sp-io only for devdependencies

[dev-dependencies.sp-io]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'monthly-2021-10'
version = '4.0.0-dev'

So through article there situation where cargo.toml involved. Maybe make sense to show this changes in same manner like changes in .rs files.

"Now build your node and make sure you don't have any errors. This will take a little while at first."

cargo build --release

>>> It worth mention that we go to root folder of project to build root node. As previous commands run from pallets/kitties subfolder.

Anyhow this build failed:

  error: `SubstrateKitties` does not have #[pallet::genesis_config] defined, perhaps you should remove `Config` from construct_runtime?
     --> /home/user/study/substrate/my5/kitties/runtime/src/lib.rs:281:1
      |
  281 | / construct_runtime!(
  282 | |     pub enum Runtime where
  283 | |         Block = Block,
  284 | |         NodeBlock = opaque::Block,
  ...   |
  298 | |     }
  299 | | );
      | |_^
      |
      = note: this error originates in the macro `pallet_kitties::__substrate_genesis_config_check::is_genesis_config_defined` (in Nightly builds, run with -Z macro-backtrace for more info)

  error[E0119]: conflicting implementations of trait `core::convert::From<pallet_kitties::Event<Runtime>>` for type `Event`
     --> /home/user/study/substrate/my5/kitties/runtime/src/lib.rs:281:1
      |
  281 | / construct_runtime!(
  282 | |     pub enum Runtime where
  283 | |         Block = Block,
  284 | |         NodeBlock = opaque::Block,
  ...   |
  298 | |     }
  299 | | );
      | | ^
      | | |
      | |_first implementation here
      |   conflicting implementation for `Event`
      |
      = note: this error originates in the macro `construct_runtime` (in Nightly builds, run with -Z macro-backtrace for more info)

  error[E0119]: conflicting implementations of trait `core::convert::From<pallet_kitties::Call<Runtime>>` for type `Call`
     --> /home/user/study/substrate/my5/kitties/runtime/src/lib.rs:281:1
      |
  281 | / construct_runtime!(
  282 | |     pub enum Runtime where
  283 | |         Block = Block,
  284 | |         NodeBlock = opaque::Block,
  ...   |
  298 | |     }
  299 | | );
      | | ^
      | | |
      | |_first implementation here
      |   conflicting implementation for `Call`
      |
      = note: this error originates in the macro `construct_runtime` (in Nightly builds, run with -Z macro-backtrace for more info)

  error[E0119]: conflicting implementations of trait `core::convert::TryInto<pallet_kitties::Event<Runtime>>` for type `Event`
     --> /home/user/study/substrate/my5/kitties/runtime/src/lib.rs:281:1
      |
  281 | / construct_runtime!(
  282 | |     pub enum Runtime where
  283 | |         Block = Block,
  284 | |         NodeBlock = opaque::Block,
  ...   |
  298 | |     }
  299 | | );
      | | ^
      | | |
      | |_first implementation here
      |   conflicting implementation for `Event`
      |
      = note: this error originates in the macro `construct_runtime` (in Nightly builds, run with -Z macro-backtrace for more info)

  error[E0119]: conflicting implementations of trait `sp_api_hidden_includes_construct_runtime::hidden_include::traits::IsSubType<pallet_kitties::Call<Runtime>>` for type `Call`
     --> /home/user/study/substrate/my5/kitties/runtime/src/lib.rs:281:1
      |
  281 | / construct_runtime!(
  282 | |     pub enum Runtime where
  283 | |         Block = Block,
  284 | |         NodeBlock = opaque::Block,
  ...   |
  298 | |     }
  299 | | );
      | | ^
      | | |
      | |_first implementation here
      |   conflicting implementation for `Call`
      |
      = note: this error originates in the macro `construct_runtime` (in Nightly builds, run with -Z macro-backtrace for more info)

  For more information about this error, try `rustc --explain E0119`.
  error: could not compile `node-kitties-runtime` due to 5 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by manylov** [comment]
Following tutorial, it still doesn't work.
I have [dev-dependencies.sp-io] in /pallets/kitties/Cargo.toml 
but when I run `cargo build -p pallet-kitties `
I have error and warnings
```
Compiling pallet-kitties v3.0.0-monthly-2021-10 (/Users/maxim/dev/kitties-tutorial/pallets/kitties)
error[E0433]: failed to resolve: use of undeclared crate or module `sp_io`
  --> pallets/kitties/src/lib.rs:12:9
   |
12 |     use sp_io::hashing::blake2_128;
   |         ^^^^^ use of undeclared crate or module `sp_io`

warning: unused imports: `DispatchResultWithPostInfo`, `DispatchResult`, `ExistenceRequirement`, `Hash`, `Randomness`, `Zero`
 --> pallets/kitties/src/lib.rs:7:46
  |
7 |     use frame_support::{sp_runtime::traits::{Hash, Zero},
  |                                              ^^^^  ^^^^
8 |                         dispatch::{DispatchResultWithPostInfo, DispatchResult},
  |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^
9 |                         traits::{Currency, ExistenceRequirement, Randomness},
  |                                            ^^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `frame_system::pallet_prelude::*`
  --> pallets/kitties/src/lib.rs:11:9
   |
11 |     use frame_system::pallet_prelude::*;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0433`.
```

Also, as a newbie, I don't understand what does this mean: 

***Check that you're using the correct monthly-* tag and version otherwise you will get a dependency error. Here, we're using the monthly-2021-10 tag of Substrate.***

I've installed Rust and Substrate exactly like was written here: https://docs.substrate.io/v3/getting-started/installation/

**Comment by sacha-l** [comment]
Hi @manylov - the clause I added: 
> Notice that we're using sp_io in our pallet. Ensure that this is declared as a dependency in your pallet's Cargo.toml file:

..means that you need to remove the `dev-` so that its included as a dependancy not as a `dev-dependency`.

The other clause: 
> Check that you're using the correct monthly- tag and version otherwise you will get a dependency error. Here, we're using the monthly-2021-10 tag of Substrate.*

.. is  just a note for when we may already have the last `monthly` tag of the template but it's not updated in the tutorial. Its more of a precautionary note. In your case it should work fine.

Let me know if this works!

**Comment by manylov** [comment]
Yes it works, thank you.

**Comment by cryply** [comment]
In 2 last helpers files (of part 1) missing line :

  `use scale_info::TypeInfo;`
  
after use sp_io::hashing::blake2_128;

In last helper file unused :
```
mod mock;
mod tests;

```
As we deleted them at scaffolding phase in the beginning of article
