### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by luatnd** [substrate-developer-hub/substrate-docs#440]
### Broken URL

https://docs.substrate.io/en/community

### Expected redirect

Dont know

### Origin

From google search result:

```
Source
substrate.dev was first indexed by Google in March 2019
·
Your connection to this site is secure
·
https://substrate.dev/en/community
```

**Comment by sacha-l** [comment]
@imadarai can you add a redirect for this ? 🙏🏻
