### ISSUE TITLE
[Content] Doc Sidebar Section

### ISSUE THREAD

**Issue by imadarai** [substrate-developer-hub/substrate-docs#446]
### Content request

<img width="253" alt="Screenshot 2021-10-28 at 18 40 43" src="https://user-images.githubusercontent.com/57454832/139299413-f596f864-5e02-46c6-86a5-16d8e5c126b4.png">

So the section above is meant to be a red-robin.  As in, if a person is viewing a tutorial, they won't see that option, but all the others in that section.  Suggestion is to display all the sections, and provide another way for users to quickly jump, instead of scrolling up. 

Secondly, @sacha-l has recommended to change `Knowledgebase` to `Reference Docs`.

Just wanted to see if anyone has strong opinions about this, or just give me a thumbs-up and I'll make the change. 

### Are you willing to help with this request?

Yes!

CC @NukeManDan @lsgunnlsgunn @Eve-Parity

**Comment by NukeManDan** [comment]
knowledgebase AFAIK has been deprecated. Docs is the goto, and Rust Docs I think we might consider "Rust API" in that for the distinction from conceptual docs.

reference:
https://doc.rust-lang.org/book/ch14-02-publishing-to-crates-io.html#making-useful-documentation-comments
