### ISSUE TITLE
Feedback Submission - docs - Installation - /v3/getting-started/installation

### ISSUE THREAD

**Issue by Petras98** [substrate-developer-hub/substrate-docs#457]
### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Other (please write below)

### Feedback

On the installation page of the docs, under the “Test Your Setup” section, there is a typo in the warning/info box:
“ For more details on why these dependancies [should be -> dependencies] are used, ...”

**Comment by NukeManDan** [comment]
Thanks! Fixed in #464 

Next time I encourage you to submit a PR to help make our docs better, and add you to the contributor list :sunglasses: 

![image](https://user-images.githubusercontent.com/35669742/139734265-66d572ad-c9ed-47bb-9ba1-559f1eb045d7.png)
