### ISSUE TITLE
[CODE BUG]: Kitties tutorial part2

### ISSUE THREAD

**Issue by cryply** [substrate-developer-hub/substrate-docs#461]
### Bug report for compiling, code snippets, templates, etc.

Set Price not working

### Steps to reproduce the problem

When you click set price in modal window you can see disabled _Transfer_ button.
When u set amount its still disabled.
I used original helper files files

**Comment by sacha-l** [comment]
Thanks for reporting this ! The reason this is the case is because creating the Set Price modal is not actually part of the tutorial. The intention was to encourage folks to write it but this was never specified in the tutorial. Working on fixing this. Will link this issue to a PR.

**Comment by sacha-l** [comment]
@cryply : Fix now: https://github.com/substrate-developer-hub/substrate-front-end-template/blob/tutorials/kitties/src/KittyCards.js#L46-L83 🎈
