### ISSUE TITLE
Feedback Submission - tutorials - Start a Private Network - /tutorials/v3/private-network

### ISSUE THREAD

**Issue by VIPOJIKOP** [substrate-developer-hub/substrate-docs#462]
### Feedback

{
  //-- snip --
  "genesis": {
    "runtime": {
      "frameSystem": {
        //-- snip --
      },
      "palletAura": {
        "authorities": [
          "5FfBQ3kwXrbdyoqLPvcXRp7ikWydXawpNs2Ceu3WwFdhZ8W4",
          "5EhrCtDaQRYjVbLi7BafbGpFqcMhjZJdu8eW8gy6VRXh6HDp"
        ]
      },
      "palletGrandpa": {
        "authorities": [
          ["5G9NWJ5P9uk7am24yCKeLZJqXWW6hjuMyRJDmw4ofqxG8Js2", 1],
          ["5CRZoFgJs4zLzCCAGoCUUs2MRmuD5BKAh17pWtb62LMoCi9h", 1]
        ]
      }
      //-- snip --
    }
  }
}

**Comment by NukeManDan** [comment]
Sorry - what is the question or issue exactly?

**Comment by sacha-l** [comment]
@VIPOJIKOP: please feel free to re-open this issue if you have a specific question or problem statement. 🙏
