### ISSUE TITLE
Feedback Submission - tutorials - Build a proof of existence dApp - /tutorials/v3/proof-of-existence

### ISSUE THREAD

**Issue by KazyCC** [substrate-developer-hub/substrate-docs#467]
### What browsers are you seeing the problem on?

Firefox (93.0 (64-bit))

### Feedback

During tutorial "https://docs.substrate.io/tutorials/v3/proof-of-existence/" when executed point "Add your custom react component" the mentioned "Proof of existence" react component is not showing after "yarn start". Cannot progress further with tutorial. Note: "`templateModule`" is visible in Pallet Interactor.

**Comment by sacha-l** [comment]
Hi @KazyCC ! Did you include the custom React component outlined in [this step](https://docs.substrate.io/tutorials/v3/proof-of-existence/#build-a-custom-front-end-component) ?

**Comment by KazyCC** [comment]
> Hi @KazyCC ! Did you include the custom React component outlined in [this step](https://docs.substrate.io/tutorials/v3/proof-of-existence/#build-a-custom-front-end-component) ?

1) Yes, it's definitely included in sources, but still after 'yarn start' it is still behaving like old TemplateModule.js is loading. I even looked if I'm editing correct file in correct dir.
2) Since it is looking like "old content is cached somewhere", I call 'yarn cache clean'. No difference.

**Comment by sacha-l** [comment]
@KazyCC please cross check against [the front-end solution](https://github.com/substrate-developer-hub/substrate-front-end-template/tree/tutorials/solutions%2Fproof-of-existence) to see what your missing. It's difficult to understand the issue without seeing your code, could you share your repository if you have one?

**Comment by KazyCC** [comment]
@sacha-l My fork of repo is available here: https://github.com/KazyCC/substrate-front-end-template
I forked your repo once again, followed the tutorial and still the same: "The customized front-end template includes the new proof of existence component." is not present.

**Comment by sacha-l** [comment]
Hi @KazyCC - apologies for such a long delay here! Looks like you weren't using the most up to date version of the template.  I've also updated the [solution here](https://github.com/substrate-developer-hub/substrate-front-end-template/tree/tutorials/solutions/proof-of-existence). So in your fork, you need to `pull` new changes from remote: `git checkout master` , `git pull upstream master`. This will create some changes in your branch. Make sure to `yarn install`. Then do `yarn start` and it should work. Please re-open this if you're still unable to make this work and I can see what I can do. I've done these steps on your branch and it worked for me so it should for you too! 😃
