### ISSUE TITLE
Feedback Submission - tutorials - Create your first Substrate blockchain - /tutorials/v3/create-your-first-substrate-chain

### ISSUE THREAD

**Issue by bluewitch** [substrate-developer-hub/substrate-docs#491]
### Feedback

hello all, not sure where to resolve this but I seem to be running into issues for the front-end-node, everything compiles but I get this error  Error Connecting to Substrate

{ "isTrusted": true }

**Comment by NukeManDan** [comment]
Duplicate, closing. 
See https://github.com/substrate-developer-hub/substrate-front-end-template/issues/209
