### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by gautamdhameja** [substrate-developer-hub/substrate-docs#492]
### Broken URL

https://docs.substrate.io/docs/low-level-data-formats

### Expected redirect

https://docs.substrate.io/v3/advanced/scale-codec/

**Comment by NukeManDan** [comment]
@gautamdhameja what was the origin of this link? (Where did you find it?)

**Comment by gautamdhameja** [comment]
I think it was in one of the old versions of the codec readme. It seems to be updated there, but still worth the redirect in case it is still there somewhere.
