### ISSUE TITLE
Working on srtool guide: https://github.com/substrate-developer-hub/substrate-docs/projects/1#card-71316894

### ISSUE THREAD

**Issue by lsgunnlsgunn** [substrate-developer-hub/substrate-docs#498]
This probably falls into the category of reference documentation.

**Comment by NukeManDan** [comment]
duplicate #407 ?

**Comment by sacha-l** [comment]
Good article giving context for the utility of this tool: https://dev.to/gnunicorn/hunting-down-a-non-determinism-bug-in-our-rust-wasm-build-4fk1
