### ISSUE TITLE
`keywords` item to an array of strings

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-docs#499]
We may use a _lot_ of keywords to help the pages get in our local search (and SEO?). Presently it is unclear what a search word is, sometimes these are two words or more.

For #482 and mother formatting, it would be best to make this an array of strings for ease of management and sorting as well. 

Anything that _would block_ this? I see no reason.

**Comment by imadarai** [comment]
@NukeManDan I see no blocker.  I'll keep this on my radar and update accordingly.

**Comment by NukeManDan** [comment]
duplicate #1164
