### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by byhow** [substrate-developer-hub/substrate-docs#505]
### Broken Link

https://docs.substrate.io/awesome-substrate/

### Context and Origin

Was looking for a sample polkadot fee estimate API call on transaction for sidecar, but link has directed to a 404

**Comment by sacha-l** [comment]
@byhow - thanks for reporting this. Do you know where you were when your clicked on this link? It would help to identify the source of where these URLs exist to fix this issue properly.

**Comment by byhow** [comment]
@sacha-l - I was clicking from a google search result, not from inside substrates docs. I am assuming it supposed to be this link? https://substrate.io/ecosystem/resources/awesome-substrate/ 

Or it could be an outdated cache on google's side. Hopefully that helps!
