### ISSUE TITLE
Feedback Submission - tutorials - Build a proof of existence dApp - /tutorials/v3/proof-of-existence

### ISSUE THREAD

**Issue by JosephKnecht-lab** [substrate-developer-hub/substrate-docs#509]
### What browsers are you seeing the problem on?

Chrome

### Feedback

The React code has the following linting errors: 

Line 2:51:    Missing semicolon                                                        semi
  Line 3:63:    Missing semicolon                                                        semi
  Line 7:47:    Missing semicolon                                                        semi
  Line 8:54:    Missing semicolon                                                        semi
  Line 11:52:   Missing semicolon                                                        semi
  Line 14:21:   Missing space before function parentheses                                space-before-function-paren
  Line 16:33:   Missing semicolon                                                        semi
  Line 18:32:   Missing semicolon                                                        semi
  Line 21:43:   Missing semicolon                                                        semi
  Line 22:43:   Missing semicolon                                                        semi
  Line 23:41:   Missing semicolon                                                        semi
  Line 24:40:   Missing semicolon                                                        semi
  Line 26:17:   Missing semicolon                                                        semi
  Line 32:16:   Missing semicolon                                                        semi
  Line 33:43:   Missing semicolon                                                        semi
  Line 34:20:   Missing semicolon                                                        semi
  Line 35:4:    Missing semicolon                                                        semi
  Line 39:34:   Missing semicolon                                                        semi
  Line 40:42:   Missing semicolon                                                        semi
  Line 41:39:   Missing semicolon                                                        semi
  Line 42:4:    Missing semicolon                                                        semi
  Line 46:20:   Missing semicolon                                                        semi
  Line 53:39:   Missing semicolon                                                        semi
  Line 54:39:   Missing semicolon                                                        semi
  Line 57:28:   Missing semicolon                                                        semi
  Line 58:9:    Missing semicolon                                                        semi
  Line 59:46:   Missing semicolon                                                        semi
  Line 63:36:   Missing semicolon                                                        semi
  Line 66:21:   Missing space before function parentheses                                space-before-function-paren
  Line 67:23:   Missing semicolon                                                        semi
  Line 106:34:  Unexpected trailing comma                                                comma-dangle
  Line 120:34:  Unexpected trailing comma                                                comma-dangle
  Line 128:4:   Missing semicolon                                                        semi
  Line 131:34:  Missing space before function parentheses                                space-before-function-paren
  Line 132:33:  Missing semicolon                                                        semi
  Line 133:10:  Expected newline between test and consequent of ternary expression       multiline-ternary
  Line 133:62:  Expected newline between consequent and alternate of ternary expression  multiline-ternary
  Line 135:11:  Missing semicolon                                                        semi
  Line 136:2:   Newline required at end of file but not found                            eol-last

**Comment by sacha-l** [comment]
Thanks for bringing this up. Will be fixed in the next upcoming PR. Just needed to run: `yarn lint --fix` . Cheers.
