### ISSUE TITLE
Parachain connect should mention the creation of a chain spec

### ISSUE THREAD

**Issue by bkchr** [substrate-developer-hub/substrate-docs#513]
### Content request

https://docs.substrate.io/how-to-guides/v3/parachains/connect

We should add as step 2 a detailed description on how to create a proper chain spec. Beginning with a json chain spec, where the user again ensures that all values are as expected, e.g. the parachain id. Then the creation of the raw chain spec out of the json chain spec. In the next steps we should then also use this created chain spec.

### Are you willing to help with this request?

Yes!

**Comment by SBalaguer** [comment]
Thanks Basti for creating the PR! I believe this piece of information also applies to the [How to Generate Genesis State on Parachains](https://docs.substrate.io/how-to-guides/v3/parachains/connect/#2-generate-the-genesis-state).

**Comment by bkchr** [comment]
Yeah, that is what I also mentioned above :)

**Comment by samelamin** [comment]
I faced the exact same issue

Also willing to help with this PR in any way I can :)

**Comment by NukeManDan** [comment]
Note for us to reference this: https://github.com/paritytech/cumulus/pull/739

**Comment by riusricardo** [comment]
This issue needs to be solved soon. We are getting close to Polkadot v0.9.13 which contains this breaking change.
Required changes in:
1) Cumulus Workshop
2) How To Guides

**Comment by bernardoaraujor** [comment]
@riusricardo I started working on a PR for the How-To-Guides: https://github.com/bernardoaraujor/substrate-docs/commit/3cbd97e51d070a059e45dc0dda108ac93931510f

How does this issue affect the Cumulus Workshop?
It seems a pre-configured chain-spec is already provided there?
https://docs.substrate.io/tutorials/v3/cumulus/start-relay/#pre-configured-chain-spec-files
