### ISSUE TITLE
Feedback Submission - tutorials - Build the Substrate Kitties Chain - /tutorials/v3/kitties/pt1

### ISSUE THREAD

**Issue by JosephKnecht-lab** [substrate-developer-hub/substrate-docs#516]
### Feedback

   ` use serde::{Deserialize, Serialize};`

should be replaced with 

`use frame_support::serde::{Deserialize, Serialize};`

Serde is not imported directly in the template Cargo.toml file so https://github.com/substrate-developer-hub/substrate-docs/blob/main/static/assets/tutorials/kitties-tutorial/02-create-kitties.rs throws an error.

**Comment by sacha-l** [comment]
@JosephKnecht-lab : thanks for pointing this out. We import it in [this step](https://docs.substrate.io/tutorials/v3/kitties/pt1/#write-a-custom-type-for-gender) in Cargo.toml:

```toml
[dependencies.serde]
default-features = false
version = '1.0.119'
```

However using `frame_support` is probably better practice. Need to verify.

Note there's a PR bringing in lots of updates to the Kitty tutorial here: https://github.com/substrate-developer-hub/substrate-docs/pull/512 - just in case you're running into issues we already addressed 😺

**Comment by sacha-l** [comment]
Checked and updated the tutorial. Thanks, this removes the extra step mentioned above on updating `Cargo.toml`. 🙏🏻

**Comment by luatnd** [comment]
For the latest guide, I got this error on the tutorial 4: kittes pallet: if I using `monthly-2021-10` 
```
error[E0463]: can't find crate for `serde`
  --> pallets/kitties/src/lib.rs:42:37
   |
42 |     #[cfg_attr(feature = "std", derive(Serialize, Deserialize))]
   |                                        ^^^^^^^^^ can't find crate
   |
   = note: this error originates in the derive macro `Serialize` (in Nightly builds, run with -Z macro-backtrace for more info)
```

My solution is update all dependencies to latest tag following this [commit](https://github.com/sacha-l/substrate-node-template/compare/1655c1241b48667a16a537ebf72c4114ebb104f3...65de1e7fa3682d0ec023a732fa3a4747c8a5013c#)
