### ISSUE TITLE
Feedback Submission - how to guides - Simple Crowdfund - /how-to-guides/v3/pallet-design/crowdfund

### ISSUE THREAD

**Issue by patrickdevelopes** [substrate-developer-hub/substrate-docs#520]
### Feedback

Grammar mistake in section **3. Declare your storage items**: 
https://docs.substrate.io/how-to-guides/v3/pallet-design/crowdfund/#3-declare-your-storage-items

**Grammar mistake in the second sentence:**
"First, deine the following types which will be used to declare our storage items:"

**should be**

"First, define the following types which will be used to declare our storage items:"

**Comment by sacha-l** [comment]
Thanks @patrickdevelopes, very much appreciated! 😃
