### ISSUE TITLE
Broken Search Results (no reaction on click)

### ISSUE THREAD

**Issue by apopiak** [substrate-developer-hub/substrate-docs#526]
### What browsers are you seeing the problem on?

Firefox

### Bug report for the website

I searched for "aura" in https://docs.substrate.io and got a list of results.
When I click on any of the results, nothing happens.
The console shows (lots of instances of):
```
Uncaught (in promise) Error: We couldn't find the correct component chunk with the name component---src-templates-kb-template-tsx
    o loader.js:493
    o loader.js:247
    promise callback*28741/t.loadPage loader.js:234
    hovering loader.js:428
    hovering loader.js:572
    onMouseEnter index.js:266
    React 11
    unstable_runWithPriority scheduler.production.min.js:18
    Gt React
```

### Steps to reproduce the problem

Search for "aura" in https://docs.substrate.io and click on any result.

Firefox Developer Edition 95.0b5 (64-Bit) - Ubuntu

**Comment by apopiak** [comment]
Right click "open in new tab" works on the result, though.

**Comment by imadarai** [comment]
@apopiak I'm unable to reproduce this bug on my end and have tried different configurations.  This sounds pretty much like a support answer, but can you do a hard refresh (ctrl+shift+r) couple of times and try loading the site again.  
I'm wondering if this has something to do with cache and the way we store search results.  Thanks!

**Comment by apopiak** [comment]
Classic "Have you tried to turn it off and on again xD
Works after a hard releoad (ctrl+shift+r) :shrug:

**Comment by imadarai** [comment]
> Classic "Have you tried to turn it off and on again" xD Works after a hard reload (ctrl+shift+r) 🤷

@apopiak No please!  
I think it's an edge case with the way we cache search results, which doesn't necessarily corresponds to the way we refresh it once we deploy new changes + search-index.  I'll try couple of different things to reproduce it.  If you see it again, please do let me know! (or anything else funky for that matter) 

Thanks a million!
