### ISSUE TITLE
Feedback Submission - tutorials - Start a Private Network - /tutorials/v3/private-network

### ISSUE THREAD

**Issue by Doordashcon** [substrate-developer-hub/substrate-docs#533]
### What browsers are you seeing the problem on?

Chrome

### Feedback

When attempting to start [subsequent node](https://docs.substrate.io/tutorials/v3/private-network/#subsequent-participants-join) I encountered this error message.
```bash
Invalid value for '--telemetry-url <URL VERBOSITY>...': Verbosity level missing
```
Found the solution on [https://github.com/paritytech/polkadot/issues/1828](https://github.com/paritytech/polkadot/issues/1828) by @bkchr 

Adding it to the documentation as well would be great

**Comment by lisa-parity** [comment]
Thanks for bringing our attention to this.Single quotes changed to double quotes in the tutorial. The site will get the change when the PR https://github.com/substrate-developer-hub/substrate-docs/pull/458 is merged
