### ISSUE TITLE
Apple M1 ARM chip builds 

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-docs#538]
https://github.com/paritytech/polkadot/issues/3482
instructions can be updated to use the right toolchain explicitly:
```bash
rustup install stable-aarch64-apple-darwin
rustup default stable-aarch64-apple-darwin
cargo clean
cargo build --release
```

**Comment by brunopgalvao** [comment]
LGTM @NukeManDan 

Interestingly when I first installed rust on my M1 machine running `rustup default stable`, rustup installed: `stable-x86_64-apple-darwin`. I had to manually install and switch to `stable-aarch64-apple-darwin` like you mentioned to get the builds to work. Curious why rustup doesn't install `stable-aarch64-apple-darwin` by default 🤷🏻
