### ISSUE TITLE
Feedback Submission - tutorials - Add the Nicks Pallet to your Runtime - /tutorials/v3/add-a-pallet

### ISSUE THREAD

**Issue by guzzit** [substrate-developer-hub/substrate-docs#541]
### Feedback

In this [section](https://docs.substrate.io/tutorials/v3/add-a-pallet/#add-the-nicks-pallet-to-the-node-template), there is a paragraph that starts like this: 

> In this dependencies.pallet-nicks section, default-features = false specifies that the default features to be understand...

It seems off, even when you replace "understand" with "understood". Perhaps what should be there is a term like "integrated"?

**Comment by kamikazebr** [comment]
Yah kinda confused. What it really does? Just disable the std library native?

**Comment by sacha-l** [comment]
Yes this was super confusing, thanks for flagging. It was actually caught and fixed here: #574.
