### ISSUE TITLE
delete `sandbox` and move to sandbox repo

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-docs#554]
Based on https://github.com/substrate-developer-hub/substrate-docs/pull/542#pullrequestreview-808125351, I propose we all target the [sandbox branch](https://github.com/substrate-developer-hub/substrate-docs/tree/sandbox) for all refactoring of the site.

Once the rough outline of things are in place, we can modify `main` to have the CI check a PR from `main` <- `sandbox` to ensure we are not going to break anything. Or if it's easy, have CI for `sandbox` while we are working on it.

**Comment by sacha-l** [comment]
Is this still relevant or can we close ? cc @NukeManDan

**Comment by NukeManDan** [comment]
Yes we should **delete** the snadbox branch, and all content AFAIK is ported over, can we have @lisa-parity confirm this before we do? Then we close the issue here.

**Comment by lsgunnlsgunn** [comment]
Refector is happening in the sandbox repo.
