### ISSUE TITLE
Substrate Kitties Tutorial: kickstart is using monthly-2021-10 substrate, tutorial requires monthly-2021-11, resulting in sp-io dependancy tag issues + downstream frame_support::serde issue. 

### ISSUE THREAD

**Issue by pyramid-songs** [substrate-developer-hub/substrate-docs#556]
### Feedback

I'm following the Substrate Kitties tutorial and noticed there's a step fairly close to the start where we specify the `sp-io` package in the pallet `Cargo.toml`:

```
[dependencies.sp-io]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'monthly-2021-11'
version = '4.0.0-dev'
```

When I use the `kickstart https://github.com/sacha-l/kickstart-substrate` command to clone a new substrate node template for the tutorial, I notice that all the packages specified in the pallet and runtime `Cargo.tomls` are v3.0.0-monthly-2021-10. Using `sp-io` with `monthly-2021-11` gives the following:

```
error: failed to select a version for `tracing`.
    ... required by package `sp-io v4.0.0-dev (https://github.com/paritytech/substrate.git?tag=monthly-2021-11#26d69bcb)`
    ... which satisfies git dependency `sp-io` of package `pallet-kitties v3.0.0-monthly-2021-10 (/home/pyramid/dev/kitties/pallets/kitties)`
    ... which satisfies path dependency `pallet-kitties` of package `node-kitties-runtime v3.0.0-monthly-2021-10 (/home/pyramid/dev/kitties/runtime)`
    ... which satisfies path dependency `node-kitties-runtime` of package `node-kitties v3.0.0-monthly-2021-10 (/home/pyramid/dev/kitties/node)`
versions that meet the requirements `^0.1.29` are: 0.1.29

all possible versions conflict with previously selected packages.

  previously selected package `tracing v0.1.28`
    ... which satisfies dependency `tracing = "=0.1.28"` of package `sc-service v0.10.0-dev (https://github.com/paritytech/substrate.git?tag=monthly-2021-10#bf9683ee)`
    ... which satisfies git dependency `sc-service` of package `frame-benchmarking-cli v4.0.0-dev (https://github.com/paritytech/substrate.git?tag=monthly-2021-10#bf9683ee)`
    ... which satisfies git dependency `frame-benchmarking-cli` of package `node-kitties v3.0.0-monthly-2021-10 (/home/pyramid/dev/kitties/node)`
```

The tutorial can be run by changing the `sp-io` tag to 'monthly-2021-10'. This allows me to compile and continue the tutorial right up until the point [where we use the frame_support::serde::{Serialize, Deserialize}](https://docs.substrate.io/tutorials/v3/kitties/pt1/#write-a-custom-type-for-gender) as per the recent change to https://github.com/substrate-developer-hub/substrate-docs/issues/516

Not having much familiarity with the `kickstart` package, what would be the best way to remedy this situation?

**Comment by fky2015** [comment]
You need to regenerate `Cargo.lock` file by `cargo update`.

**Comment by sacha-l** [comment]
@pyramid-songs : Thanks for flagging this. It should be [fixed now](https://github.com/sacha-l/kickstart-substrate/commit/b7529baef712970436ac03ca16880533fc6f1473) - I just had to update the submodule kickstart uses.
