### ISSUE TITLE
Keywords and search

### ISSUE THREAD

**Issue by lisa-parity** [substrate-developer-hub/substrate-docs#580]
Imad: "For sake of time and simplicity, I just reverted the three markdown pages that had arrays to strings for now. Mainly to get rid of the CI error in gatsby. This is also not configured in search at the moment, so strings are acceptable vs arrays. If we want to switch it all to arrays, we should do it in a one go and update our search to account for it. Or else it's just going to output null and not count keywords towards the final score." See: https://github.com/substrate-developer-hub/substrate-docs/pull/459#discussion_r744527547

**Comment by NukeManDan** [comment]
YAML is somewhat oppinionated to use the "bulleted list" for this section: https://www.mkdocs.org/user-guide/writing-your-docs/#yaml-style-meta-data
