### ISSUE TITLE
Wrong Word, Misleading - tutorials - Start a Relay Chain - /tutorials/v3/cumulus/start-relay

### ISSUE THREAD

**Issue by Fahrrader** [substrate-developer-hub/substrate-docs#586]
### Feedback

> We have included **three set** of chain spec files in this tutorial that you can use without modification for a local test network:

It seems like "three" should have been "the". Link to the paragraph: [https://docs.substrate.io/tutorials/v3/cumulus/start-relay/#pre-configured-chain-spec-files](https://docs.substrate.io/tutorials/v3/cumulus/start-relay/#pre-configured-chain-spec-files)

**Comment by sacha-l** [comment]
Looks like @NukeManDan will be merging this 🔜 👀  ! Thanks @Fahrrader for pointing this out 🙏🏻 .
