### ISSUE TITLE
Feedback Submission - tutorials - Build a proof of existence dApp - /tutorials/v3/proof-of-existence

### ISSUE THREAD

**Issue by weezy20** [substrate-developer-hub/substrate-docs#594]
### What browsers are you seeing the problem on?

Chrome

### Feedback

For a beginner's tutorial this completely misses the changes one might need to perform on the Runtime/lib.rs file. While this tutorial works for customizing a pre-existing template, and it's associated runtime inclusion in the construct_runtime! macro, I think it would be more beneficial for the reader, if they could be involved in the process. A second problem that I faced was with the React front-end code. More specifically, I don't see a file uploading component as promised in the tutorial, instead the front-end asks me for bytes in the proof field:
![image](https://user-images.githubusercontent.com/15669111/142875803-0a551d38-ce63-48ff-a430-4673a80d7b74.png)
I don't know if this is a issue because I didn't follow the tutorial strictly( I created my own crate, called pallet-proof-of-existence and incorporated that in the runtime) or if it's an issue with the front-end code, a little clarification would be nice :)

**Comment by sacha-l** [comment]
Thanks for bringing this up @weezy20 - will look into it and update here.

**Comment by sacha-l** [comment]
Thanks for your feedback @weezy20.

A couple things:
- The intention for this tutorial is to make it easy to work through, hence why we're not asking folks to modify the `runtime/src/lib.rs` file. In addition, the only `Config` associated type our pallet has is `Event` which is already configured from the `pallet_template` the tutorial uses. There's a more involved tutorials, like the Kitties one.
- If you follow the steps of the tutorial you should be able to see the Proof of Existence component show up. It's at the bottom of the page too, but you could change that in `App.js` The screenshot above is a general "pallet interactor" as in it allows you to interact with any pallet in the node you're running. But think of it as the "raw" interface to interact with your node, i.e. it's just providing the exposed RPCs and nothing else.

Hope my thoughts here are useful to you. Cheers!

**Comment by weezy20** [comment]
Well about point one, maybe I can agree with you. However it's quite weird that the same code, running on my Macbook does indeed display a file input field, however the screenshot I posted in the original feedback was running the front-end from WSL and Windows Powershell. Both refused to display the Component which led me to create the issue. We can close this issue now. Thanks for your prompt input.
