### ISSUE TITLE
Feedback Submission - docs - Smart Contract Toolkits - /v3/runtime/smart-contracts

### ISSUE THREAD

**Issue by jackyjia** [substrate-developer-hub/substrate-docs#610]
### What browsers are you seeing the problem on?

Chrome

### Feedback

1. ```Sandbox: A contract is not able to modify core blockchain storage or the storage of other contracts directly. It's power is limited to only modifying it's own state, and the ability to make outside calls to other contracts or runtime functions.```: typo, both __it's__ should be __its__
1. ```You can even brick your chain```: brick->break?

**Comment by sacha-l** [comment]
Thanks @jackyjia! Made the fix. The use of the word "brick" is intended though. It's like saying" stall your chain, where blocks are stalling. 🧱
