### ISSUE TITLE
Add a close button on the Substrate StackExchange msg overlay

### ISSUE THREAD

**Issue by jimmychu0807** [substrate-developer-hub/substrate-docs#612]
### What browsers are you seeing the problem on?

Chrome

### Bug report for the website

Can we add a close button on the Substrate StackExchange msg overlay on Substrate? It is pretty annoying and couldn't close it. Yes I know scrolling the screen down will make it disappear.

Also, once closed, I would suggest make the message don't popup again for that session. (So it is fine to have the overlay appears again when the window/tab is closed and reopen again).

### Steps to reproduce the problem

Goto https://docs.substrate.io

**Comment by NukeManDan** [comment]
agreed, this has  been voiced to me a few times more than this too. perhaps replacing the scroll behavior. but also maybe returning after say 15 minutes or something if navigating to a new page?

@je-boska @imadarai can you help?

**Comment by imadarai** [comment]
Closed with feature update on #697

**Comment by jimmychu0807** [comment]
Very Cool @imadarai . Thanks for that.
