### ISSUE TITLE
Feedback Submission - docs - SS58 Address Format - /v3/advanced/ss58

### ISSUE THREAD

**Issue by robinwei-itering** [substrate-developer-hub/substrate-docs#616]
### Feedback

I suppose the total length should be '35' instead of '34' in the last line of the table in the Section **Address Formats for Substrate**

**Comment by NukeManDan** [comment]
Good spot! I thought it was fixed here: https://github.com/substrate-developer-hub/substrate-docs/pull/466#discussion_r744614170

**Comment by NukeManDan** [comment]
Next time feel free to open a PR instead -  would love to have you as a contributor @robinwei-itering  :grin:
