### ISSUE TITLE
The StackExchange card is hidden, but interfering with the pages it's on

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-docs#632]
### What browsers are you seeing the problem on?

Other (please write below)

### Bug report for the website

I can't click on things or have the link to the SO site from the transparent card, it need to actually go to z=-1000 or somehow get out of your way!! 

### Steps to reproduce the problem

scroll down, card -> hidden
Try and hover over the same area.

**Comment by sacha-l** [comment]
Can attest to this too: seems like the Stack Exchange callout card just becomes transparent after scrolling down the page, but it's still actually there. You can easily test this by scrolling all the way down to the footer of any page in docs.substrate.io and trying to click on any of the socials buttons.
