### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by sadministrator** [substrate-developer-hub/substrate-docs#662]
### Broken Link

https://substrate.dev/docs/en/overview/low-level-data-format

### Expected Location

To a page in the Polkadot documentation explaining low-level SCALE encoding.

### Context and Origin

The broken link was included in this post: https://hackmd.io/@gavwood/r1jTRX2Zr in section 2:
"All block data is encoded using the basic SCALE codec described in detail [here](https://substrate.dev/docs/en/overview/low-level-data-format)."

**Comment by NukeManDan** [comment]
https://docs.substrate.io/reference/scale-codec/
