### ISSUE TITLE
Update the OS dependent dev enviroment instructions

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-docs#676]
It is unclear what is needed and redundant on the https://docs.substrate.io/v3/getting-started/installation/ page. Various issues crop up insisting non-reproducible Ubuntu problems for example #422  come around from time to time.

- [ ] Sync with devops / CI-CD team to understand what container use and why upstream for Substrate builds to inform this
- [ ] (optionally) #478 related CI workflow here to manually test (locally or otherwise) that all platforms work with the `latest` tagged base node template.
- [ ] ... more?

**Comment by NukeManDan** [comment]
openssl dependency was added again recently with the update of jsonrpc

**Comment by NukeManDan** [comment]
"if Debian/Ubuntu is the target rootfs, this could be handy: https://github.com/kpcyrd/cargo-debstatus "

**Comment by TriplEight** [comment]
Please check out [this](https://github.com/paritytech/substrate/tree/master/docs#613-docker) recently added option. I think it describes and has everything the beginning dev needs.

**Comment by NukeManDan** [comment]
I think the new https://docs.substrate.io/main-docs/install/ pages are OK for now. Will have a better overall rustdocs story in #678
