### ISSUE TITLE
Cumulus workshop - link to conversion of plain-chain-spec to raw-chain-spec

### ISSUE THREAD

**Issue by BenWhiteJam** [substrate-developer-hub/substrate-docs#683]
### Broken Link

https://docs.substrate.io/tutorials/v3/cumulus/start-relay/#convert-plain-to-raw-chain-spec

### Expected Location

https://docs.substrate.io/how-to-guides/v3/basics/custom-chain-spec/#3-generate-the-raw-chain-specification

### Context and Origin

I think the `conversion` link here https://docs.substrate.io/tutorials/v3/cumulus/start-relay/#pre-configured-chain-spec-files should link to the above mentioned in expected location or anywhere because it seems it doesn't link anywhere right now.

**Comment by NukeManDan** [comment]
https://docs.substrate.io/reference/how-to-guides/basics/customize-a-chain-specification/

https://docs.substrate.io/tutorials/connect-other-chains/local-relay/
