### ISSUE TITLE
[Tutorial: Start a private network] Missing option --scheme in step to add the aura and grandpa secret key

### ISSUE THREAD

**Issue by sanitu** [substrate-developer-hub/substrate-docs#685]
### Content request

The code to add the `aura` secret key in the **Allow other participants to join** section does not have the --scheme option. I get the error message that this option is required. So I had to add `--scheme Sr25519` to the code to add the aura secret key and `--scheme Ed25519` to the code to add the grandpa secret key.

Original code:

```
./target/release/node-template key insert --base-path /tmp/node02 \
--chain customSpecRaw.json \
--suri <second-participant-secret-seed> \
--password-interactive \
--key-type aura
```

Fixed code:

```
./target/release/node-template key insert --base-path /tmp/node02 \
--chain customSpecRaw.json \
--scheme Sr25519 \
--suri <second-participant-secret-seed> \
--password-interactive \
--key-type aura
```

### Are you willing to help with this request?

Yes!

**Comment by lisa-parity** [comment]
This issue has been fixed. For reference, see this issue:
https://github.com/substrate-developer-hub/substrate-docs/issues/714
