### ISSUE TITLE
Content Request: Chain Extensions, pallet->contract interactions

### ISSUE THREAD

**Issue by justinFrevert** [substrate-developer-hub/substrate-docs#693]
### Content request

[Chain Extensions](https://paritytech.github.io/ink-docs/macros-attributes/chain-extension) make up an extremely powerful feature for runtime developers in that they allow extension of runtime functions to ink! smart contract execution environments. Basically, extending a runtime function makes that function available to use within ink! smart contracts. I'm not aware of an equivalent concept in other ecosystems, at least in a way this can be done through configuration, rather than coding from scratch.

It's hard for me to articulate the value of chain extensions without an example. Imagine a scenario where a runtime developer has a runtime with some cool functionality, say in this case it's zk-like functions. This developer can then extend these functions to their smart contracts-layer. Now, smart contracts developers who are building for this chain can write smart contracts that make use of this extension to make zk-powered applications. 

I wrote a [user-facing example](https://github.com/justinFrevert/Runtime-Contract-Interactions) that demonstrates two related concepts:
1. Chain extensions
2. Calling smart contract functions from custom pallets(almost an inverse of chain extensions)

I think that with this code example in place, we can write a tutorial that uses it as a basis. I think that a tutorial would better argue the value of chain extensions than a single code example would. Such a tutorial should probably do a good job of providing a real-world scenario for applying a chain extension, to properly "wow" developers. 

### Are you willing to help with this request?

Yes!

**Comment by NukeManDan** [comment]
https://ink.substrate.io/macros-attributes/chain-extension is this sufficient? 

https://github.com/paritytech/ink-docs should have this issue instead if not :pray: 
Perhaps introducing your great example to them via an issue or PR is called for @justinFrevert !
