### ISSUE TITLE
Wrong path to Cargo.toml + lib.rs

### ISSUE THREAD

**Issue by a-nickol** [substrate-developer-hub/substrate-docs#701]
### Content request

In the tutorial "Add the Nicks Pallet to your Runtime" and the section "Adding Other FRAME Pallets" the path to `bin/node/runtime/Cargo.toml ` should be `runtime/Cargo.toml` and `bin/node/runtime/src/lib.rs` should be `runtime/src/lib.rs`.

### Are you willing to help with this request?

Yes!

**Comment by lisa-parity** [comment]
Actually, the path is correct but the information is a bit misleading. The runtime referred to in that section is the one built from the substrate repo instead of the dev hub node template.
Great catch, @a-nickol !
https://github.com/substrate-developer-hub/substrate-docs/pull/738
