### ISSUE TITLE
Inline text in Weights section

### ISSUE THREAD

**Issue by JosephKnecht-lab** [substrate-developer-hub/substrate-docs#702]
### Content request

Hi,

The Overview text in the weight section is inlined: https://docs.substrate.io/how-to-guides/v3/basics/weights/

One has to scroll to the left to read, and it's a bad user experience.

It should be an easy fix. 

Cheers

 

### Are you willing to help with this request?

Maybe (please elaborate above)

**Comment by lisa-parity** [comment]
Hi @JosephKnecht-lab, it looks like this is fixed to me.
Are you still seeing an issue?
Are you viewing doc on a mobile device?

**Comment by JosephKnecht-lab** [comment]
Hi Lisa... The issue seems to fixed now. 

I was viewing it in chrome on mac m1.
