### ISSUE TITLE
Opts missing while adding secret key

### ISSUE THREAD

**Issue by oneforalone** [substrate-developer-hub/substrate-docs#703]
### Content request

In section [`Add keys to the keystore`](https://docs.substrate.io/tutorials/v3/private-network/#add-keys-to-the-keystore), adding secret key command miss an argument: `--scheme`, otherwise the command would report an error:

```bash
error: The following required arguments were not provided:
    --scheme <SCHEME>
```

The fix for `aura` is:
```bash
./target/release/node-template key insert --base-path /tmp/node01 \
--chain customSpecRaw.json \
--suri <your-secret-seed> \
--password-interactive \
--key-type aura
--scheme Sr25519
```
and for `grandpa` is:
```bash
./target/release/node-template key insert --base-path /tmp/node01 \
--chain customSpecRaw.json \
--suri <your-secret-key> \
--password-interactive \
--key-type gran
--scheme Ed25519
```

### Are you willing to help with this request?

Yes!

**Comment by lisa-parity** [comment]
Looks like it is fixed.
![image](https://user-images.githubusercontent.com/92225469/148423145-0067f84f-51c2-44f5-82b4-690bc18b4136.png)

![image](https://user-images.githubusercontent.com/92225469/148423080-2ace591e-6712-4d30-886d-7cd6eb6b4648.png)
