### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by weezy20** [substrate-developer-hub/substrate-docs#704]
### Broken Link

https://doc.deepernetwork.org/rustdocs/latest/pallet_balances/struct.GenesisConfig.html

### Expected Location

https://docs.substrate.io/rustdocs/latest/pallet_balances/pallet/struct.GenesisConfig.html

### Context and Origin

https://doc.deepernetwork.org/how-to-guides/v3/basics/genesis/

**Comment by sacha-l** [comment]
Thanks for filing this issue @weezy20, but we aren't the maintainers of the content of origin. Please file an issue there. Cheers
