### ISSUE TITLE
Add Section on Parachain Block Times

### ISSUE THREAD

**Issue by wpank** [substrate-developer-hub/substrate-docs#706]
### Content request

A section should be added discussing a standard config and setup parachains should do for setting block times. Right now this should be 12 seconds. If they set it any lower (something like 6  seconds), they will have authors missing their slots. It's also the case that after a target block time is set, it's very hard to change. If a team solely changes it in their runtime, the next runtime upgrade will brick their chain. There should be an explicit warning about this.

### Are you willing to help with this request?

Maybe (please elaborate above)

**Comment by NukeManDan** [comment]
https://docs.substrate.io/reference/how-to-guides/parachains/prepare-to-launch/#critical-parachain-constraints is not ideal, but it does cover this. You agree? Open to a PR to improve as you see fit for sure :pray:
