### ISSUE TITLE
Attribute 'pallet::generate_storage_info' causing issues in proof-of-existence tutorial

### ISSUE THREAD

**Issue by angelolovatto** [substrate-developer-hub/substrate-docs#716]
### Content request

In the [Set up scaffolding for your pallet](https://docs.substrate.io/tutorials/v3/proof-of-existence/#set-up-scaffolding-for-your-pallet) section of the 'Build a proof of existence dApp' tutorial, the following lines are to be included
```rust
    // ...
    #[pallet::generate_store(pub(super) trait Store)]
    #[pallet::generate_storage_info]
    pub struct Pallet<T>(_);

```
However, running the compilation check later in the tutorial yields the error
```
➜  substrate-node-template git:(pallet-building) cargo check -p node-template-runtime
    Checking sp-std v4.0.0-dev (https://github.com/paritytech/substrate.git?tag=monthly-2021-11-1#352c46a6)
   Compiling node-template-runtime v4.0.0-dev (/Users/angelolovatto/Repositories/cloned/substrate-node-template/runtime)
    Checking pallet-template v4.0.0-dev (/Users/angelolovatto/Repositories/cloned/substrate-node-template/pallets/template)
error[E0277]: the trait bound `Vec<u8>: MaxEncodedLen` is not satisfied
  --> pallets/template/src/lib.rs:43:12
   |
43 |     #[pallet::generate_storage_info]
   |               ^^^^^^^^^^^^^^^^^^^^^ the trait `MaxEncodedLen` is not implemented for `Vec<u8>`
   |
   = note: required because of the requirements on the impl of `StorageInfoTrait` for `frame_support::pallet_prelude::StorageMap<_GeneratedPrefixForStorageProofs<T>, frame_support::Blake2_128Concat, Vec<u8>, (<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), frame_support::pallet_prelude::ValueQuery>`
note: required by `storage_info`
  --> /Users/angelolovatto/.cargo/git/checkouts/substrate-7e08433d4c370a21/352c46a/frame/support/src/traits/storage.rs:71:2
   |
71 |     fn storage_info() -> Vec<StorageInfo>;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0277`.
error: could not compile `pallet-template` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
```
Removing the attribute `#[pallet::generate_storage_info]` solves this. Plus, I've checked that the [template solution](https://github.com/substrate-developer-hub/substrate-node-template/blob/tutorials/solutions/proof-of-existence/pallets/template/src/lib.rs#L37-L39) does not have this attribute.

I can open a PR removing the attribute from the tutorial page if you agree that it isn't necessary.

### Are you willing to help with this request?

Yes!

**Comment by sacha-l** [comment]
Hi there @angelolovatto ! Have you tried refreshing your browser ? I think this has been resolved already. Please let me know if I'm missing something.

**Comment by angelolovatto** [comment]
Hi @sacha-l ! You're right, I've checked it now and the `#[pallet::generate_storage_info]` isn't there anymore. Thanks!
