### ISSUE TITLE
Code snip in substrate kitties tutorial doesn't compile

### ISSUE THREAD

**Issue by weezy20** [substrate-developer-hub/substrate-docs#718]
### Content request

```
construct_runtime!(
    // --snip
    {
        // --snip
        SubstrateKitties: pallet_kitties,
    }
);
```
On the substrate kitties tutorial doesn't compile with a bunch of errors. Please make the relevant changes for us beginners, Thanks! So far using 
```
SubstrateKitties: pallet_kitties::{Pallet, Storage, Call, Event<T>},
```
works but the dispatchable calls don't show up on the extrinsics page.

### Are you willing to help with this request?

Yes!

**Comment by sacha-l** [comment]
Correct me if I'm wrong but it seems like you're using a node template that's tagged to a monthly that's `monthly-2021-10` or less. Please let me know :)

**Comment by weezy20** [comment]
Hey sorry for the late reply. Indeed it is monthly-2021-10.
