### ISSUE TITLE
Yarn start error in "create-your-first-substrate-chain" tutorial

### ISSUE THREAD

**Issue by Medvind2140** [substrate-developer-hub/substrate-docs#743]
### What browsers are you seeing the problem on?

Firefox, Chrome

### Bug report for the website

Running yarn start will produce this error:
"digital envelope routines::unssupported"
![Screenshot 2022-01-08 at 10 33 20](https://user-images.githubusercontent.com/36833016/148643606-1fd5539f-fe2b-4522-a846-5f6d7d79f1ec.png)
 

### Steps to reproduce the problem

Follow the tutorial, run the "substrate-node-template" as described. When bulding and running the "substrate-front-end-template" errors occur during the yarn install and start.

**Comment by Medvind2140** [comment]
The fix is to add
export NODE_OPTIONS=--openssl-legacy-provider

**Comment by jimmychu0807** [comment]
@Medvind2140 
Thanks for reporting the issue. Indeed this is due to Node update in v17, as explained in [this blog post](https://medium.com/the-node-js-collection/node-js-17-is-here-8dba1e14e382).

But for now I choose to support only the latest LTS node version, v16.
