### ISSUE TITLE
[kitties-tutorial] File not found for module `mock` and `tests`

### ISSUE THREAD

**Issue by 04637** [substrate-developer-hub/substrate-docs#747]
https://docs.substrate.io/tutorials/v3/kitties/pt1/#set-a-price-for-each-kitty
This helper file in the tutorial is wrong.
```
error[E0583]: file not found for module `mock`
 --> pallets\kitties\src\lib.rs:5:1
  |
5 | mod mock;
  | ^^^^^^^^^
  |
  = help: to create the module `mock`, create file "pallets\kitties\src\mock.rs" or "pallets\kitties\src\mock\mod.rs"

error[E0583]: file not found for module `tests`
 --> pallets\kitties\src\lib.rs:6:1
  |
6 | mod tests;
  | ^^^^^^^^^^
  |
  = help: to create the module `tests`, create file "pallets\kitties\src\tests.rs" or "pallets\kitties\src\tests\mod.rs"
```

**Comment by 04637** [comment]
I fixed it in this pr, please review.
https://github.com/substrate-developer-hub/substrate-docs/pull/748#issue-1097655276

**Comment by sacha-l** [comment]
Thanks @04637 for taking action on this here. Much appreciated ! 🙏🏻  

If you're curious, you can find the tests (and mock runtime) in [the solution](https://github.com/substrate-developer-hub/substrate-node-template/blob/tutorials/solutions/kitties/pallets/kitties/src/tests.rs) for this tutorial. 😃
