### ISSUE TITLE
[Tutorial:private-network] Key insert missed arguments: --scheme <SCHEME>

### ISSUE THREAD

**Issue by 04637** [substrate-developer-hub/substrate-docs#758]
https://docs.substrate.io/tutorials/v3/private-network/#enable-other-participants-to-join
Step 5 and Step 6, need add --scheme

**Comment by 04637** [comment]
Plese review this pr. #759 @sacha-l

**Comment by sacha-l** [comment]
This is correct, thanks for the contribution @04637 🙏🏻
