### ISSUE TITLE
Incorrect markdown in tutorials/v3/kitties/pt2/

### ISSUE THREAD

**Issue by PoisonPhang** [substrate-developer-hub/substrate-docs#779]
### Content request

The first part of kitties/pt2/#create-kittiesjs contains a code block that contains documentation that looks as though it should be outside of the code block.

### Are you willing to help with this request?

Yes!

**Comment by sacha-l** [comment]
Thanks for offering your help @PoisonPhang. I'm not sure what you mean exactly, could you link this issue to a follow-up PR suggesting a fix? Thanks!

**Comment by PoisonPhang** [comment]
Hi, @sacha-l, it looks like this was resolved in 1be991ddb084172e4b95adc190857e5120c54b8a
I'll go ahead and close this.
Thanks
