### ISSUE TITLE
ink! Contracts Workshop: problem uploading contract

### ISSUE THREAD

**Issue by 0xangelo** [substrate-developer-hub/substrate-docs#789]
### What browsers are you seeing the problem on?

Brave

### Feedback

I'm trying to follow part 1 of the workshop but I keep running into the following issue. On the [Upload Contract Code](https://docs.substrate.io/tutorials/v3/ink-workshop/pt1/#1-upload-contract-code) step, I get the following error upon uploading `flipper.contract` to the hosted version of Canvas UI:
![Screen Shot 2022-01-21 at 08 38 19](https://user-images.githubusercontent.com/12701614/150581190-1f3972cb-8290-44ca-9fb8-a0bc5a24620d.png)

Checking the developer console in the Brave browser, I see the following errors
![Screen Shot 2022-01-21 at 08 38 44](https://user-images.githubusercontent.com/12701614/150581254-27f0605a-f6e7-40df-bf65-94520760c8a5.png)
This is preventing me from progressing further in the tutorial. I also tried Chrome, but the same issue shows. I've checked that `cargo +nightly contract build` runs without errors and all tests pass.

Any ideas on what I could be doing wrong?

**Comment by sulnong** [comment]
i met same problem
Last Saturday, i build example flipper project, it works well
But today i rebuild it, then upload contract caught same error

Previous flipper.contract is `language":"ink! 3.0.0-rc7`
Today's flipper.contract is `language":"ink! 3.0.0-rc8`
