### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by mishalalex** [substrate-developer-hub/substrate-docs#794]
### Broken Link

https://substrate.dev/substrate-front-end-template/

### Expected Location

Github

### Context and Origin

I wanted to see the UI of the frontend application but it threw 404 error

**Comment by sacha-l** [comment]
Hi @mishalalex - where did you originally stumble upon this link?

**Comment by mishalalex** [comment]
> Hi @mishalalex - where did you originally stumble upon this link?

I am not sure; the day I raised it while going through the docs I guess

**Comment by NukeManDan** [comment]
https://substrate-developer-hub.github.io/substrate-front-end-template/ is found in the readme, it _may_ have been a redirect missfire. Please use the hosted version here, but really locally deploying is the way to go :rocket:
