### ISSUE TITLE
Add the Nicks Pallet to your Runtime - Node build error

### ISSUE THREAD

**Issue by ItFlyingStart** [substrate-developer-hub/substrate-docs#795]
### What browsers are you seeing the problem on?

Other (please write below)

### Bug report for the website

- OS: Ubuntu 21.04
- Local development VM

### Steps to reproduce the problem

- Tutorial: Add the Nicks Pallet to your Runtime
- Step: Implement the Nicks pallet Config trait > Step nr. 6 > Build error

I have followed the steps in the tutorial, but I get the next build error:

33 |     pub fn spawn_blocking(
    |            ^^^^^^^^^^^^^^

error[E0061]: this function takes 3 arguments but 2 arguments were supplied
   --> node/src/service.rs:330:41
    |
330 |         task_manager.spawn_essential_handle().spawn_blocking(
    |                                               ^^^^^^^^^^^^^^ expected 3 arguments
331 |             "grandpa-voter",
    |             ---------------
332 |             sc_finality_grandpa::run_grandpa_voter(grandpa_config)?,
    |             ------------------------------------------------------- supplied 2 arguments

Please help.

**Comment by hkvongit** [comment]
I have also faced the same issue but found a temporary fix. please check the command on issue #792 .

**Comment by ItFlyingStart** [comment]
> I have also faced a similar issue but found a temporary fix. please check the command on issue #792 and [fix](https://github.com/substrate-developer-hub/substrate-docs/issues/792#issuecomment-1020477839).

Ok thanks for your feedback. I will close this issue because it is duplicate.

**Comment by hkvongit** [comment]
> > I have also faced a similar issue but found a temporary fix. please check the command on issue #792 and [fix](https://github.com/substrate-developer-hub/substrate-docs/issues/792#issuecomment-1020477839).
> 
> Ok thanks for your feedback. I will close this issue because it is duplicate.

Thanks @ItFlyingStart
