### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by guzzit** [substrate-developer-hub/substrate-docs#798]
### Broken Link

https://docs.substrate.io/rustdocs/latest/pallet_scheduler/trait.Config.html#associatedtype.ScheduleOrigin

### Context and Origin

It was found under the 'Upgrade the Runtime' section here:
https://docs.substrate.io/tutorials/v3/forkless-upgrades/#schedule-an-upgrade

**Comment by sacha-l** [comment]
Thanks for flagging this too @guzzit - fixed now.
