### ISSUE TITLE
Broken links in Storage docs & Cumulus tutorial

### ISSUE THREAD

**Issue by Imod7** [substrate-developer-hub/substrate-docs#825]
### Broken Link

1) This is a broken link
https://docs.substrate.io/rustdocs/latest/pallet_utility/trait.Config.html#associatedtype.MaxSignatories
which is located in the [Storage docs > create bounds section](https://docs.substrate.io/v3/runtime/storage/#create-bounds) 

2) Also, in the [Cumulus tutorial > pre-configured-chain-spec-files section](https://docs.substrate.io/tutorials/v3/cumulus/start-relay/#pre-configured-chain-spec-files) the link **_conversion_** links to https://docs.substrate.io/tutorials/v3/cumulus/start-relay/#convert-plain-to-raw-chain-spec but there is no corresponding section called "convert plain to raw chain spec" so it does not do anything.

3) In the [Cumulus tutorial > pre-configured-chain-spec-files section](https://docs.substrate.io/tutorials/v3/cumulus/start-relay/#pre-configured-chain-spec-files) the text **_create your own chain spec_** links to https://docs.substrate.io/tutorials/v3/cumulus/start-relay/#create-a-custom-relay-chain-spec-optional but there is no corresponding section called "create a custom relay chain spec optional" so it does not do anything.

4) In the [Cumulus tutorial > Registration Transaction section](https://docs.substrate.io/tutorials/v3/cumulus/connect-parachain/#registration-transaction) the text **_paraID being reserved_** links to https://docs.substrate.io/tutorials/v3/cumulus/connect-parachain/#1-reserve-a-para-id which does not do anything.

### Expected Location

1) Regarding the first broken link, I would guess/expect (mainly because of consistency reasons) that it would point where the first [instance](https://docs.substrate.io/v3/runtime/storage/#verify-first-write-last) of the phrase **_the multi-signature capabilities from the Utility pallet_** points at which is the link https://docs.substrate.io/rustdocs/latest/pallet_utility/pallet/enum.Call.html#variant.as_multi
However, this link refers to the variant `as_multi` which is not present in the docs of the `Utility pallet` nor in the actual pallet itself. So I would guess that also the first [link](https://docs.substrate.io/v3/runtime/storage/#verify-first-write-last) is not very reliable and needs to be reviewed.

2) Regarding the word **_conversion_** not sure where it should link to.

3) I think this link should point [here](https://docs.substrate.io/tutorials/v3/private-network/#create-a-custom-chain-specification).

4) I think this link should point [here](https://docs.substrate.io/tutorials/v3/cumulus/connect-parachain/#reserve-a-para-id)

**Comment by sacha-l** [comment]
Thank you for flagging this @Imod7 ! I'll follow up with a PR to fix these.
