### ISSUE TITLE
Old workshop link goes nowhere when ending with #

### ISSUE THREAD

**Issue by statictype** [substrate-developer-hub/substrate-docs#834]
### Broken Link

https://substrate.dev/substrate-contracts-workshop/#/ 

### Expected Location

https://docs.substrate.io/tutorials/v3/ink-workshop/pt1/

### Context and Origin

I suppose it was a hash router before and some websites still link to the full URL. The new router can't handle hashes.

Got it from here https://morioh.com/p/0e444b63ab48, but it might be more wide spread.

**Comment by NukeManDan** [comment]
This redirects just fine for me. Please check behavior again

**Comment by statictype** [comment]
<img width="1677" alt="Screenshot 2022-03-03 at 17 25 25" src="https://user-images.githubusercontent.com/42985153/156607242-fcf2dc6c-2cdc-4fd4-8a5c-874f681267fd.png">

this is what I still see using google chrome
