### ISSUE TITLE
Debug `print` function should be `print!`

### ISSUE THREAD

**Issue by ltfschoen** [substrate-developer-hub/substrate-docs#838]
### What browsers are you seeing the problem on?

Other (please write below)
Brave

### Bug report for the website

I think all examples that use `print` function at https://docs.substrate.io/v3/runtime/debugging/ should be using `print!` (with a bang character) instead

### Steps to reproduce the problem

In the Substrate Debugging deocumentation here https://docs.substrate.io/v3/runtime/debugging/

It says that we can use Substrate's `print` function with
```
print("My Test Message");
```

But if I do that I get error
```
error[E0423]: expected function, found macro `print`
  --> node/src/chain_spec.rs:51:5
   |
51 |     print("My Test Message");
   |     ^^^^^ not a function
```

Whereas if I use a bang character by changing it to `print!("My Test Message");` then it works

**Comment by NukeManDan** [comment]
https://github.com/substrate-developer-hub/substrate-docs/pull/869
