### ISSUE TITLE
Code in the tutorial not working as instructed

### ISSUE THREAD

**Issue by Waleedzkhan** [substrate-developer-hub/substrate-docs#859]
### Bug report for the website

I am trying to follow the tutorial at  https://docs.substrate.io/tutorials/v3/proof-of-existence/ and I get the following errors

cargo check -p node-template-runtime                                                         Compiling node-template-runtime v4.0.0-dev (E:\Dev\BlockChain\Substrate\proof-of-existense\substrate-node-template\runtime)
    Checking pallet-template v4.0.0-dev (E:\Dev\BlockChain\Substrate\proof-of-existense\substrate-node-template\pallets\template)
error[E0599]: the function or associated item `contains_key` exists for struct `frame_support::pallet_prelude::StorageMap<_GeneratedPrefixForStorageProofs<T>, frame_support::Blake2_128Concat, Vec<u8>, (<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), frame_support::pallet_prelude::ValueQuery>`, but its trait bounds were not satisfied
   --> pallets\template\src\lib.rs:61:31
    |
61  |         ensure!(!Proofs::<T>::contains_key(&proof), Error::<T>::ProofAlreadyClaimed);
    |                               ^^^^^^^^^^^^ function or associated item cannot be called on `frame_support::pallet_prelude::StorageMap<_GeneratedPrefixForStorageProofs<T>, frame_support::Blake2_128Concat, Vec<u8>, (<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), frame_support::pallet_prelude::ValueQuery>` due to unsatisfied trait bounds
    |
   ::: C:\Users\Waleed\.cargo\git\checkouts\substrate-7e08433d4c370a21\22d40c7\frame\support\src\storage\types\mod.rs:89:1
    |
89  | pub struct ValueQuery;
    | ---------------------- doesn't satisfy `_: QueryKindTrait<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), GetDefault>`     
    |
   ::: C:\Users\Waleed\.cargo\git\checkouts\substrate-7e08433d4c370a21\22d40c7\frame\support\src\traits\misc.rs:420:1
    |
420 | pub struct GetDefault;
    | ---------------------- doesn't satisfy `_: frame_support::traits::Get<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber)>`     
    |
    = note: the following trait bounds were not satisfied:
            `frame_support::pallet_prelude::ValueQuery: QueryKindTrait<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), GetDefault>`
            `GetDefault: frame_support::traits::Get<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber)>`

error[E0599]: the function or associated item `insert` exists for struct `frame_support::pallet_prelude::StorageMap<_GeneratedPrefixForStorageProofs<T>, frame_support::Blake2_128Concat, Vec<u8>, (<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), frame_support::pallet_prelude::ValueQuery>`, but its trait bounds were not satisfied
   --> pallets\template\src\lib.rs:67:22
    |
67  |         Proofs::<T>::insert(&proof, (&sender, current_block));
    |                      ^^^^^^ function or associated item cannot be called on `frame_support::pallet_prelude::StorageMap<_GeneratedPrefixForStorageProofs<T>, frame_support::Blake2_128Concat, Vec<u8>, (<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), frame_support::pallet_prelude::ValueQuery>` due to unsatisfied trait bounds
    |
   ::: C:\Users\Waleed\.cargo\git\checkouts\substrate-7e08433d4c370a21\22d40c7\frame\support\src\storage\types\mod.rs:89:1
    |
89  | pub struct ValueQuery;
    | ---------------------- doesn't satisfy `_: QueryKindTrait<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), GetDefault>`
    |
   ::: C:\Users\Waleed\.cargo\git\checkouts\substrate-7e08433d4c370a21\22d40c7\frame\support\src\traits\misc.rs:420:1
    |
420 | pub struct GetDefault;
    | ---------------------- doesn't satisfy `_: frame_support::traits::Get<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber)>`     
    |
    = note: the following trait bounds were not satisfied:
            `frame_support::pallet_prelude::ValueQuery: QueryKindTrait<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), GetDefault>`
            `GetDefault: frame_support::traits::Get<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber)>`

error[E0599]: the function or associated item `contains_key` exists for struct `frame_support::pallet_prelude::StorageMap<_GeneratedPrefixForStorageProofs<T>, frame_support::Blake2_128Concat, Vec<u8>, (<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), frame_support::pallet_prelude::ValueQuery>`, but its trait bounds were not satisfied
   --> pallets\template\src\lib.rs:86:30
    |
86  |         ensure!(Proofs::<T>::contains_key(&proof), Error::<T>::NoSuchProof);
    |                              ^^^^^^^^^^^^ function or associated item cannot be called on `frame_support::pallet_prelude::StorageMap<_GeneratedPrefixForStorageProofs<T>, frame_support::Blake2_128Concat, Vec<u8>, (<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), frame_support::pallet_prelude::ValueQuery>` due to unsatisfied trait bounds
    |
   ::: C:\Users\Waleed\.cargo\git\checkouts\substrate-7e08433d4c370a21\22d40c7\frame\support\src\storage\types\mod.rs:89:1
    |
89  | pub struct ValueQuery;
    | ---------------------- doesn't satisfy `_: QueryKindTrait<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), GetDefault>`     
    |
   ::: C:\Users\Waleed\.cargo\git\checkouts\substrate-7e08433d4c370a21\22d40c7\frame\support\src\traits\misc.rs:420:1
    |
420 | pub struct GetDefault;
    | ---------------------- doesn't satisfy `_: frame_support::traits::Get<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber)>`     
    |
    = note: the following trait bounds were not satisfied:
            `frame_support::pallet_prelude::ValueQuery: QueryKindTrait<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), GetDefault>`
            `GetDefault: frame_support::traits::Get<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber)>`

error[E0599]: the function or associated item `get` exists for struct `frame_support::pallet_prelude::StorageMap<_GeneratedPrefixForStorageProofs<T>, frame_support::Blake2_128Concat, Vec<u8>, (<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), frame_support::pallet_prelude::ValueQuery>`, but its trait bounds were not satisfied
   --> pallets\template\src\lib.rs:89:39
    |
89  |         let (owner, _) = Proofs::<T>::get(&proof);
    |                                       ^^^ function or associated item cannot be called on `frame_support::pallet_prelude::StorageMap<_GeneratedPrefixForStorageProofs<T>, frame_support::Blake2_128Concat, Vec<u8>, (<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), frame_support::pallet_prelude::ValueQuery>` due to unsatisfied trait bounds
    |
   ::: C:\Users\Waleed\.cargo\git\checkouts\substrate-7e08433d4c370a21\22d40c7\frame\support\src\storage\types\mod.rs:89:1
    |
89  | pub struct ValueQuery;
    | ---------------------- doesn't satisfy `_: QueryKindTrait<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), GetDefault>`     
    |
   ::: C:\Users\Waleed\.cargo\git\checkouts\substrate-7e08433d4c370a21\22d40c7\frame\support\src\traits\misc.rs:420:1
    |
420 | pub struct GetDefault;
    | ---------------------- doesn't satisfy `_: frame_support::traits::Get<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber)>`     
    |
    = note: the following trait bounds were not satisfied:
            `frame_support::pallet_prelude::ValueQuery: QueryKindTrait<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), GetDefault>`
            `GetDefault: frame_support::traits::Get<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber)>`

error[E0599]: the function or associated item `remove` exists for struct `frame_support::pallet_prelude::StorageMap<_GeneratedPrefixForStorageProofs<T>, frame_support::Blake2_128Concat, Vec<u8>, (<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), frame_support::pallet_prelude::ValueQuery>`, but its trait bounds were not satisfied
   --> pallets\template\src\lib.rs:95:22
    |
95  |         Proofs::<T>::remove(&proof);
    |                      ^^^^^^ function or associated item cannot be called on `frame_support::pallet_prelude::StorageMap<_GeneratedPrefixForStorageProofs<T>, frame_support::Blake2_128Concat, Vec<u8>, (<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), frame_support::pallet_prelude::ValueQuery>` due to unsatisfied trait bounds
    |
   ::: C:\Users\Waleed\.cargo\git\checkouts\substrate-7e08433d4c370a21\22d40c7\frame\support\src\storage\types\mod.rs:89:1
    |
89  | pub struct ValueQuery;
    | ---------------------- doesn't satisfy `_: QueryKindTrait<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), GetDefault>`     
    |
   ::: C:\Users\Waleed\.cargo\git\checkouts\substrate-7e08433d4c370a21\22d40c7\frame\support\src\traits\misc.rs:420:1
    |
420 | pub struct GetDefault;
    | ---------------------- doesn't satisfy `_: frame_support::traits::Get<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber)>`     
    |
    = note: the following trait bounds were not satisfied:
            `frame_support::pallet_prelude::ValueQuery: QueryKindTrait<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), GetDefault>`
            `GetDefault: frame_support::traits::Get<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber)>`

error[E0277]: the trait bound `Vec<u8>: MaxEncodedLen` is not satisfied
  --> pallets\template\src\lib.rs:37:15
   |
37 |     #[pallet::pallet]
   |               ^^^^^^ the trait `MaxEncodedLen` is not implemented for `Vec<u8>`
   |
   = note: required because of the requirements on the impl of `StorageInfoTrait` for `frame_support::pallet_prelude::StorageMap<_GeneratedPrefixForStorageProofs<T>, frame_support::Blake2_128Concat, Vec<u8>, (<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), frame_support::pallet_prelude::ValueQuery>`

error[E0277]: the trait bound `<T as frame_system::Config>::AccountId: std::default::Default` is not satisfied
  --> pallets\template\src\lib.rs:37:15
   |
37 |     #[pallet::pallet]
   |               ^^^^^^ the trait `std::default::Default` is not implemented for `<T as frame_system::Config>::AccountId`
   |
   = note: required because of the requirements on the impl of `std::default::Default` for `(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber)`
   = note: required because of the requirements on the impl of `frame_support::traits::Get<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber)>` for `GetDefault`
   = note: required because of the requirements on the impl of `QueryKindTrait<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), GetDefault>` for `frame_support::pallet_prelude::ValueQuery`
   = note: required because of the requirements on the impl of `StorageInfoTrait` for `frame_support::pallet_prelude::StorageMap<_GeneratedPrefixForStorageProofs<T>, frame_support::Blake2_128Concat, Vec<u8>, (<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), frame_support::pallet_prelude::ValueQuery>`
help: consider further restricting the associated type
   |
37 |     #[pallet::pallet where <T as frame_system::Config>::AccountId: std::default::Default]
   |                      +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

error[E0277]: the trait bound `<T as frame_system::Config>::AccountId: std::default::Default` is not satisfied
  --> pallets\template\src\lib.rs:41:12
   |
41 |     #[pallet::storage]
   |               ^^^^^^^ the trait `std::default::Default` is not implemented for `<T as frame_system::Config>::AccountId`
   |
   = note: required because of the requirements on the impl of `std::default::Default` for `(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber)`
   = note: required because of the requirements on the impl of `frame_support::traits::Get<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber)>` for `GetDefault`
   = note: required because of the requirements on the impl of `QueryKindTrait<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), GetDefault>` for `frame_support::pallet_prelude::ValueQuery`
   = note: required because of the requirements on the impl of `StorageEntryMetadataBuilder` for `frame_support::pallet_prelude::StorageMap<_GeneratedPrefixForStorageProofs<T>, frame_support::Blake2_128Concat, Vec<u8>, (<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), frame_support::pallet_prelude::ValueQuery>`

Some errors have detailed explanations: E0277, E0599.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `pallet-template` due to 8 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed
PS E:\Dev\BlockChain\Substrate\proof-of-existense\substrate-node-template> cargo check -p node-template-runtime
   Compiling node-template-runtime v4.0.0-dev (E:\Dev\BlockChain\Substrate\proof-of-existense\substrate-node-template\runtime)
    Checking pallet-template v4.0.0-dev (E:\Dev\BlockChain\Substrate\proof-of-existense\substrate-node-template\pallets\template)
error[E0599]: the function or associated item `contains_key` exists for struct `frame_support::pallet_prelude::StorageMap<_GeneratedPrefixForStorageProofs<T>, frame_support::Blake2_128Concat, Vec<u8>, (<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), frame_support::pallet_prelude::ValueQuery>`, but its trait bounds were not satisfied
   --> pallets\template\src\lib.rs:61:31
    |
61  |         ensure!(!Proofs::<T>::contains_key(&proof), Error::<T>::ProofAlreadyClaimed);
    |                               ^^^^^^^^^^^^ function or associated item cannot be called on `frame_support::pallet_prelude::StorageMap<_GeneratedPrefixForStorageProofs<T>, frame_support::Blake2_128Concat, Vec<u8>, (<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), frame_support::pallet_prelude::ValueQuery>` due to unsatisfied trait bounds
    |
   ::: C:\Users\Waleed\.cargo\git\checkouts\substrate-7e08433d4c370a21\22d40c7\frame\support\src\storage\types\mod.rs:89:1
    |
89  | pub struct ValueQuery;
    | ---------------------- doesn't satisfy `_: QueryKindTrait<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), GetDefault>`     
    |
   ::: C:\Users\Waleed\.cargo\git\checkouts\substrate-7e08433d4c370a21\22d40c7\frame\support\src\traits\misc.rs:420:1
    |
420 | pub struct GetDefault;
    | ---------------------- doesn't satisfy `_: frame_support::traits::Get<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber)>`     
    |
    = note: the following trait bounds were not satisfied:
            `frame_support::pallet_prelude::ValueQuery: QueryKindTrait<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), GetDefault>`
            `GetDefault: frame_support::traits::Get<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber)>`

error[E0599]: the function or associated item `insert` exists for struct `frame_support::pallet_prelude::StorageMap<_GeneratedPrefixForStorageProofs<T>, frame_support::Blake2_128Concat, Vec<u8>, (<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), frame_support::pallet_prelude::ValueQuery>`, but its trait bounds were not satisfied
   --> pallets\template\src\lib.rs:67:22
    |
67  |         Proofs::<T>::insert(&proof, (&sender, current_block));
    |                      ^^^^^^ function or associated item cannot be called on `frame_support::pallet_prelude::StorageMap<_GeneratedPrefixForStorageProofs<T>, frame_support::Blake2_128Concat, Vec<u8>, (<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), frame_support::pallet_prelude::ValueQuery>` due to unsatisfied trait bounds
    |
   ::: C:\Users\Waleed\.cargo\git\checkouts\substrate-7e08433d4c370a21\22d40c7\frame\support\src\storage\types\mod.rs:89:1
    |
89  | pub struct ValueQuery;
    | ---------------------- doesn't satisfy `_: QueryKindTrait<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), GetDefault>`     
    |
   ::: C:\Users\Waleed\.cargo\git\checkouts\substrate-7e08433d4c370a21\22d40c7\frame\support\src\traits\misc.rs:420:1
    |
420 | pub struct GetDefault;
    | ---------------------- doesn't satisfy `_: frame_support::traits::Get<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber)>`     
    |
    = note: the following trait bounds were not satisfied:
            `frame_support::pallet_prelude::ValueQuery: QueryKindTrait<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), GetDefault>`
            `GetDefault: frame_support::traits::Get<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber)>`

error[E0599]: the function or associated item `contains_key` exists for struct `frame_support::pallet_prelude::StorageMap<_GeneratedPrefixForStorageProofs<T>, frame_support::Blake2_128Concat, Vec<u8>, (<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), frame_support::pallet_prelude::ValueQuery>`, but its trait bounds were not satisfied
   --> pallets\template\src\lib.rs:86:30
    |
86  |         ensure!(Proofs::<T>::contains_key(&proof), Error::<T>::NoSuchProof);
    |                              ^^^^^^^^^^^^ function or associated item cannot be called on `frame_support::pallet_prelude::StorageMap<_GeneratedPrefixForStorageProofs<T>, frame_support::Blake2_128Concat, Vec<u8>, (<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), frame_support::pallet_prelude::ValueQuery>` due to unsatisfied trait bounds
    |
   ::: C:\Users\Waleed\.cargo\git\checkouts\substrate-7e08433d4c370a21\22d40c7\frame\support\src\storage\types\mod.rs:89:1
    |
89  | pub struct ValueQuery;
    | ---------------------- doesn't satisfy `_: QueryKindTrait<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), GetDefault>`     
    |
   ::: C:\Users\Waleed\.cargo\git\checkouts\substrate-7e08433d4c370a21\22d40c7\frame\support\src\traits\misc.rs:420:1
    |
420 | pub struct GetDefault;
    | ---------------------- doesn't satisfy `_: frame_support::traits::Get<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber)>`     
    |
    = note: the following trait bounds were not satisfied:
            `frame_support::pallet_prelude::ValueQuery: QueryKindTrait<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), GetDefault>`
            `GetDefault: frame_support::traits::Get<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber)>`

error[E0599]: the function or associated item `get` exists for struct `frame_support::pallet_prelude::StorageMap<_GeneratedPrefixForStorageProofs<T>, frame_support::Blake2_128Concat, Vec<u8>, (<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), frame_support::pallet_prelude::ValueQuery>`, but its trait bounds were not satisfied
   --> pallets\template\src\lib.rs:89:39
    |
89  |         let (owner, _) = Proofs::<T>::get(&proof);
    |                                       ^^^ function or associated item cannot be called on `frame_support::pallet_prelude::StorageMap<_GeneratedPrefixForStorageProofs<T>, frame_support::Blake2_128Concat, Vec<u8>, (<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), frame_support::pallet_prelude::ValueQuery>` due to unsatisfied trait bounds
    |
   ::: C:\Users\Waleed\.cargo\git\checkouts\substrate-7e08433d4c370a21\22d40c7\frame\support\src\storage\types\mod.rs:89:1
    |
89  | pub struct ValueQuery;
    | ---------------------- doesn't satisfy `_: QueryKindTrait<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), GetDefault>`     
    |
   ::: C:\Users\Waleed\.cargo\git\checkouts\substrate-7e08433d4c370a21\22d40c7\frame\support\src\traits\misc.rs:420:1
    |
420 | pub struct GetDefault;
    | ---------------------- doesn't satisfy `_: frame_support::traits::Get<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber)>`     
    |
    = note: the following trait bounds were not satisfied:
            `frame_support::pallet_prelude::ValueQuery: QueryKindTrait<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), GetDefault>`
            `GetDefault: frame_support::traits::Get<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber)>`

error[E0599]: the function or associated item `remove` exists for struct `frame_support::pallet_prelude::StorageMap<_GeneratedPrefixForStorageProofs<T>, frame_support::Blake2_128Concat, Vec<u8>, (<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), frame_support::pallet_prelude::ValueQuery>`, but its trait bounds were not satisfied
   --> pallets\template\src\lib.rs:95:22
    |
95  |         Proofs::<T>::remove(&proof);
    |                      ^^^^^^ function or associated item cannot be called on `frame_support::pallet_prelude::StorageMap<_GeneratedPrefixForStorageProofs<T>, frame_support::Blake2_128Concat, Vec<u8>, (<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), frame_support::pallet_prelude::ValueQuery>` due to unsatisfied trait bounds
    |
   ::: C:\Users\Waleed\.cargo\git\checkouts\substrate-7e08433d4c370a21\22d40c7\frame\support\src\storage\types\mod.rs:89:1
    |
89  | pub struct ValueQuery;
    | ---------------------- doesn't satisfy `_: QueryKindTrait<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), GetDefault>`     
    |
   ::: C:\Users\Waleed\.cargo\git\checkouts\substrate-7e08433d4c370a21\22d40c7\frame\support\src\traits\misc.rs:420:1
    |
420 | pub struct GetDefault;
    | ---------------------- doesn't satisfy `_: frame_support::traits::Get<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber)>`     
    |
    = note: the following trait bounds were not satisfied:
            `frame_support::pallet_prelude::ValueQuery: QueryKindTrait<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), GetDefault>`
            `GetDefault: frame_support::traits::Get<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber)>`

error[E0277]: the trait bound `Vec<u8>: MaxEncodedLen` is not satisfied
  --> pallets\template\src\lib.rs:37:15
   |
37 |     #[pallet::pallet]
   |               ^^^^^^ the trait `MaxEncodedLen` is not implemented for `Vec<u8>`
   |
   = note: required because of the requirements on the impl of `StorageInfoTrait` for `frame_support::pallet_prelude::StorageMap<_GeneratedPrefixForStorageProofs<T>, frame_support::Blake2_128Concat, Vec<u8>, (<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), frame_support::pallet_prelude::ValueQuery>`

error[E0277]: the trait bound `<T as frame_system::Config>::AccountId: std::default::Default` is not satisfied
  --> pallets\template\src\lib.rs:37:15
   |
37 |     #[pallet::pallet]
   |               ^^^^^^ the trait `std::default::Default` is not implemented for `<T as frame_system::Config>::AccountId`
   |
   = note: required because of the requirements on the impl of `std::default::Default` for `(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber)`
   = note: required because of the requirements on the impl of `frame_support::traits::Get<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber)>` for `GetDefault`
   = note: required because of the requirements on the impl of `QueryKindTrait<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), GetDefault>` for `frame_support::pallet_prelude::ValueQuery`
   = note: required because of the requirements on the impl of `StorageInfoTrait` for `frame_support::pallet_prelude::StorageMap<_GeneratedPrefixForStorageProofs<T>, frame_support::Blake2_128Concat, Vec<u8>, (<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), frame_support::pallet_prelude::ValueQuery>`
help: consider further restricting the associated type
   |
37 |     #[pallet::pallet where <T as frame_system::Config>::AccountId: std::default::Default]
   |                      +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

error[E0277]: the trait bound `<T as frame_system::Config>::AccountId: std::default::Default` is not satisfied
  --> pallets\template\src\lib.rs:41:12
   |
41 |     #[pallet::storage]
   |               ^^^^^^^ the trait `std::default::Default` is not implemented for `<T as frame_system::Config>::AccountId`
   |
   = note: required because of the requirements on the impl of `std::default::Default` for `(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber)`
   = note: required because of the requirements on the impl of `frame_support::traits::Get<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber)>` for `GetDefault`
   = note: required because of the requirements on the impl of `QueryKindTrait<(<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), GetDefault>` for `frame_support::pallet_prelude::ValueQuery`
   = note: required because of the requirements on the impl of `StorageEntryMetadataBuilder` for `frame_support::pallet_prelude::StorageMap<_GeneratedPrefixForStorageProofs<T>, frame_support::Blake2_128Concat, Vec<u8>, (<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), frame_support::pallet_prelude::ValueQuery>`

Some errors have detailed explanations: E0277, E0599.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `pallet-template` due to 8 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed

### Steps to reproduce the problem

Follow the tutorial after cloning git clone https://github.com/substrate-developer-hub/substrate-node-template and then git checkout latest

**Comment by Liu-WeiHu** [comment]
I encountered the same mistake in this chapter

**Comment by Waleedzkhan** [comment]
I tried running it with wsl on windows and it worked, powershell might be causing the issue.
