### ISSUE TITLE
PoE Tutorial to compile from step to step

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-docs#884]
> I would still prefer we start with a template which compiles from step to step. this could help someone realize there is an issue before getting too far into the tutorial 
> _Originally posted by @shawntabrizi in https://github.com/substrate-developer-hub/substrate-docs/pull/861#pullrequestreview-905083794_

This should not be too hard to implement, and the solution could be constructed with each commit for these steps. 
Possibly using a different base skeleton for the pallet template: https://sacha-l.github.io/collectables-ethdenver-workshop/#/setup

**Comment by lisa-parity** [comment]
Probably superseded by:
https://github.com/substrate-developer-hub/substrate-docs/pull/1352
