### ISSUE TITLE
Update Nicks-pallet dependency to new format

### ISSUE THREAD

**Issue by srinivasnarula** [substrate-developer-hub/substrate-docs#889]
### Content request

In Nicks-Pallet tutorial, when dependencies code (Listing 1.1) is used as per [documentation](https://docs.substrate.io/tutorials/v3/add-a-pallet/), it throwing below error (Listing 1.2)

![image](https://user-images.githubusercontent.com/2491903/157806361-483520a9-b3d0-46cf-950d-c152a7e171ef.png)
Listing 1.1

![image](https://user-images.githubusercontent.com/2491903/157805748-99f3de5d-df43-42ed-961c-9dd0202e5981.png)
Listing 1.2

So I modified format of nicks-pallet dependency as per the existing dependencies in toml.file Please refer Listing 1.3
![image](https://user-images.githubusercontent.com/2491903/157805973-1163f4ba-8f4c-4dfe-aa9c-e3f56ae4a23f.png)
Listing 1.3

I was able to compile using `cargo check -p node-template-runtime` then solution compiled successfully. Please refer Listing 1.4
![image](https://user-images.githubusercontent.com/2491903/157806075-85cdece1-0b27-4ed6-9593-04ba0b8cd4e0.png)
Listing 1.4

### Are you willing to help with this request?

Yes!

**Comment by NukeManDan** [comment]
you are mixing versions in 1.4 as you see, monthly and polkadot based. Ensure you use one version, the docs are very explicit maintained to make sure of this using the `latest` tag on the template
