### ISSUE TITLE
Unclear "Configure your node's chain spec"

### ISSUE THREAD

**Issue by AuroraLantean** [substrate-developer-hub/substrate-docs#911]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Content request

Where is a full example of this? 
Example link 1
[Node template 'chain_spec.rs'](https://github.com/substrate-developer-hub/substrate-node-template/blob/master/node/src/chain_spec.rs#L142-L144)
does not show pallet_something: PalletSomethingConfig {}, which is explained in the guide

Example link 2
[Example pallet GenesisConfig](https://docs.substrate.io/rustdocs/latest/src/pallet_example/lib.rs.html#607)
is an invalid link
please advise. thanks

### Are you willing to help with this request?

Maybe (please elaborate above)

**Comment by lisa-parity** [comment]
Hi @AuroraLantean, thanks for submitting an issue. Can you provide a little more context on where these issues are? Which guide are you referring to?
Is the problem in the chain specification itself or in documentation about the chain spec or both?
Thanks!

**Comment by NukeManDan** [comment]
Go ahead and reopen if you can provide more context & details :)
