### ISSUE TITLE
Glossary / trie (Patricia Merkle Tree)

### ISSUE THREAD

**Issue by trongdth** [substrate-developer-hub/substrate-docs#937]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### What browsers are you seeing the problem on?

Chrome

### Bug report for the website

There is a wrong typo in Glossary / trie (Patricia Merkle Tree). The right one is `retrieving` instead of `retireving` in the sentence `Because incremental changes to the data set result in a new hash, retireving data is efficient even if the data set is very large`

**Comment by lisa-parity** [comment]
Thanks for catching this!
