### ISSUE TITLE
Substrate Node Template Issue

### ISSUE THREAD

**Issue by AthenasNetwork** [substrate-developer-hub/substrate-docs#948]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Bug report for compiling, code snippets, templates, etc.

Hi guys, I have a question.

I went throught the "Create your first Substrate blochchain" tutorial.

I did everything and it worked great, except at the end.

When I connect to the Front end template I see that the balances column is blank.

Like, no of the accounts have any funds, including Alice.

And when I try to transfer I get this error: "Transaction Failed: Error: Unable to decode storage system.account: entry 0:: createType(AccountInfo):: {"nonce":"Index","consumers":"RefCount","providers":"RefCount","sufficients":"RefCount","data":"AccountData"}:: Decoded input doesn't match input, received 0x0000000000000000000000000000001000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (72 bytes), created 0x0000000000000000000000000000001000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (80 bytes)".

How can I fix it? Thanks.

### Steps to reproduce the problem

I went throught the tutorial and got this error.

**Comment by NukeManDan** [comment]
I cannot reproduce using the preset `latest` templates. Please try with this? `polkadot-v0.9.19` release of substrate.
