### ISSUE TITLE
Ink tutorial: Issue installing cargo-contract

### ISSUE THREAD

**Issue by jakerumbles** [substrate-developer-hub/substrate-docs#949]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Content request

Ink Tutorial: https://docs.substrate.io/tutorials/v3/ink-workshop/pt1/#install-the-cargo-contract-package

I was working through the above Ink tutorial and when I tried to install the cargo-contract package the first time I got an error:

Error:
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/25042987/163249338-a62688cb-da7a-4be2-9aa0-9c4ff1035900.png">

It suggested I run `cargo install dylint-link`. I installed that, then reran the cargo-contracts cargo install and it worked fine. I'm running this on a 2021 M1 Macbook Pro for context. Not sure if only me or a lot of people will run into this issue, but it might be nice to add this extra install command to the tutorial.

### Are you willing to help with this request?

Maybe (please elaborate above)

**Comment by pencoa** [comment]
I encountered the same issue.

**Comment by Maar-io** [comment]
Same problem as well

**Comment by NukeManDan** [comment]
https://ink.substrate.io/getting-started/setup#ink-cli indeed, more deps are needed.

**Comment by jakerumbles** [comment]
> https://ink.substrate.io/getting-started/setup#ink-cli indeed, more deps are needed.

Typo for devs? or departments?

**Comment by NukeManDan** [comment]
I don't understand exactly - this is a deps (dependencies) issue that was missed in updating the ink docs it seems :) Please report if not working as it is now in #1030 #1031

**Comment by jakerumbles** [comment]
Was confused on meaning of "deps". I got it now, thanks.
